### ISSUE TITLE
Page should fast-refresh when saving related .mdx file

### ISSUE THREAD

**Issue by NateRadebaugh** [hashicorp/next-mdx-remote#101]
If I'm writing a blog post, I like to see the rendered HTML as I'm writing the post. As it is now, next doesn't know the content has changed, so it doesn't re-render/update `getStaticProps`.

Should there be something that watches for changes in some configurable `./src/_posts` dir and re-updates?

**Comment by helloworld** [comment]
Check out: https://github.com/hashicorp/next-mdx-remote/issues/100. I've been using the library suggested ([next-remote-watch](https://github.com/hashicorp/next-remote-watch)) and it's been working perfectly for me.

**Comment by NateRadebaugh** [comment]
Thanks!

**Comment by xairoo** [comment]
Fast load is possible, no need to reload the whole site!
Have a look at https://github.com/hashicorp/next-mdx-remote/issues/100#issuecomment-1355866820.
