### ISSUE TITLE
Bump MDX to v2?

### ISSUE THREAD

**Issue by ooloth** [hashicorp/next-mdx-remote#103]
Thanks for this project!

MDX 2 has features I’d like to use, including [parsing MDX component children as MDX](https://github.com/mdx-js/mdx/issues/1312#issuecomment-717344406). 

Any chance you could bump the MDX dependency in this repo to V2?

**Comment by jescalan** [comment]
@ChristianMurphy mdx v2 has not yet been released and is still in beta - we will not be updating until its released. It's loosely on my agenda to start a beta branch but I don't have an exact timeframe there. You're welcome to fork and give it a shot!

Closing as this is answered but please feel free to continue discussion

**Comment by ChristianMurphy** [comment]
I don't think you meant to @ me, but in case you did.

You're welcome to start working with V2 beta.
If you have questions or concerns for the core team about MDX 2 itself, you're welcome to reach out at https://github.com/mdx-js/mdx/discussions

**Comment by jescalan** [comment]
Ah sorry, yeah I'm not sure how that happened. Thanks for the kind response though Christian!

**Comment by Ehesp** [comment]
We were interested in using v2 so created a PR https://github.com/hashicorp/next-mdx-remote/pull/164
