### ISSUE TITLE
`Cannot use import statement outside a module` error with certain components

### ISSUE THREAD

**Issue by helloworld** [hashicorp/next-mdx-remote#104]
Hi there, I'm having trouble using the react components from https://github.com/ooade/react-rough in my MDX files. 

Here's a minimal repo: 

```
import renderToString from "next-mdx-remote/render-to-string";
import hydrate from "next-mdx-remote/hydrate";
import ReactRough, { Rectangle } from "react-rough";

const Test = () => <h1>Test</h1>;

const components = {
  Test,
  ReactRough,
  Rectangle
};

export default function IndexPage({ source }) {
  const content = hydrate(source, { components });
  return <div className="wrapper">{content}</div>;
}

export async function getStaticProps() {
  // MDX text - can be from a local file, database, anywhere
  const source = `
    Some **mdx** text, with a component <Test />

    <ReactRough>
		  <Rectangle x={15} y={15} width={90} height={80} fill="red" />
  	</ReactRough>
  `;

  const mdxSource = await renderToString(source, { components });
  return { props: { source: mdxSource } };
}
````

When trying to render the page, I get this error:

![image](https://user-images.githubusercontent.com/3893054/106430499-e56d6f80-6439-11eb-8e97-988a4ecc5c83.png)

Do you have any ideas on how to properly import these components to use within MDX? I've also tried dynamic imports with no luck. 

Interestingly, I was able to reproduce this on Codesandbox, but I'm getting a slightly different error: https://codesandbox.io/s/vigilant-noyce-h3smc?file=/pages/index.js:0-798

Would really appreciate any help with this! Being able to use these components would be a huge win for me.

**Comment by jescalan** [comment]
You can't use imports with mdx remote. Give the readme a good once over and it should make it clear how you can make this happen.

Here's the section that specifies that you can't import within the file: https://github.com/hashicorp/next-mdx-remote#caveats

**Comment by helloworld** [comment]
Hey @jescalan, thanks for the quick response. I did read that section, so I apologize in advance for the confusion. 

The text there says the "import cannot be used inside an MDX file". My understanding of that phrase is that the MDX source cannot contain an import, which is the case in the example provided above. 

The text goes on to say "... should be provided through the second argument to the hydrate and renderToString functions", which I believe is what I'm doing above. 

Is there some detail that I'm completely missing or misunderstanding? Does "import cannot be used inside an MDX file" mean that I can't use components imported from a package?

**Comment by jescalan** [comment]
You're right - I'm so sorry I misread here. Something really unusual is going on with the `react-rough` package. I'm not sure what it is exactly, and I don't currently have the bandwidth to jump in and debug this one. If you are able to narrow down the issue a little more, that would be the best way to help push this one forward!

**Comment by helloworld** [comment]
No worries! Thank you for the clarification. I will try to get more info and report back on this issue

**Comment by BRKalow** [comment]
@helloworld It looks like `react-rough` and some of its dependencies are shipping es modules. I was able to get it working by using `next-transpile-modules` to tell next to run those packages through webpack. Here's a sandbox: https://codesandbox.io/s/loving-murdock-3wypm?file=/pages/index.js

**Comment by helloworld** [comment]
@BRKalow that's amazing, thank you so much for your help! I'll admit that my understanding of es modules is still shaky, so I doubt I would have made much progress myself.
