### ISSUE TITLE
hydrate should be prefixed with "use"

### ISSUE THREAD

**Issue by alattalatta** [hashicorp/next-mdx-remote#105]
`hydrate()` uses `useState()` and `useEffect()`, so it should be handled as a hook, i.e.

```ts
const Body = ({ children, needHydration }) => {
  let toRender = children

  if (needHydration) {
    toRender = hydrate(children, /* ... */) // Order of hooks may change!
  }

  return /* ... */
}
```

Of course, this code is quite an exaggeration - but I didn't know it actually was a hook until I looked at its code, so there _is_ some possibility.

The most easiest (but breaking) way to prevent such usage, in my opinion, is by prefixing it with `use`. This does two things:
1. Make [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks) recognize `hydrate()` as a hook. See ["What exactly do the lint rules enforce?"](https://reactjs.org/docs/hooks-faq.html#what-exactly-do-the-lint-rules-enforce).
2. Let users know that this function is a hook, and they shouldn't be placed inside any control or loop statements.

```ts
if (needHydration) {
  toRender = hydrate(children, /* ... */)
  // ESLint error: React Hook "useHydrate" is called conditionally
}
```

**Comment by jescalan** [comment]
Agreed and thank you for bringing this up. We'll include this in the next breaking release!

**Comment by jescalan** [comment]
Actually, this is a fairly simple change but I'd love if you were interested in opening a PR for it - it's a great way to get an open source contribution under the belt!

**Comment by alattalatta** [comment]
Sure, I'll have a look 😄

**Comment by BRKalow** [comment]
Thanks for the report, the `hydrate` API has been removed as of [v3.0.0](https://github.com/hashicorp/next-mdx-remote/releases/tag/3.0.0). I'm going to go ahead and close this. 🙏
