### ISSUE TITLE
Local build OK, Vercel build failing after next-mdx-remote 2.0 upgrade

### ISSUE THREAD

**Issue by brandonpittman** [hashicorp/next-mdx-remote#111]
This is a weird issue—possibly conflicting with something else—not sure.

next-mdx-remote 1.x.x package builds fine, but after upgrading to 2.0.1 (and tried with latest 2.1), I get this error when deploying to Vercel, but local build's are okay.

```
13:36:35.771 | Error: File /vercel/workpath0/node_modules/next-mdx-remote/node_modules/semver/preload.js does not exist.
-- | --
13:36:35.771 | at Job.emitDependency (/vercel/afe367d3340d9eb2/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:37791)
13:36:35.771 | at /vercel/afe367d3340d9eb2/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:38241
13:36:35.771 | at Array.map (<anonymous>)
13:36:35.771 | at Job.emitDependency (/vercel/afe367d3340d9eb2/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:38021)
13:36:35.771 | at async /vercel/afe367d3340d9eb2/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:38595
13:36:35.771 | at async Promise.all (index 0)
13:36:35.771 | at async Job.emitDependency (/vercel/afe367d3340d9eb2/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:37992)
13:36:35.771 | at async /vercel/afe367d3340d9eb2/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:38595
13:36:35.771 | at async Promise.all (index 3)
13:36:35.771 | at async Job.emitDependency (/vercel/afe367d3340d9eb2/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:37992)
```

Any idea what could be the cause of this?

Thanks!

---

The repo is public at <https://github.com/brandonpittman/site>.

**Comment by jescalan** [comment]
I'm sorry nothing is ringing a bell for me here and this stack trace doesn't look like its pointing back to anything in userland. This might be something worth asking vercel about, since the trace seems to point into their internals?

If it makes any difference at all, we have several sites running on vercel using version `2.x` and I haven't seen these errors. Maybe slowly stripping it down to a minimal reproduction would help too? I'm sorry, I know its a pain.

**Comment by brandonpittman** [comment]
@jescalan Contacted Vercel as well, but they had no answers as well. Just know that when I roll back to a commit with 1.x installed, it deploys without issue.

**Comment by jescalan** [comment]
It seems like you might need to dive a little deeper on the debugging here. Sorry this is happening at all though, I know the feeling and it's really frustrating 😠

**Comment by brandonpittman** [comment]
I'll just pin it at 1.x for now. Thanks.

**Comment by brandonpittman** [comment]
@jescalan 

I chased this issue down again with Vercel and they figured it out.

```
Hi Brandon,

This issue was caused by a Babel release.

Upon changing your dependencies you likely cleared the build cache entirely and with your next deployment caught the newer Babel release.
```

So, it seems next-mdx-remote just happened to be the thing that kept popping up with this Babel issue. Seems okay now. Apologies for creating an issue that didn't originate here.

**Comment by jescalan** [comment]
No worries! So glad you worked it out though 😀

**Comment by brandonpittman** [comment]
On to my new issue, Webpack 5 won't load my MDX content in getServersideProps when it works with Webpack 4! 😭
