### ISSUE TITLE
remark-gfm plugin warning when used with next-mdx-remote

### ISSUE THREAD

**Issue by marcofranssen** [hashicorp/next-mdx-remote#122]
Before I switched from `remark-html` to `next-mdx-remote`. there was no warning.

Now I'm using the following stack I'm getting this warning. `[remark-gfm] Warning: please upgrade to remark 13 to use this plugin`

```json
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-brands-svg-icons": "^5.15.3",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@tailwindcss/typography": "^0.4.0",
    "classnames": "2.3.1",
    "date-fns": "2.21.1",
    "gray-matter": "4.0.3",
    "js-yaml": "^4.1.0",
    "next": "latest",
    "next-mdx-remote": "^2.1.4",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "remark": "13.0.0",
    "remark-autolink-headings": "^6.0.1",
    "remark-emoji": "^2.2.0",
    "remark-external-links": "^8.0.0",
    "remark-gfm": "^1.0.0",
    "remark-slug": "^6.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^10.2.1",
    "next-remote-watch": "^1.0.0",
    "postcss": "^8.2.13",
    "tailwindcss": "^2.1.2"
  },
```

Is it possible to upgrade next-mdx-remote to `remark 13` like `remark-html`?

**Comment by jescalan** [comment]
Hey @marcofranssen - unfortunately remark is a dependency of mdx itself, we'd need to get mdx to update their dependency in order to move forward with this one. You're welcome to open an issue over there though, or downgrade the plugin in question to a compatible version!
