### ISSUE TITLE
components aren't pre-rendered?

### ISSUE THREAD

**Issue by JerryGreen** [hashicorp/next-mdx-remote#126]
My components that I put into `next-mdx-remote` have this [layout shift](https://web.dev/cls/) effect, which basically means they're rendered purely on client. Isn't it possible to pre-render them, to get rid of this layout shift?

P.S. `next-mdx-remote@2.1.4`

**Comment by jescalan** [comment]
They are server-rendered but hydrate lazily - we are working on changing this behavior with our upcoming release. Would you be interested in testing it out to see if this helps with your issue?

https://github.com/hashicorp/next-mdx-remote/pull/121

**Comment by BRKalow** [comment]
This should now be fixed on latest, please checkout the [3.0.0 release](https://github.com/hashicorp/next-mdx-remote/releases/tag/3.0.0) and let us know if you're still seeing the issue!
