### ISSUE TITLE
Output issues with blockquotes

### ISSUE THREAD

**Issue by m-bp** [hashicorp/next-mdx-remote#131]
`serialize()` gives me a different output than I'd get using remark directly

Input:

```
> This is a quote
# This is a header
```

Output:

```
<blockquote>
  <p>This is a quote</p>
  <h1>This is a header</h1>
</blockquote>
```

Expected output:

```
<blockquote>
  <p>This is a quote</p>
</blockquote>
<h1>This is a header</h1>
```

**Comment by BRKalow** [comment]
Interesting. We're using the latest stable `@mdx-js/mdx` package, `@mdx-js/mdx@1.6.22`, which I believe is on an older version of `remark`. I'm not sure if there's much we can do to address it in this package.

I believe adding an empty line between the quote and the header would fix your issue, if that is an option for you!

**Comment by m-bp** [comment]
In my case it kind of isn't as in my backend I'm using a MD editor which does process the quote correctly for its preview, therefore users don't add the empty line when writing the content and I can't expect them to.

**Comment by jescalan** [comment]
Closing this one, as we are not in control of the version of remark used by the mdx package. You are welcome to open an issue in mdx proper asking if they will upgrade remark, but this might be a bit tough to get around unfortunately, as they have a new release still in beta that they have probably run the upgrade for.
