### ISSUE TITLE
Broken component when using <MDXRemote lazy />

### ISSUE THREAD

**Issue by kalwabed** [hashicorp/next-mdx-remote#132]
I use Tailwind and I give its parent class `space-y-24`

```tsx
<article className="space-y-24">
	<MDXRemote {...mdxSource} components={MDXComponents} lazy />
</article>
```

pay attention to the distance between the components that I marked with the red line:

> with lazy
![image](https://user-images.githubusercontent.com/49640654/117170480-44a19e00-adf4-11eb-8719-4fc8eb363f2e.png)

> without lazy
![image](https://user-images.githubusercontent.com/49640654/117170439-39e70900-adf4-11eb-8518-66d71d21d431.png)

**Comment by BRKalow** [comment]
Would you be able to provide a minimal reproduction? Keep in mind that `lazy` adds an additional div around the rendered MDX out of necessity, per our docs:

> Note: this will add an additional wrapping div around your rendered MDX, which is necessary to avoid [hydration mismatches during render](https://reactjs.org/docs/react-dom.html#hydrate).

This might be impacting how the styles are applied 💭

**Comment by kalwabed** [comment]
I see. Thank you for the information. I don't think I'll use it on that page right now, but I used this feature on another page and it's great!

I'm closed now.
