### ISSUE TITLE
Updating to v3 breaks on vercel

### ISSUE THREAD

**Issue by AndrisBorbas** [hashicorp/next-mdx-remote#137]
I have a problem where if I try to update to v3 it runs fine locally, but on vercel it fails: https://gist.github.com/AndrisBorbas/396a3de325a12dcfdd1c95af95671250

I created a branch where I update everything else first, then next-mdx-remote and everything else works fine, but when next-mdx-remote gets updated it fails: https://github.com/AndrisBorbas/andrisborbas-com/tree/test

Earlier I tried it with webpack 4 as well to no success. These are all the changes I made for v3: https://github.com/AndrisBorbas/andrisborbas-com/commit/d269f72cfbf27e027e80bcbd9816637785b55e82

Also if I update to next@canary 10.2.1-canary.3 then the build succeeds but I get a 500 internal server error when visiting the page

**Comment by BRKalow** [comment]
Thanks for the report! If you run the next production build locally are you able to get any additional error messaging?

**Comment by AndrisBorbas** [comment]
It runs fine without any warning or error.

**Comment by anishathalye** [comment]
I had the same issue when deploying to Vercel: worked locally, but broke on Vercel in the same way. My local environment is macOS 11.2.3 / node v16.0.0 / npm 7.10.0. I was able to reproduce the breakage with the same error message as Vercel on a Linux box, Debian 9.11 / node v12.18.3 / npm 6.14.6 by running `next build`. As far as I remember, Vercel uses node v14. Perhaps it's an issue that shows up with earlier node versions?

(I haven't spent any time debugging this yet.)

**Comment by anishathalye** [comment]
This now works for me with the latest versions (next-mdx-remote@3.0.2 and next@10.2.3).

**Comment by jescalan** [comment]
This is a really weird one. Have you tried clearing out everything - node modules, package-lock, etc and regenerating from scratch?

**Comment by AndrisBorbas** [comment]
So updating everything, and next to 11 fixed it i guess, now everything just works.

**Comment by AndrisBorbas** [comment]
Also I would like to add that I had another project with basically the same setup and everything worked there, the only difference is that there everything was locally available, I had mdx files with the data in them, but in the project that broke i got the data from contentful.

**Comment by jescalan** [comment]
Closing this out as it seems to not be an issue anymore!
