### ISSUE TITLE
Infer correct types for children props in <pre> HTML Element

### ISSUE THREAD

**Issue by floroz** [hashicorp/next-mdx-remote#138]
## Problem

I would like to know whether there is a public interface provided by `next-mdx-remote` for the props that the compiler generates and passes onto the `MdxRemote.Component`.

This is not code I implemented so I want to make sure I am not making the wrong assumptions regarding the internals of `next-mdx-remote` .

### Setup

I have the following MDX Components list

```ts
const genericComponents: MdxRemote.Components = {
  // other components
  pre: PreCode,
 // more components
};
```

Those components are then used in the `hydrate` function.

The `PreCode` is a React Functional Component responsible of rendering the the corresponding HTML for 

```html
<pre>
  <code>
    my code snippet
  </code>
</pre>
```

Inside the `PreCode` component, I print the props that this component receives, 

```ts
const PreCode: React.FC = (props) => {
 console.log(props)

 return /* the JSX */
}
```

and I can see the following output:

<img width="674" alt="Screenshot 2021-05-10 at 14 58 57" src="https://user-images.githubusercontent.com/45793869/117662799-4080d200-b1a0-11eb-8e13-fdd3e0a8e239.png">

I see the following data structure that I declare in my component's prop interface:

```ts
// in precode.tsx


interface Props {
  children: {
    /**
     * props object here is the result of `next-mdx-remote` compiler generating additional properties:
     */
    props?: {
      /**
       * The serialized string containing the code to insert within the <code> tag.
       */
      children?: string;
      /**
       * The className prop is the language declared in the markdown scope for the code snippet.
       *
       * Example: If I declare the following within a markdown file:
       *```mdx
       *  ```js
       *  var count = 0;
       *  ```
       * ```
       *
       * Then the className generated would be `language-js`.
       */
      className?: `language-${Language}`;
      mdxType?: keyof HTMLElementTagNameMap;
      originalType?: string;
      parentName?: string;
    };
  };
}

```

I digged a bit around and it seems that this props are provided by the `@mdx-js` package, but cannot really pinpoint where I can find a publicly expose interface.

**Comment by jescalan** [comment]
Yeah I think what you're seeing there is a `React.ReactElement` type - provided by react and not by this package. Sorry for the late response and hope this helps! If you want to define a type for an element with its props it would be like this:

```tsx
// you have to define your own props of course
interface ComponentProps {
  className?: `language-${Language}`;
  mdxType?: keyof HTMLElementTagNameMap;
  originalType?: string;
  parentName?: string;
}

// and here's the typing for a react element with those props
React.ReactElement<ComponentProps>
```
