### ISSUE TITLE
Verifying/checking if MDX `source` has been already serialized

### ISSUE THREAD

**Issue by ScottAgirs** [hashicorp/next-mdx-remote#139]
Hey fellas, been a big fan of Hashiworks for a while, and this package is just 🔥

Enough of that, tho, I'm wondering if there's any API available out of the box to verify if the source has been already serialized?

## Use-case

Once I pass the `source` from server to client, I would like to check first if for whatever reason the `source` is not a serialized MDX data, and if it's not or if it's empty or whatever else, I would like to conditionally render different parser.

That said, if this is not yet a thing, I would like to propose a feature; – implementation of which could look something like this:

```jsx
import { verify } from 'next-mdx-remote/serialize';
import { MDXRemote } from 'next-mdx-remote';

import MyOwnParser from './makaka/parser';

...

const SmallBigComponent = ({ source }) => {
  const isValidSource = verify(source);
  ...
  return isValidSource ? <MDXRemote source={source} /> : <MyOwnParser source={source} />
}
```

Many thanks for this siiiiick package.

**EDIT**
Or perhaps it would make sense to bake this functionality into the `MDXRemote />` and return a more meaningful error message, since currently the returned error reads:
`ReferenceError: MDXContent is not defined` 

This of course works well, if the data is not present, but if the source is:
```js
  const source = "Non MDX string, not serialized, u kno'";
```
then the error message should be more accurate, actually, I think either way it should be more accurate, haha. Oktnxbye

**Comment by BRKalow** [comment]
You might be able to check the shape of `source`, here's the TS interface:
https://github.com/hashicorp/next-mdx-remote/blob/3d1c70759e6450b1384567823412199a0119bcbc/src/types.ts#L28-L40

I would guess that your source would be a string, while the result from `serialize` would be an object. 

Do you think that would work?

**Comment by ScottAgirs** [comment]
> You might be able to check the shape of `source`, here's the TS interface:
> https://github.com/hashicorp/next-mdx-remote/blob/3d1c70759e6450b1384567823412199a0119bcbc/src/types.ts#L28-L40
> 
> I would guess that your source would be a string, while the result from `serialize` would be an object.
> 
> Do you think that would work?

Hola, thanks for the suggestion, that may work, but to be honest, it looks like the issue was actually implementation of the component, I passed in the source as a prop, rather than spreading the source, so instead of `MDXRemote {...source} />` I did `MDXRemote source={source} />`.

With that (for non-TS users) maybe there's a way to improve the error message... 🤔

**Comment by BRKalow** [comment]
@ScottAgirs I'm going to go ahead and close this for now, if you are up for it feel free to create an issue proposing some more helpful runtime error messaging when we encounter common misuses, such as passing `source` as a prop instead of spreading. Thanks!
