### ISSUE TITLE
Issues rendering with react-testing-library

### ISSUE THREAD

**Issue by mudetroit** [hashicorp/next-mdx-remote#141]
I am working on a component that is rendering the output from `next-mdx-remote`. I am loading the mdx within `getStaticProps` on the page as outlined in the docs. to support styling we pass the output from that to another component which then renders `MDXRemote`. We have a simple rendering test on that wrapping component, but when that tests runs we get

> Error: Uncaught [ReferenceError: MDXContent is not defined]

Simplest working example I can give looks like this
```
// Component.js
import { MDXRemote } from 'next-mdx-remote'

// In real code this does work but not relevant here
function StyleContent({children}) {
  return <div>{children}</div>
}

const components = {
  Test: () => <>test</>
}

export function Component({ source }) {
  return (
    <StyledContent>
      <MDXRemote {...source} components={components} />
    </StyledContent>
  )
}
```

```
// Component.test.js
import { render, screen } from '@testing-library/react'
import { serialize } from 'next-mdx-remote/serialize'

import { Component } from '/Component.js'

describe('InstallationContent', () => {
  const mdx = 'hello world <Test />'
  const source = serialize(mdx)

  it('should render without crashing', () => {
    render(<Component source={source} />)
    expect(screen.getByTestId('installation-content')).toBeInTheDocument()
    expect(screen.getByText('hello world')).toBeInTheDocument()
  })
})
```

Is there something basic to this lib that would prevent it from running within a testing context? I could return a mock function instead of using it, but would rather get the confidence it is doing what I expect here.

**Comment by jescalan** [comment]
Thank you for the straightforward reproduction here - we'll look into this soon!

**Comment by BRKalow** [comment]
Curious if `await`ing the call to `serialize` in your test case would fix this:
```jsx
// Component.test.js
import { render, screen } from '@testing-library/react'
import { serialize } from 'next-mdx-remote/serialize'

import { Component } from '/Component.js'

describe('InstallationContent', async () => {
  const mdx = 'hello world <Test />'
  const source = await serialize(mdx)

  it('should render without crashing', () => {
    render(<Component source={source} />)
    expect(screen.getByTestId('installation-content')).toBeInTheDocument()
    expect(screen.getByText('hello world')).toBeInTheDocument()
  })
})
```

**Comment by mudetroit** [comment]
🤦‍♂️ yep that was it and now I am feeling a bit silly. I had run into a similar problem first implementing it in production because I didn't spread source in. Not sure if there is a way to get a more helpful error message in there, but this doesn't look like a fundamental problem.

**Comment by BRKalow** [comment]
I think some runtime errors could be helpful if we can detect common mistakes like this! Thanks for the suggestion 😄
