### ISSUE TITLE
How can I get the renderedOutput in v3?

### ISSUE THREAD

**Issue by MichaelBurgess** [hashicorp/next-mdx-remote#147]
In v2 I was able to pass my MDX through the `renderToString` function and get back `renderedOutput` (which was a JSX string).

In v3 I don't see this any more, only `compiledSource`.

Can I get the `renderedOutput` JSX in v3?

I use this in my `getStaticProps` function to built an AST from that I can do some further interrogation / manipulation with.

**Comment by BRKalow** [comment]
Unfortunately we don't expose rendered markup from `serialize`, as the rendering is now done within the application itself.

Can you expand more on what you are trying to accomplish? Would a custom remark plugin or rehype plugin allow you to manipulate the content as needed? You can pass those to serialize, see the [API docs](https://github.com/hashicorp/next-mdx-remote#apis).

**Comment by MichaelBurgess** [comment]
@BRKalow I build things such as Algolia search records from the markdown, so the way I've done that is to first render the markdown to a JSX string (which I do with v2). I then pass that string into a HTML transformer, which allows me to do things like strip tags, strip content, replace content etc to make my HTML easier to index. Finally I build an AST from the transformed HTML and from that I can extract the various things I need to build my search records.

I'm also building a TOC from the AST e.g. get all the h2's from the markdown.

Not sure if there's an obvious way I'm missing to achieve the above? Not looked into building any custom plugins to do that.

**Comment by BRKalow** [comment]
Makes sense! I think a remark/rehype plugin would be great for this use case, as under the hood an AST is generated from the MDX source. It might be actually more efficient to do it this way as you wouldn't need to parse the markup again.

Here's an example remark plugin which generates a TOC: https://github.com/remarkjs/remark-toc

**Comment by lostfictions** [comment]
Just chiming in that I also still have usecases for `renderToString` that I was hoping to continue to be able to use `next-mdx-remote` for! As I mentioned last year in #61, it was really useful to be able to use MDX for non-interactive (that is, without any dynamic behaviour) layout or presentational elements for which static HTML rendering was sufficient. Is that no longer on the table for this library?

**Comment by BRKalow** [comment]
@lostfictions The approach outlined in #133 is both more efficient and more predictable than the previous implementation, as we won't be shipping the markup twice (both in the serialized data as well as in the document HTML). I would definitely recommend using that approach instead of rolling back.

**Comment by MichaelBurgess** [comment]
> Makes sense! I think a remark/rehype plugin would be great for this use case, as under the hood an AST is generated from the MDX source. It might be actually more efficient to do it this way as you wouldn't need to parse the markup again.
> 
> Here's an example remark plugin which generates a TOC: https://github.com/remarkjs/remark-toc

Thanks @BRKalow I'll look into this when I get some time!

**Comment by lostfictions** [comment]
> @lostfictions The approach outlined in #133 is both more efficient and more predictable than the previous implementation, as we won't be shipping the markup twice (both in the serialized data as well as in the document HTML). I would definitely recommend using that approach instead of rolling back.

Thanks! That's useful to know -- from here it wasn't clear if it the first technique you suggested in https://github.com/hashicorp/next-mdx-remote/issues/133#issuecomment-835857581 actually worked (the _might_ in "you _might_ be able to accomplish this" sort of gave me the heebie-jeebies). Plus the combo of "use `React.memo` to trick it into never rerendering and disappearing" and `suppressHydrationWarning` made it seem like a brittle hack. And as you mention in that issue, the result of `serialize` is shipped to the client either way, so at the end of the day don't you still end up with duplication (that is, server-rendered markup plus rendundant serialized data shipped to the client)?

(None of that is a dealbreaker, obviously, and I'm sure the serialized result is more compact than shipping the full markup. I get that there's ultimately no perfect solution to this other than some kind of build-time step that's ultimately outside the scope and goals of this project.)
