### ISSUE TITLE
KaTeX with next-mdx-remote

### ISSUE THREAD

**Issue by gazzza** [hashicorp/next-mdx-remote#148]
I'm trying to follow the guides from here and get a next-mdx-remote implementation: 

https://mdxjs.com/guides/math-blocks

using the following MWE (packages required: remark-math, rehype-katex): 

        import Head from 'next/head'
        import styles from '../styles/Home.module.css'
        import { MDXRemote } from 'next-mdx-remote';
        import { serialize } from 'next-mdx-remote/serialize'
        
        
        const data = `# Testing KaTeX
        
        This is the number $x = 13$ and this
        
        $$
        E = mc^2
        $$
        
        is an equation`
        
        export default function Home({ mdxSource }) {
          return (
            <div className={styles.container}>
              <Head>
                <title>KaTeX test</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css" integrity="sha384-Um5gpz1odJg5Z4HAmzPtgZKdTBHZdw8S29IecapCSB31ligYPhHQZMIlWLYQGVoc" crossOrigin="anonymous" />
        
              </Head>
        
              <div>
        
                <span className="katex">
                  <span className="katex-mathml">The KaTeX stylesheet is not loaded!</span>
                  <span className="katex-version rule">KaTeX stylesheet version: </span>
                </span>
        
                <MDXRemote {...mdxSource} />
        
              </div>
        
            </div>
          )
        }
        
        
        export async function getStaticProps() {
        
          const mdxSource = await serialize(data, {
            mdxOptions: {
              remarkPlugins: [
                require('remark-math')
              ],
              rehypePlugins: [
                require('rehype-katex')
              ],
            },
          })
          return {
            props: {
              mdxSource
        
            }
          }
        
        
        
        }

However the output isn't working, as can be seen by the following: 

<img width="483" alt="Screenshot 2021-05-22 at 10 54 19" src="https://user-images.githubusercontent.com/5956335/119222383-11495980-baec-11eb-9a73-0a9708a741bd.png">

even though it seems the KaTeX stylesheet has been correctly loaded.

Sandbox below:

https://codesandbox.io/s/katex-44nge?file=/pages/index.js

I would be grateful if anyone can advise as to what I'm doing wrong or how to further debug this issue.

**Comment by coravacav** [comment]
I'm not certain if this removes any MDX functionality, but I fixed this by adding `markdown` before `remarkMath` plugin (from the package `remark-parse`). 

Here's a sandbox with the fix:
https://codesandbox.io/s/katex-forked-o6z66

**Comment by gazzza** [comment]
Thank you coravacav - that certainly works in terms of rendering the KaTeX but does indeed stop custom mdx components rendering with an error: 

TypeError: Cannot read property 'className' of undefined

I imagine remark-parse can only work with the standard markdown elements? 

This project seems to have this all implemented just fine and I'm copying the essential features as far as I can tell but it still doesn't seem to work on the above SandBox. 

https://github.com/timlrx/tailwind-nextjs-starter-blog

**Comment by timlrx** [comment]
You don't need to add `remark-parse` because the [mdx package already does it](https://github.com/mdx-js/mdx/blob/main/packages/mdx/index.js#L15). Custom mdx components also work as shown in this sandbox: https://codesandbox.io/s/katex-forked-6s6qm?file=/pages/index.js

**Comment by timlrx** [comment]
Oh you need to use `remark-math` v3 as in my blog's config as well.

**Comment by gazzza** [comment]
Hi Tim

Thanks for your comments - the sandbox has the custom component but doesn't actually render the maths? 

I tried downgrading remark-math to v3 as you mentioned but this still doesn't render the maths:

https://codesandbox.io/s/katex-forked-k04q1?file=/pages/index.js

So at the moment it seems like an odd situation - add remark-parse and the maths renders but none of the custom components, remove it and the custom components render but not the maths. It's strange that adding it at all changes anything given the mdx package already uses it, as you say.

**Comment by timlrx** [comment]
It works fine - you have to restart your codesandbox server. https://codesandbox.io/s/katex-forked-jegb7?file=/pages/index.js

**Comment by gazzza** [comment]
Doh! You are absolute right, it works. 

Thanks very much for your help Tim. 

So it seems that simply using remark-math@3.0.0 fixes this problem, for some unknown reason.

**Comment by jescalan** [comment]
Thanks for the all star support @timlrx ! 🏆
