### ISSUE TITLE
Module not found: Can't resolve 'child_process'

### ISSUE THREAD

**Issue by Daavidaviid** [hashicorp/next-mdx-remote#149]
In development mode, with `v3.0.2`
I'm getting this issue : 

```
error - ./node_modules/esbuild/lib/main.js:1535:0
Module not found: Can't resolve 'child_process'
```

Someone ever got this one ?

**Comment by crazyrumer** [comment]
Yep, Got it as well

`error - ./node_modules/esbuild/lib/main.js:1535:0
Module not found: Can't resolve 'child_process'
null
`

Repro:
1) Add import { serialize } from 'next-mdx-remote/serialize';
2) npm run develop

**Comment by jescalan** [comment]
Is anyone able to provide a full repro here?

**Comment by glassblowerscat** [comment]
I'm seeing this exact same error. Wasn't yesterday, am today. Haven't changed anything about my config. 

I don't have time to make a dedicated repo just for this (and I'm not sure I'd be able to reproduce the issue with a new app). But I could provide my repo for inspection, if it would help. It's a personal project, so nothing secret or fancy. @jescalan, let me know if that would be helpful.

**Comment by glassblowerscat** [comment]
I'm seeing the error on 3.0.1 and 3.0.0 as well as 3.0.2

**Comment by jescalan** [comment]
It would definitely be helpful, thank you!

**Comment by glassblowerscat** [comment]
> It would definitely be helpful, thank you!

Okay, so I actually resolved my own issue. Here's what happened:

I had abstracted my use of `serialize` into its own function, like this:

```
import smartypants from "@silvenon/remark-smartypants"
import matter from "gray-matter"
import { serialize } from "next-mdx-remote/serialize"
import numberedFootnotes from "remark-numbered-footnotes"
import { Pluggable } from "unified"

[... one other function that I only used in `getStaticProps`/`getStaticPaths`]

export async function parseMarkdown(
  file: Buffer,
  scope?: Record<string, unknown>
) {
  const { data, content: parsedContent } = matter(file)
  const content = await serialize(parsedContent, {
    mdxOptions: {
      remarkPlugins: [numberedFootnotes as Pluggable, smartypants as Pluggable],
    },
    ...(scope ? { scope } : null),
  })
  return { data, content }
}

```

I put this in a file called `parsers.ts`. This was fine. But just now I added another function to `parsers.ts` that **runs on the client**. The file then imported `serialize`, which imports `esbuild`, which imports `child_process`, and there we have our error.

Moving my new function to a new file so that `parsers.ts` is only ever imported on the server resolves the issue.

Hopefully this is helpful to others experiencing this issue.

**Comment by Daavidaviid** [comment]
Make sense ! I'm gonna try to rewrite my code to avoid this case too

**Comment by jescalan** [comment]
Ah good find, thanks for digging deeper and finding the fix! I tried to make a brief mention of this [under the example section in the readme](https://github.com/hashicorp/next-mdx-remote#examples), but perhaps that could be more clear. Nextjs' bundle separation is a bit of a magical thing that can be tough to keep in mind at times for sure.

**Comment by Daavidaviid** [comment]
Unfortunately, i wasn't able to get it to work
Even copy/pasting the code in example section in a `post/[slug].tsx` get me this error 🥲

**Comment by Daavidaviid** [comment]
I didn't mention it but I'm using it with expo/React Native Web, so I think the issue comes from this. In a new project it works perfectly
