### ISSUE TITLE
Using MDX remote to include data from redux toolkit store

### ISSUE THREAD

**Issue by cordobadigitalmedia** [hashicorp/next-mdx-remote#150]
Hi
This is more of a question.
How would you include redux toolkit store and make it available to a component inside an mdx file that is being loaded by mdxremote?

**Comment by jescalan** [comment]
I'm sorry, I'm not sure. If anyone else in the community has an answer you are welcome to pitch in. I'm going to close this as it's not an issue, but my no means take this as an end to discussion!
