### ISSUE TITLE
Internationalization and posts

### ISSUE THREAD

**Issue by IrvingArmenta** [hashicorp/next-mdx-remote#152]
I have this question as well in `next-mdx` but I can't seem to get any answer.

I followed the `blog` example, and it works fine as expected, however, when I introduce localized paths, it seems to not be able to find the data.

here it's my getStaticPaths function:  
```tsx
export const getStaticPaths = async (ctx: GetStaticPathsContext) => {
  const paths = postFilePaths
    // Remove file extensions for page paths
    .map((path) => path.replace(/\.mdx?$/, ''))
    // Map the path into the static paths object required by Next.js
    .map((slug) => ctx.locales?.map((locale) => ({ params: { slug, locale } })))
    .flat();

  console.log(paths);

  return {
    paths,
    fallback: true
  };
};
```
this returns: 
```js
[
  { params: { slug: 'byebye', locale: 'en-US' } },
  { params: { slug: 'byebye', locale: 'es-MX' } },
  { params: { slug: 'byebye', locale: 'ja' } },
  { params: { slug: 'hello', locale: 'en-US' } },
  { params: { slug: 'hello', locale: 'es-MX' } },
  { params: { slug: 'hello', locale: 'ja' } }
]
```
this is my `next.config.file`:

```js
module.exports = {
  reactStrictMode: true,
  future: {
    webpack5: true
  },
  i18n: {
    locales: ['en-US', 'es-MX', 'ja'],
    defaultLocale: 'en-US'
  },
  webpack(config, options) {
    config.module.rules.push({
      test: /\.svg$/,
      issuer: /\.(js|ts)x?$/,
      use: [
        options.defaultLoaders.babel,
        {
          loader: '@svgr/webpack',
          options: {
            titleProp: true
          }
        },
        'file-loader'
      ]
    });
    return config;
  }
};
```
my structure it's just a step inside `/src` so it's `src/blog/index.tsx` and `src/blog/[slug].tsx` where the index gets the posts t list them and the `[slug]` it's just like the example.

is there something I'm missing?

**Comment by IrvingArmenta** [comment]
Here it's a `codesandbox` https://codesandbox.io/s/currying-fire-04ez1 

I'm not sure why there is an error in `/blog/index.tsx` for not finding the utils file, however I think this is related to cache and codesandbox.   

The issue again is that when accessing the `/blog/post-slug`  page with a language path e.g. `/es-MX/blog/post-slug` the `[slug].tsx` page takes some time to load at `getStaticProps` , it seems to wait for the `next frame` to actually render the data from the `mdx` file, so I had to setup `fallback: true` and use a hook `useEffect` to update the info, but If I don't setup the `fallback` to `true` , then the page just throws a `404` error. 

My desired functionality  is that the page renders and getStaticProps works as the same with or without a language prefix in the pathname.

here it's the `postFilePaths` function that I took directly from the `nextjs with next-mdx-remote` example:

```ts
import fs from 'fs';
import path from 'path';

// POSTS_PATH is useful when you want to get the path to a specific file
export const POSTS_PATH = path.join(process.cwd(), '/src/_posts');

// postFilePaths is the list of all mdx files inside the POSTS_PATH directory
export const postFilePaths = fs
  .readdirSync(POSTS_PATH)
  // Only include md(x) files
  .filter((path) => /\.mdx?$/.test(path));
  ```

**Comment by jescalan** [comment]
I tried running the code sandbox but there are errors all over the place. it looks like many of the import paths are incorrect. is there any way you can take another pass on this and make sure it runs at base?

**Comment by nico-bachner** [comment]
@IrvingArmenta this might be what's causing the main underlying issue. The following doesn't correspond to what Next.js expects to be returned:
```js
{
    params: {
        slug: 'hello';
        locale: 'en-US';
    };
}
```


Try this instead:
```js
{
    params: {
        slug: 'hello';
    };
    locale: 'en-US';
}
```
