### ISSUE TITLE
Markdown links next to React components are not built

### ISSUE THREAD

**Issue by PandaSekh** [hashicorp/next-mdx-remote#158]
When using markdown urls next to a react component, the url will not be converted to <a> tags in html.

Example of code that will break:
`[Some url](some.url) and also a <ReactComponent />`

In this case the component will be rendered but not the link.

Found this on the MDX repo: [https://github.com/mdx-js/mdx/issues/628](https://github.com/mdx-js/mdx/issues/628)

**Comment by BRKalow** [comment]
Hey there! As noted in the issue linked, this has landed in mdx-js v2, which is not yet stable, and as such we have not integrated it into this library. Once v2 lands as stable we'll look at adopting it then. I'm going to close this as it's not something that can be addressed by this library at this point.
