### ISSUE TITLE
Npm Audit report showing 5 high severity vulnerabilities

### ISSUE THREAD

**Issue by IamManchanda** [hashicorp/next-mdx-remote#161]
I am using latest version of `next-mdx-remote` => `^3.0.2`

I am currently getting this log once I run `npm audit`

<img width="930" alt="Screenshot 2021-06-10 at 6 09 25 PM" src="https://user-images.githubusercontent.com/4970624/121526742-4d027f80-ca17-11eb-92fd-4c052311755b.png">

**Comment by jescalan** [comment]
Dupe https://github.com/hashicorp/next-mdx-remote/issues/144
