### ISSUE TITLE
How can I render multiple post types from the root?

### ISSUE THREAD

**Issue by Ibaslogic** [hashicorp/next-mdx-remote#162]
Can someone please assist?

I have two post types `blog` and `series` which I want to render their content from the root (for instance, `site.com/post1`). 

```
project
    ├── data
    │    ├── blog
    │    │    ├── post1.mdx
    │    │    └── post2.mdx
    │    ├── series
    │    │    ├── post1.mdx
    │    │    └── post2.mdx
    ├── pages
    │    ├── [slug].js
```

I understand we can use the `next-mdx-enhanced` layouts and specify which template to use for the individual post type. But from the doc, it's advisable to use the `next-mdx-remote`.

Now, I have set up the plugins and rendered the content of the `series` using the dynamic route, `[slug]`. Please how can I render the content of the `blog` to display also from the root, `/post1`.

Thank you.

**Comment by jescalan** [comment]
Hey @Ibaslogic! I am not able to offer full support here, if someone else is and jumps in that would be very lovely. I just want to mention that we have an example of a blog setup here if that helps you to get oriented!

https://github.com/vercel/next.js/tree/canary/examples/with-mdx-remote

**Comment by timlrx** [comment]
Hi, just came across this issue. If you are looking to render based on a particular layout template name provided in the frontmatter, you can check out a possible implementation on my [blog template](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/v1/components/MDXComponents.js)

Basically it's a higher order component that takes in the layout frontmatter, loads it and render `MDXRemote`.

```
export const MDXLayoutRenderer = ({ layout, mdxSource, ...rest }) => {
  const LayoutComponent = require(`../layouts/${layout}`).default

  return (
    <LayoutComponent {...rest}>
      <MDXRemote {...mdxSource} components={MDXComponents} />
    </LayoutComponent>
  )
}
```
