### ISSUE TITLE
ReferenceError: MDXContent is not defined

### ISSUE THREAD

**Issue by teyo5** [hashicorp/next-mdx-remote#166]
Hello and thanks in advance for your help!

I am getting this error:

<img width="747" alt="Bildschirmfoto 2021-06-23 um 20 35 26" src="https://user-images.githubusercontent.com/77794938/123150355-8e0c8200-d462-11eb-9620-e0a1d739f495.png">

It was working fine before but since I added the frontMatter to props in [slug].jsx I can't get rid of this error..

(I am working on a blog that uses functions from my mdx.js file to get the markdown data I need.)

[slug].jsx --> the page where the blog post is shown
```
import React from 'react';

import hydrate from 'next-mdx-remote/hydrate';

import { getFiles, getFileBySlug, getFileFrontMatter } from '../../src/utils/mdx';
import MovieLayout from '../../src/layouts/movie';

export default function Movie({ mdxSource }) {
  const content = hydrate(mdxSource);

  return (
    <div className="z-50 fixed top-0 bg-black text-white min-h-screen min-w-full">
      <MovieLayout frontMatter="">{content}</MovieLayout>
    </div>
  );
}

export async function getStaticPaths({ locales }) {
  const paths = [];

  for (const locale of locales) {
    const filenames = await getFiles('movies', locale);

    for (const filename of filenames) {
      const slug = filename.replace(/\.mdx/, '');
      paths.push({ params: { slug }, locale: locale });
    }
  }

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params, locale }) {
  const mdxSource = await getFileBySlug('movies', params.slug, locale);
  const frontMatter = await getFileFrontMatter(locale, 'movies', params.slug);

  return { props: { mdxSource, frontMatter } };
}
```

mdx.js --> where the functions are which I use to get the data
```
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import renderToString from 'next-mdx-remote/render-to-string';

const root = process.cwd();

export async function getFileBySlug(type, slug, locale) {
  const source = slug
    ? fs.readFileSync(path.join(root, `src/content/${locale}`, type, `${slug}.mdx`), 'utf8')
    : fs.readFileSync(path.join(root, `src/content/${locale}`, `${type}.mdx`), 'utf8');

  const mdxSource = await renderToString(source);

  return { mdxSource };
}

export async function getFileFrontMatter(locale, type, slug) {
  const fileSlug = slug + '.mdx';
  const file = fs.readFileSync(path.join(root, `src/content/${locale}`, type, fileSlug), 'utf8');
  const { data } = matter(file);

  return data;
}

```

I hope you can help!
Thanks in advance!

**Comment by jescalan** [comment]
There was [a major version update to this library](https://github.com/hashicorp/next-mdx-remote/releases/tag/3.0.0) recently - is it possible that you updated the version and didn't read the release notes? This is what I'm guessing based on the error and the code, which looks to be written for the previous version.

**Comment by ksorv** [comment]
@jescalan I'm seeing this error too. Tried it with:

- next 10, 11
- webpack 4,5
- node 12-15

On dev it works fine... but while running build it throws `MDXContent is not defined`.

I even checked the compiled source, It had the MDXContent right there... but the ``${compiledSource}return MDXContent;` line  just keeps throwing this.

Can someone take a look at this?

**Comment by teyo5** [comment]
@jescalan I was using an older version. I updated it now to the latest version and it still throws an error - only the message changed.

<img width="731" alt="Bildschirmfoto 2021-06-25 um 14 29 02" src="https://user-images.githubusercontent.com/77794938/123424862-b232a500-d5c1-11eb-9598-173e78067651.png">

**Comment by jescalan** [comment]
@teyo5 you can't just upgrade the version, there are also code changes needed. If you check out [the release notes](https://github.com/hashicorp/next-mdx-remote/releases/tag/3.0.0) it should help!

**Comment by teyo5** [comment]
@jescalan yes, of course I also made the necessary code changes.. 

I think I solved the issue partly by making these changes":

1. mdx.js
```
export async function getFileBySlug(type, slug, locale) {
  const source = slug
    ? fs.readFileSync(path.join(root, `src/content/${locale}`, type, `${slug}.mdx`), 'utf8')
    : fs.readFileSync(path.join(root, `src/content/${locale}`, `${type}.mdx`), 'utf8');

  const frontMatter = matter(source);
  const mdxSource = await serialize(source);

  return { mdxSource, frontMatter };
}
```

2. [slug].jsx
```
export async function getStaticProps({ params, locale }) {
  const source = await getFileBySlug('movies', params.slug, locale);
  const mdxSource = source.mdxSource;
  const frontMatter = source.frontMatter.data;

  return { props: { mdxSource, frontMatter } };
}
```

Was this the right move? ..I don't understand what difference it makes - maybe you do?

--> And I don't understand why my mdxSource includes "title: 'Filmtitel 2' publishedAt: '2021-03-21' summary: 'Summary of movie - quick descr' image: '/res/movieList/12.png'" although this part of the front-matter in the mdx file?

Thanks in advance :)

(And thank you for the version tip! ..don't know why I didn't update it sooner)

**Comment by jescalan** [comment]
It's really hard to tell with just random snippets of code here, I can't really see the full flow. If you want help debugging here, the best way would be to create a minimal reproduction and post it here -- that means creating a project that only contains the least possible code that can be used to demonstrate your issue. If you can provide that I should be able to dig in and point out the issue specifically!

**Comment by teyo5** [comment]
@jescalan Ok, thank you for your help so far and sorry that it took so long. Here is a repository with my issue - thanks in advance!

--> https://github.com/teyo5/next-mdx-remote-issue

**Comment by jescalan** [comment]
Thank you - this allowed me to spot the problem quickly. It's on [these lines here](https://github.com/teyo5/next-mdx-remote-issue/blob/9ea31104b2a9d0ede4a14585cbb93c50f77c0811/src/utils/mdx.js#L23-L24).

It should instead be formatted as such:

```js
const { content, data } = matter(source);
const mdxSource = await serialize(content);
```

Here's why. `gray-matter` pulls apart the page content and the frontmatter. It [returns an object](https://github.com/jonschlinkert/gray-matter#returned-object) that contains the frontmatter data as well as the contents of the file with the front matter removed. So imagine you have a file like this:

```md
---
title: foo
---

Here's my *markdown* content
```

When you run `gray-matter` on it as I showed in the example above, it will return as such:

```js
const { content, data } = matter(source);
// => content: "Here's my *markdown* content"
// => data: { title: 'foo' }
```

Then you take the content it returns, without the front matter, and pass _that_ into serialize, so that you display your post's content without the front matter.

Hope this makes sense! There is also [a section in the readme](https://github.com/hashicorp/next-mdx-remote#frontmatter--custom-processing) that covers this specifically.

**Comment by teyo5** [comment]
@jescalan  Thank you - that solved it ! :)
