### ISSUE TITLE
Not using latest esbuild version

### ISSUE THREAD

**Issue by PabloSzx** [hashicorp/next-mdx-remote#168]
Is there any reason for this library to not be using the latest version of esbuild? 

Right now we have to use `pnpm.overrides`/`yarn resolutions` to force next-mdx-remote to use `^0.12.9` to not have conflicting/duplicated versions of esbuild, since this package is using the range of the previous version `"esbuild": "^0.11.12"`.

And thank you for this project btw, it's powering [the-guild-docs](https://github.com/the-guild-org/the-guild-docs) as a docusaurus replacement 👍

**Comment by jescalan** [comment]
Not that I know of! Would you be interested in contributing a dependency boost here since you noticed?
