### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by vineetver** [hashicorp/next-mdx-remote#170]
I've been trying to get next-mdx-remote working for days now but.....

![Screenshot 2021-06-27 143440](https://user-images.githubusercontent.com/66165922/123538954-da9ed880-d754-11eb-871c-0a0b72ac88e9.png)

Here's my package json
``` "dependencies": {
    "@headlessui/react": "^1.2.0",
    "@heroicons/react": "^1.0.1",
    "graphql": "^15.5.1",
    "graphql-request": "^3.4.0",
    "he": "^1.2.0",
    "next": "^11.0.0",
    "next-mdx-remote": "^3.0.2",
    "next-themes": "^0.0.14",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "typed.js": "^2.0.12"
  },
  "devDependencies": {
    "autoprefixer": "^10.0.4",
    "eslint": "^7.28.0",
    "eslint-plugin-react": "^7.24.0",
    "postcss": "^8.1.10",
    "prettier": "^2.3.1",
    "prop-types": "^15.7.2",
    "tailwindcss": "^2.2.4"
  }````

**Comment by parzuko** [comment]
`next-mdx-remote/hydrate` and `next-mdx-remote/render-to-string` have now migrated to  `<MDXRemote />`  and `serialize ` respectively.


source: [here](https://github.com/hashicorp/next-mdx-remote/releases/tag/3.0.0)
