### ISSUE TITLE
Share State between the [slug] and the MDXComponents

### ISSUE THREAD

**Issue by serban-mihai** [hashicorp/next-mdx-remote#172]
Didn't catch anything related into the Docs but is there a way to access State Hooks that are declared into the [slug] component from the Custom MDXComponents that are passed to the `<MDXRemote/>` component? 

I have this setup in **[slug].jsx**
```
const [test, setTest] = useState("WORKS")

<article
   id="scrollArea"
   prose dark:prose-dark min-w-0 max-w-sm desktop:max-w-xl px-5 flex flex-col items-stretch justify-items-center"
>
   <MDXRemote
       {...mdxSource}
       components={{ ...MDXComponents }}
/>
</article>
```

and this into **MDXComponents.jsx**
```
const CustomLink = (props) => {
  console.log(test) // I NEED THIS TO RETURN "WORKS"
  const href = props.href;
  const isInternalLink = href && (href.startsWith("/") || href.startsWith("#"));

  if (isInternalLink) {
    return (
      <Link href={href}>
        <a {...props} />
      </Link>
    );
  }
  return <a target="_blank" rel="noopener noreferrer" {...props} />;
};

const MDXComponents = {
  a: CustomLink
};

export default MDXComponents;
```

I would like to be able to make the `console.log(test)` return the value that is currently set into the [slug].jsx but I don't get if there is a way to pass to it the value itself, the `scope` option seems not to be the solution here.

**Comment by jescalan** [comment]
In this case you'd want to use [react context](https://reactjs.org/docs/context.html) - this would allow you to access the variable from your custom component without issue as long as you wrap `<MDXRemote>` in your provider.

Going to close this issue but please feel free to continue discussion!
