### ISSUE TITLE
V3 `esbuild` breaks ability to use in AWS Lambda

### ISSUE THREAD

**Issue by jlaramie** [hashicorp/next-mdx-remote#174]
I've done some testing and if I replace the references to `esbuild` with `esbuild-wasm` and then set `process.env.ESBUILD_BINARY_PATH = ''` then I am able to deploy and use this inside of a lambda.

I know its not as fast but I think next-mdx-remote should have some handling for running esbuild in a compatibility mode.

Maybe a new ENV variable `ESBUILD_COMPAT=1` or something similar could be used to trigger this behavior.

Then `esbuild-wasm` could be a peer dependency.

**Comment by jlaramie** [comment]
The solution above does not fully work but I'm keeping this open while I investigate how to get esbuild running in lambda easily

**Comment by jescalan** [comment]
Thank you, would be happy to support something like this if you can figure out a way to make it work!

**Comment by jlaramie** [comment]
Thought I'd post and update.

I successfully managed to get it to work but have not put together a proper fix for it yet.

The steps to get this working are:
1. Download and extract `esbuild` from `esbuild-linux-64` at the version matching the `next-mdx-remote` dependency version.
2. Ensure this file gets uploaded into the lambda
3. Move file to /tmp/esbuild
4. Update `process.env.ESBUILD_BINARY_PATH="/tmp/esbuild"` 
5. CHMOD /tmp/esbuild to make it executable `chmod 493 /tmp/esbuild`

I still need to figure out the best way to handle these steps as some of them will probably be more installation / configuration steps instead of actual code fixes.

**Comment by BRKalow** [comment]
esbuild has now been removed in v4, so I'm going to close this. Thanks!
