### ISSUE TITLE
How to use serialize function result for RSS

### ISSUE THREAD

**Issue by zenVentzi** [hashicorp/next-mdx-remote#175]
Normally, I pass the result from `const result = await serialize(..)` to the `MDXRemote` component and it does its magic. What I need now is to use that result's "spitted" html and put it into the `description` field for my RSS feed. The problem currently is that it spits javascript code that RSS doesn't know how to run. 

How can I achieve the result of having the end html for e.g. an RSS feed?

EDIT: The action is taking place outside of the component tree, in getServersideProps function. E.g.

```
export async function getServerSideProps(context: NextPageContext) {
  const res = context.res;
  if (!res) {
    return;
  }

  const posts = await getPosts({ limit: 20 });

  const rssXML = getRSSXML(posts);
  res.setHeader('Content-Type', 'text/xml');
  res.write(rssXML);
  res.end();
}
```

**Comment by BRKalow** [comment]
You should be fine to go ahead and render using `react-dom`, see [this comment](https://github.com/hashicorp/next-mdx-remote/issues/133#issuecomment-835857581) for an example.

```jsx
async function getStaticProps() {

  // ...

  const mdxSource = await serialize(mdx)
  const markup = renderToStaticMarkup(<MDXRemote {...mdxSource} />)

  // ...

  return {
    props: { markup }
  }
}
```

**Comment by zenVentzi** [comment]
That was easy, appreciate it! The components I pass don't render well but I think that's an issue with Chakra UI.
