### ISSUE TITLE
Breaking hyperlinks while mapping <img /> tag with MDXRemote

### ISSUE THREAD

**Issue by Beraliv** [hashicorp/next-mdx-remote#176]
Hey!

# The problem

I currently have an issue with `MDXRemote` + `serialize` with `img` inside `mdxComponents`

<details>
  <summary>When I comment `img` mapping in `mdxComponents`, my hyperlinks are correct</summary>
  
  
<img width="1058" alt="Screenshot 2021-07-31 at 16 32 34" src="https://user-images.githubusercontent.com/2991847/127743247-a12bf688-dc15-4b79-950a-540c57517480.png">

</details>

<details>
  <summary>When I add `img` mapping in `mdxComponents`, my hyperlinks are wrong, but only in the beginning of the blog post (usually, it's the second link 🤷‍♀️)</summary>
  
<img width="1054" alt="Screenshot 2021-07-31 at 16 33 35" src="https://user-images.githubusercontent.com/2991847/127743303-bd37d35f-2c49-40f2-9cfa-af13e2c4d5dc.png">

</details>

I want to understand, why?

# More details

## Technologies

Package.json – https://github.com/Beraliv/beraliv.dev/blob/main/packages/blog2/package.json#L12

Dependencies:

```json
    "firebase-admin": "9.9.0",
    "formik": "2.2.9",
    "gray-matter": "4.0.3",
    "next": "11.0.1",
    "next-mdx-remote": "3.0.4",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "remark": "13.0.0",
    "remark-html": "13.0.1",
    "swr": "0.5.6",
    "unist-util-visit": "2.0.3",
    "yup": "0.32.9"
```

## How I use them

I defined `mdxComponents` – https://github.com/Beraliv/beraliv.dev/blob/main/packages/blog2/src/components/mdx/index.ts:

```tsx
export const mdxComponents = {
  // if I comment it, the problem with hyperlinks is gone
  img: MdxImage,
};
```

and use it later as `PostBody` – https://github.com/Beraliv/beraliv.dev/blob/main/packages/blog2/src/components/atoms/PostBody.tsx#L10:

```tsx
export const PostBody: FC<PostBodyPropsType> = ({ content }) => (
  <MDXRemote {...content} components={mdxComponents} />
);
```

I get blog post content in `getPostStaticProps` this way – https://github.com/Beraliv/beraliv.dev/blob/main/packages/blog2/src/static/getPostStaticProps.ts#L10:

```ts
export const getPostStaticProps: GetStaticProps<
  PostPropsType,
  PostPropsParamsType
> = async ({ params }) => {
  if (!params?.slug) {
    throw new Error(`Cannot find slug for post ${location.href}`);
  }

  const { content, data } = getPostBySlug(params.slug);
  const uncheckedPost = { ...data, slug: params.slug };
  const checkedPost = validatePost(uncheckedPost);
  const { apiKey, formId } = validateEnvParameters();

  const mdxContent = await serialize(content, {
    scope: data as Record<string, unknown>,
    mdxOptions: {
      rehypePlugins: [imageMetadata],
    },
  });

  return {
    props: {
      apiKey,
      content: mdxContent,
      formId,
      post: checkedPost,
    },
  };
};
```

`imageMetadata` – https://github.com/Beraliv/beraliv.dev/blob/main/packages/blog2/src/plugins/imageMetadata.ts#L126 –  is the loader for Cloudinary images (it uses the path from here – https://github.com/Beraliv/beraliv.dev/blob/main/packages/blog2/src/functions/imageLoader/index.ts#L12)

## How to reproduce

Example of the blog post – Advanced Get – https://blog2.beraliv.dev/2021-03-26-typed-get

The MD file is available here – https://github.com/Beraliv/beraliv.dev/blob/main/packages/blog2/src/content/2021-03-26-typed-get.md

## Check it locally

1. You need to checkout to `test/debug-hyperlink-issues` branch (PR – https://github.com/Beraliv/beraliv.dev/pull/217)
2. You need to prepare it:

```bash
git clone https://github.com/Beraliv/beraliv.dev.git
cd beraliv.dev
git checkout test/debug-hyperlink-issues
yarn dev
```

3. Then open http://localhost:3000/2021-03-26-typed-get
4. And check `Summary ⚓️` link (it should be `/2021-03-26-typed-get/#summary` but instead you will see `https://github.com/type-challenges/type-challenges`)

## Additional question

Can you suggest me how to fix that without adding custom MdxLink components and use it in *.md files?

**Comment by jescalan** [comment]
Hey @Beraliv - I really appreciate the detailed post here. I've got a lot going on, and diving into a full project to try to debug is quite difficult. Is there any chance that you'd be able to create a minimal reproduction? This would make it much easier for me to carve out the time to help out with this one!

**Comment by Beraliv** [comment]
@jescalan hey! thank you for the response!

As I mentioned above, please have a look at `How to reproduce` and `Check it locally` headings.

In short, to check it in the existing blog page:

1. Open blog post – https://blog2.beraliv.dev/2021-03-26-typed-get
2. Check the link with the text `Summary ⚓️`
3. Compare it with what it has inside https://raw.githubusercontent.com/Beraliv/beraliv.dev/main/packages/blog2/src/content/2021-03-26-typed-get.md (look for `Summary&nbsp;⚓️` here)

In short, to reproduce it locally:

> 1. You need to checkout to `test/debug-hyperlink-issues` branch (PR – https://github.com/Beraliv/beraliv.dev/pull/217)
> 2. You need to prepare it:
> 
> ```bash
> git clone https://github.com/Beraliv/beraliv.dev.git
> cd beraliv.dev
> git checkout test/debug-hyperlink-issues
> yarn dev
> ```
> 
> 3. Then open http://localhost:3000/2021-03-26-typed-get
> 4. And check `Summary ⚓️` link (it should be `/2021-03-26-typed-get/#summary` but instead you will see `https://github.com/type-challenges/type-challenges`)

**Comment by jescalan** [comment]
Yes, a minimal reproduction means that you spin up a new empty nextjs project and include only the minimum amount of code required to reproduce the issue. The steps you mentioned above are pulling down a full project that includes lots of other code. When debugging, the first step is narrowing down what is causing the issue, I'm asking you to do some of the narrowing down for me in advance!

**Comment by Beraliv** [comment]
Okay, fair enough

Let me create an empty next project and I will add a minimum reproduction which happens for me

**Comment by Beraliv** [comment]
Sorry, didn't prepare the demo yet, will send it soon

**Comment by Beraliv** [comment]
Recently I came back from the vacation and I will prepare the demo soon

I'm really sorry for making demo for months

**Comment by Beraliv** [comment]
@jescalan thank you for your patience!

I finally got to creating the demo where I can reproduce the problem: https://github.com/Beraliv/nextjs-with-mdx#how-to-reproduce

Please let me know if I do something wrong

**Comment by Beraliv** [comment]
I checked `remark-unwrap-images` and it didn't really help me 😞

**Comment by jescalan** [comment]
Yeah I think you will need something slightly custom here as noted in [the previous comment](https://github.com/hashicorp/next-mdx-remote/issues/176#issuecomment-953259071), unfortunately.

At some point we are going to run into this same issue internally but its not acute for us yet, so it's difficult for me to prioritize. Are you open to taking a stab at this? I'd be happy to pair or provide guidance

**Comment by Beraliv** [comment]
> Yeah I think you will need something slightly custom here as noted in [the previous comment](https://github.com/hashicorp/next-mdx-remote/issues/176#issuecomment-953259071), unfortunately.
> 
> At some point we are going to run into this same issue internally but its not acute for us yet, so it's difficult for me to prioritize. Are you open to taking a stab at this? I'd be happy to pair or provide guidance

Yeah, as I really want to finish moving to the new version of the blog (with next.js)

At the moment I'm also lost a bit as the component (MdxLink) accept correct parameters but render it incorrectly

**Comment by imjuangarcia** [comment]
@Beraliv @jescalan OMG, I've been facing this issue for a while now and your suggestion to use `remark-unwrap-images` worked for me. Thanks a ton to both of you! I really appreciate Hashicorp's OSS work, keep it up! 👍

**Comment by jescalan** [comment]
@imjuangarcia ah im so glad! 👬

@Beraliv will shoot you an email and we can set up a time to work on this

**Comment by Beraliv** [comment]
> @imjuangarcia ah im so glad! 👬
> 
> @Beraliv will shoot you an email and we can set up a time to work on this

Got it!

**Comment by jescalan** [comment]
Closing the loop here, we got this resolved live by passing `unwrapImages` to the `mdxOptions.remarkPlugins` option in mdx remote. Whoo! 🎉

**Comment by Beraliv** [comment]
@jescalan thank you again for the help!
