### ISSUE TITLE
New Line / Line Break

### ISSUE THREAD

**Issue by tw1t611** [hashicorp/next-mdx-remote#177]
Hey,

what is the recommended way to create a new line?
I tried multiple `\n`, `\` at the end of line and `<br />`

Out of the box, none of them are working.

**Comment by tw1t611** [comment]
I figured out, that might be what I want, but couldn't get it working either.
https://github.com/remarkjs/remark-breaks

Tried
```js 
  const mdxSource = await serialize(source, {
    mdxOptions: {
      remarkPlugins: [breaks],
    },
  })
```

**Comment by jescalan** [comment]
Hey @tw1t611 - I think this is more of a question about mdx than this plugin, which is for using mdx within nextjs projects. You may want to ask about this in mdx support forums!

**Comment by ChristianMurphy** [comment]
`remark-breaks` works with the version of MDX used in `next-mdx-remote`
Here is a running example showing the `mdx` and `remark-breaks` versions are compatible https://codesandbox.io/s/distracted-wescoff-3rde8?file=/src/App.js

It may be related to `remark-breaks`v3  being ESM https://github.com/remarkjs/remark-breaks/releases/tag/3.0.0, until recently (https://github.com/vercel/next.js/pull/27069) Next has had issues loading ESM.
If there are ESM related warnings/errors shown in the console consider either:
* Updating to a Next version that includes the ESM fixes
* Or temporarily downgrading `remark-breaks` to version 2, until Next can be updated.

If no ESM related errors are thrown, this may be a bug in how `next-mdx-remote` handles plugins.

**Comment by tw1t611** [comment]
@ChristianMurphy Ty, I am not getting any Errors. The line break just isnÄt rendered.
@jescalan Could you look into this again please?

**Comment by jescalan** [comment]
@tw1t611 if you can make a minimal reproduction for me I can likely find some time to check it out next week!
