### ISSUE TITLE
transclusion not working 

### ISSUE THREAD

**Issue by Deep-Codes** [hashicorp/next-mdx-remote#181]
What I am trying to achieve here is 

importing `.mdx/.md` into other `.mdx/.md` also called as **Transclusion**.

This is mentioned in [MDX Docs.](https://mdxjs.com/getting-started#documents) helps in embedding repetitive content in multiple files.

How I was trying to approach it: 

1. Cloning `next-mdx-remote` nextjs example

```bash
git clone yarn create next-app --example with-mdx-remote with-mdx-remote-app
```

2. Creating a `.md` file and importing it in `.mdx` file

```js
// posts/example-post.md
import Test from '../utils/test.md';

<Test />
```

![Screenshot 2021-08-18 at 9 04 28 PM](https://user-images.githubusercontent.com/61158210/129927597-0245ec73-0af7-4feb-9e7a-d4481ac27eb0.png)

I do get it that this wasn't provided into the `<MdxProvider />`

but importing and adding as a component in the Provider also doesn't work because it isn't a react component.
which also needs modification in `next.config.js`.

How can I approach Transclusion with `next-mdx-remote` ?

**Comment by jescalan** [comment]
Imports [are not supported at all](https://github.com/hashicorp/next-mdx-remote#import--export) by this library, so the first step would be having `import` work, which we are tracking here: https://github.com/hashicorp/next-mdx-remote/issues/143

Going to close this one, but we can take another look if/when we support imports if it's not working automatically.
