### ISSUE TITLE
Package breaks ie11

### ISSUE THREAD

**Issue by tw1t611** [hashicorp/next-mdx-remote#184]
Using this package, I get the following error on IE11

![image](https://user-images.githubusercontent.com/13353525/131081020-f5bf5333-8229-434d-8fdc-5cdd536b0f6a.png)

Running an unoptimized build in ie11 shows the source of the error

![image](https://user-images.githubusercontent.com/13353525/131080976-475ec8d1-80ce-48dc-b128-da39a8836755.png)

**Comment by jescalan** [comment]
We're happy to accept contributions to adjust in IE! It's not a priority for our team since we do not support IE11

**Comment by brianespinosa** [comment]
Just in case anyone else happens to land here, this decision is backed up my Microsoft also having [already dropped support for IE11 in all of their web application apps and services](https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-support-end-dates).

[IE11 itself will also be fully retired as of June 15, 2022](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/).

🎉
