### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by EugeneGohh** [hashicorp/next-mdx-remote#187]
I'm trying to import `render-to-string` & `hydrate` but it doesn't work.

This is the error:

![error](https://user-images.githubusercontent.com/64187129/133035324-503c765a-b120-43a6-a46b-bf37bd741a5a.png)

**Comment by jescalan** [comment]
It looks like you may be using code from an older version, but have installed the latest major - see the readme for the docs for the current version and releases for upgrade notes.

Closing this issue as it's an individual support request but feel free to continue following up and I can still try to help!

**Comment by EugeneGohh** [comment]
> It looks like you may be using code from an older version, but have installed the latest major - see the readme for the docs for the current version and releases for upgrade notes.
> 
> Closing this issue as it's an individual support request but feel free to continue following up and I can still try to help!

Thanks for the reply, I fixed it.
