### ISSUE TITLE
High Severity Errors

### ISSUE THREAD

**Issue by EugeneGohh** [hashicorp/next-mdx-remote#189]
It looks like these 2 high severity errors are from your package. May I know how can I fix it?

![Untitled](https://user-images.githubusercontent.com/64187129/133365215-2a0a4d5f-87d8-4506-a0dc-fcaab01a460b.png)

**Comment by jescalan** [comment]
Addressed here: https://github.com/hashicorp/next-mdx-remote/issues/144
