### ISSUE TITLE
Is this possible passing function to mdx file ?

### ISSUE THREAD

**Issue by khanhna** [hashicorp/next-mdx-remote#193]
Hi,
Doing a page with ChakraUI, I've struggling for the whole day trying to passing function to `mdx` file.

On the `mdx file`, I was trying to achieve something like

```
<Image
    src="xxx"
    borderColor={useColorModeValue('gray.300', 'gray.700')}
    borderWidth="1px"
    shadow="md"
    mb={8}
  />
```

The `Image` component here is the [https://chakra-ui.com/docs/media-and-icons/image](Image) chakraUI component.

And here is how I passed the `useColorModeValue` function down(in tsx page):

```
import { useColorModeValue } from '@chakra-ui/react';

///...
const pageScecificComponent = {
  ...mdxComponents,
  useColorModeValue // I'm struggling here
};

export const getStaticProps: GetStaticProps = async () => {
  const postFilePath = path.join(POSTS_PATH, 'About.mdx');
  const source = fs.readFileSync(postFilePath);

  const { content, data } = matter(source);

  const mdxSource = await serialize(content, {
    // Optionally pass remark/rehype plugins
    mdxOptions: {
      remarkPlugins: [],
      rehypePlugins: [],
    },
    scope: data,
  });

  return {
    props: {
      source: mdxSource,
      frontMatter: data,
    },
  };
};

const Home: AppNextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({ source, frontMatter }) => {
  return <MDXRemote {...source} components={pageScecificComponent} />;
};
```

Everything was working fine if the `useColorModeValue` function on `mdx` file is not present.
So, is there anyway I can do this, googling things through various example but everything I found was it implemented using `next-mdx-enhanced` (which I want to avoid).

I would appreciate even just some glue.

Thank you guys.

**Comment by payapula** [comment]
@khanhna  As far as I know, you cannot pass functions into `components` prop of `MDXRemote`. 

What you are trying to achieve could be done with this method. Kind of prop forwarning.

For this example I used CustomComponent takes props from MDX Page and pass it to the component in `useColorModeValue` hook, but the idea would be same

```jsx
const CustomComponent = (props) => (
    <Box
        backgroundColor={useColorModeValue(props.light, props.dark)}
        {...props}
    />
);

const MDXComponents = {
     CustomComponent,
};
```
And on MDX Page,

```mdx
Some awesome MDX Content here!!

<CustomComponent light="gray.300" dark="gray.700" >
 I would change colors :) 
</CustomComponent>

Thanks for reading my blog!
```


On the page you are using MDXRemote,

```jsx
import {MDXComponents} from './index/components';

 <MDXRemote {...content} components={...MDXComponents} />
```

So, for your use case with Image component, write an intermediate component that accepts props from MDX file and pass it down to the Chakra Image component.

Let me know if this helps.

**Comment by khanhna** [comment]
Thanks for a quick reply @payapula,

I was though that was possible, but seems like I would take this approach as long as I could find anything that more helpful.

And ofcourse this should work right away.
Have a good day 🎉

**Comment by khanhna** [comment]
thanks for the theory @jescalan, and this is my experiment following the hint so far:

```ts
// Using NextJs
import matter from 'gray-matter';
import { FiActivity } from 'react-icons/fi';

// getStaticProps:
const { content, data } = matter(source);
const mdxSource = await serialize(content, {
  // Optionally pass remark/rehype plugins
  mdxOptions: {
    remarkPlugins: [remarkSlug, remarkFootnotes, remarkCodeTitles, remarkEmoji],
    rehypePlugins: [mdxPrism],
  },
  scope: { ...data, FiActivity }, //another tried scope, just return a number: { ...data, InvokeSample: () => 10 },
});

// mdx file, Note component is my custom component that accept icon as a JSX.Element:
<Note status="success" icon={FiActivity}>
  //...
</Note>

// mdx file on another tried:
<Note status="success" icon={() => <></>}>
  {InvokeSample()}
</Note>
```
Both of them failed to compile... I guess @payapula still right... currently it's not yet possible to pass a function down like this.

**Comment by jescalan** [comment]
I guess this does make sense. I had mentioned in my comment only to pass it to `MDXRemote`, knowing that it wouldn't pass through `getStaticProps` since functions are not serializable, but I guess if you skip it from `getStaticProps` probably you'd get an error when it tried to server render calling an undefined function. Worth a shot!

**Comment by jescalan** [comment]
I **think** you merged the `scope` property directly into the source object here on this line, rather than under the `scope` key:

```
const processedSource = { ...addingPropScope, ...theRest };
```

it would have to be instead:

```
const processedSource = { scope: addingPropScope, ...theRest };
```
