### ISSUE TITLE
Serialize markdown inside custom components

### ISSUE THREAD

**Issue by ghoshnirmalya** [hashicorp/next-mdx-remote#196]
The `children` props inside custom components aren't serialized. Let's say that you have a `Callout` component like the following:

```tsx
import { Box, HStack } from "@chakra-ui/react";
import React, { FC } from "react";

const Callout: FC = ({ children }) => {
  return (
    <Box p={4} rounded="sm" bg="gray.800" color="white">
      <HStack spacing={2}>
        <Box fontSize={48}>💡</Box>
        <Box>{children}</Box>
      </HStack>
    </Box>
  );
};

export default Callout;
```

We call it like this:

```jsx
<Callout>
  Markdown oh **yeah**!! [Cool,
  right?](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
</Callout>
```

You will get something like this:
<img width="674" alt="Screenshot 2021-10-13 at 1 52 57 AM" src="https://user-images.githubusercontent.com/6391763/137023892-1c15f5e8-c16c-488b-8834-584717f7e731.png">

This issue extends [this one](https://github.com/hashicorp/next-mdx-remote/issues/190).

**Comment by rome2o** [comment]
Hi @jescalan.

Mdx 2 was out earlier this year, has there been any news on this? or any examples that you could share?

Thanks
Ali

**Comment by jescalan** [comment]
Are you having trouble getting this to work correctly?
