### ISSUE TITLE
How to add className to lazy div wrapper?

### ISSUE THREAD

**Issue by ekafyi** [hashicorp/next-mdx-remote#209]
Hi, this is more of a question than an "issue".

Is it possible to add a className to the `<div>` wrapper of the lazy-hydrated MDXRemote?

My use case is to avoid excessive nested divs; I'd otherwise wrap it with another div to assign classname for basic styles that don't warrant custom components (eg. simply styling `.markdown-content a`, `.markdown-content ul` etc).

Thanks!

**Comment by jescalan** [comment]
This is not currently a way to do this, the code that renders the div [can be found here](https://github.com/hashicorp/next-mdx-remote/blob/main/src/index.tsx#L104). We'd definitely consider a PR to add this feature though if it's important for you!

**Comment by BRKalow** [comment]
Closing this, feel free to re-open or create a follow-up issue if you feel this is still necessary.

Thanks!
