### ISSUE TITLE
How does one preview the MDX?

### ISSUE THREAD

**Issue by SanderCokart** [hashicorp/next-mdx-remote#212]
So I wish to make an in browser editor for MDX before it hits the API database. But how would one be able to preview the MDX before it is send out? I cannot use serialize outside of getStaticProps/getServersideProps.
The hydrate function is gone now in 3.0.
What is the expected workflow?

I have a Laravel API and wish to store the blog posts there and render them on my NextJS App.
Using an MDX editor and then copy pasting it in the textarea is not a very elegant solution.

**Comment by jescalan** [comment]
This is outside the scope of this project. This project is not something that can/should be used to build a client-side editor. You'd have to look into other tools and projects to pull this off. I am pretty sure that mdx itself ships a package that can be used for client side compilation, on their site [there is a playground](https://mdxjs.com/playground/), and the [website is open source](https://github.com/mdx-js/mdx/tree/main/website) so I might start by looking into this!
