### ISSUE TITLE
Navigation to hash not working

### ISSUE THREAD

**Issue by wolnynick** [hashicorp/next-mdx-remote#214]
After some tests, I noticed that hash navigation are not working after parsing `.md | .mdx` files into html using `next-mdx-remote`. Then I thought that when I change default `<a/>` element to `<Link/>` (using components prop) then it will start working, but unfortunately it didn't help. Markdown file is correct, so it's not problem with it.

With `<a><a>` there is in DOM href only to # (for example href="#title"), but with `<Link></Link>` there is full path (for example href="/content/markdownFile#title"). Both are working in same way (url is changed correctly, but nothing happen).

I'm using:
```json
    "next": "^12.0.4",
    "next-mdx-remote": "^3.0.8",
```
I found this [issue](https://github.com/hashicorp/next-mdx-remote/issues/65), but it didn't help me.  If I need to provide any additional data to solve this problem, please tell me. 

Edit:
I recreated this issue in [codeSandbox](https://codesandbox.io/s/dreamy-ully-zkzqq?file=/pages/index.js)

**Comment by jescalan** [comment]
From looking at the codesandbox, it looks like hash navigation is working fine but none of your headlines actually have ids on them, so they are not navigating anywhere. You may need to add a remark plugin that adds permalink markup to headline output!

Closing this issue, but please feel free to continue chatting here if this doesn't solve the problem.

**Comment by voyyy** [comment]
Thanks, your advice helps me 😁

Solution:
```typescript
import rehypeSlug from "rehype-slug";
....
    content = await serialize(matterResult.content, {
      mdxOptions: {
        rehypePlugins: [rehypeSlug],
      },
    });
...
```

**Comment by wolnynick** [comment]
Thanks, your advice helps me 😁

Solution:
```typescript
import rehypeSlug from "rehype-slug";
....
    content = await serialize(matterResult.content, {
      mdxOptions: {
        rehypePlugins: [rehypeSlug],
      },
    });
...
```
