### ISSUE TITLE
The package css could not be applied

### ISSUE THREAD

**Issue by thangtmc73** [hashicorp/next-mdx-remote#215]
Hi, I am using the `next-mdx-remote` to load and display my `.mdx` files. It parses from markdown into html very well. But their styles with CSS don't have any change with my pages.

<img width="1348" alt="Screen Shot 2021-12-06 at 02 01 56" src="https://user-images.githubusercontent.com/9251308/144759893-231d4942-5b75-4091-8e9f-c21b3fdd2219.png">

You could see the highlight text "Phân tích" in the above image is `h1` and it is not **bold**. Does the CSS need to be implemented myself? In the tutorial I have followed, they don't implement any CSS related to the markdown with your package..

This is my repo with the working branch: https://github.com/thangtmc73/homepage/tree/features/add-post-UI.
You could try with the URL:  http://localhost:3000/posts/2021-07-12-filter-boolean-trong-javascript to test my markdown page.
My packages in the package.json file:
```
  "dependencies": {
    "@chakra-ui/react": "^1.7.2",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "dayjs": "^1.10.7",
    "framer-motion": "^5",
    "gray-matter": "^4.0.3",
    "next": "12.0.7",
    "next-mdx-remote": "^3.0.8",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "sass": "^1.44.0"
  },
```
Thanks for your help.

.

**Comment by jescalan** [comment]
Yes you need to implement css yourself, this package does not provide any styling at all, it simple converts mdx to html. It seems like perhaps the tutorial you followed may not have mentioned this or included the styling they implemented.
