### ISSUE TITLE
DeprecationWarning: No "main" or "exports" field defined

### ISSUE THREAD

**Issue by philsp** [hashicorp/next-mdx-remote#218]
next-mdx-remote 4.0.0-rc.1
node v16.10.0

```
[DEP0151] DeprecationWarning: No "main" or "exports" field defined in the package.json for ***\node_modules\next-mdx-remote\ resolving the main entry point "index.js", imported from ***.js.
Default "index" lookups for the main are deprecated for ES modules.
```

**Comment by jescalan** [comment]
This is correct, there is no main import from this package -- the readme details how and why you can import individual chunks for specific purposes. Adding a main export would be misleading, as one does not genuinely exist.

**Comment by philsp** [comment]
Thank you for your reply!

Do I understand correctly that this is the preferred way to import this package with node 16?

`import { MDXRemote } from 'next-mdx-remote/index'`

**Comment by jescalan** [comment]
No, that is not correct. See the readme for the correct way to important the package for all stable versions of node!

**Comment by philsp** [comment]
Hmm, building the following (compacted) example from the readme on Node 16.13.2 LTS (Windows (x64)) also shows the deprecation warning. Is there any other way to import this package that I'm missing?

pages/index.js
```
import { serialize } from 'next-mdx-remote/serialize'
import { MDXRemote } from 'next-mdx-remote'

const Test = () => <em>Test</em>;

export default function TestPage({ source }) {
  return <MDXRemote {...source} components={{ Test }} />
}

export async function getStaticProps() {
  return { props: { source: await serialize('Some **mdx** text, with a component <Test />') } }
}
```

package.json
```
{
  "scripts": {
    "build": "next build"
  },
  "dependencies": {
    "next-mdx-remote": "4.0.0-rc.1",
    "next": "12.0.7",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  }
}
```

**Comment by jescalan** [comment]
You can ignore the deprecation warning for now. Put up a PR that should get rid of it https://github.com/hashicorp/next-mdx-remote/pull/223
