### ISSUE TITLE
Issue with remark-directive

### ISSUE THREAD

**Issue by ademenet** [hashicorp/next-mdx-remote#219]
Hello,

I have some trouble with [`remark-directive`](https://github.com/remarkjs/remark-directive). It does not work at all with `next-mdx-remote`.

I have created a toy example [here](https://github.com/ademenet/directive-mdx-remote) so you can reproduce the issue. Everything happens [in this file](https://github.com/ademenet/directive-mdx-remote/blob/main/pages/index.js).

I am using:
- Next: 12.0.7,
- next-mdx-remote: 3.0.8
- remark-directive: 2.0.1

Am I missing something? I read there have been some big changes recently in remark sphere (the use of ESM among others), but I was able to use other libraries without any trouble.

Thank you very much anyway! 😃

**Comment by BRKalow** [comment]
It's possible this is because `remark-directive` depends on a newer version of remark than what mdx v1 uses. You might try `next-mdx-remote@next`, which uses mdx v2 under the hood.

**Comment by mogita** [comment]
Can confirm `remark-directive` still doesn't work on version 4.0.3.

Next.js: 12.1.6
next-mdx-remote: 4.0.3
remark-directive: 2.0.1

Just a simple usage from [`remark-directive`'s readme](https://github.com/remarkjs/remark-directive#use). The generated node types which should be a "directive" was simply a paragraph.
