### ISSUE TITLE
1.0.0 remark plugins stopped working

### ISSUE THREAD

**Issue by ahmadawais** [hashicorp/next-mdx-remote#22]
On 0.6.0 I had this

```js
const mdx = await renderToString(
    content,
    components,
    {
      remarkPlugins: [
        remarkSlug,
        [
          remarkAutoLink,
          {
            content: {
              type: 'element',
              tagName: 'span',
              children: [{ type: 'text', value: '#' }],
              properties: { className: ['heading-link'] },
            },
          },
        ],
        remarkCodeTitles,
        remarkUnwrapImages,
      ],
    },
    data,
  );

```

And it worked perfectly to produce the following

![image](https://user-images.githubusercontent.com/960133/90681206-7978bf80-e27c-11ea-9a1d-b90eb4bbafb7.png)

And just by upgrading to 1.0.0 none of the remark plugins work with the same code. I get this in the source

![image](https://user-images.githubusercontent.com/960133/90681294-9c0ad880-e27c-11ea-9629-7f1eadbe5552.png)

See how no auto-link headings and ids exist. Same is the case with code, not being highlighted.

**Comment by ahmadawais** [comment]
Oops. Just read the breaking changes. https://github.com/hashicorp/next-mdx-remote/releases/tag/1.0.0

Fixed 💯

**Comment by jescalan** [comment]
Heyy glad the release notes worked! Thanks for the update, and hope you're really enjoying the plugin!

**Comment by ahmadawais** [comment]
Yeah thanks for that. So far so good. Been having trouble with trying to refactor all the code into separate files but Next.js chokes on it if I do that :P

**Comment by jescalan** [comment]
@ahmadawais feel free to reach out on twitter and I can pair this with you if you'd like
