### ISSUE TITLE
serialize() doesn't load remark/rehype plugins

### ISSUE THREAD

**Issue by joulev** [hashicorp/next-mdx-remote#221]
I'm trying to use KaTeX, but so far I have failed:

```js
const source = await serialize("Hello *world* and $1+1=2$ math mode", {
  scope: {},
  mdxOptions: {
    remarkPlugins: [],
    rehypePlugins: []
  },
});
```

and

```js
const source = await serialize("Hello *world* and $1+1=2$ math mode", {
  scope: {},
  mdxOptions: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeKatex]
  },
});
```

give exactly the same `source`.

<details>
<summary><code>console.log(source)</code> output</summary>

```js
{
  compiledSource: 'var D=Object.defineProperty,M=Object.defineProperties;var X=Object.getOwnPropertyDescriptors;var p=Object.getOwnPropertySymbols;var m=Object.prototype.hasOwnProperty,r=Object.prototype.propertyIsEnumerable;var u=(o,t,e)=>t in o?D(o,t,{enumerable:!0,configurable:!0,writable:!0,value:e}):o[t]=e,a=(o,t)=>{for(var e in t||(t={}))m.call(t,e)&&u(o,e,t[e]);if(p)for(var e of p(t))r.call(t,e)&&u(o,e,t[e]);return o},s=(o,t)=>M(o,X(t));var y=(o,t)=>{var e={};for(var n in o)m.call(o,n)&&t.indexOf(n)<0&&(e[n]=o[n]);if(o!=null&&p)for(var n of p(o))t.indexOf(n)<0&&r.call(o,n)&&(e[n]=o[n]);return e};const layoutProps={},MDXLayout="wrapper";function MDXContent(e){var n=e,{components:o}=n,t=y(n,["components"]);return mdx(MDXLayout,s(a(a({},layoutProps),t),{components:o,mdxType:"MDXLayout"}),mdx("p",null,"Hello ",mdx("em",{parentName:"p"},"world")," and $1+1=2$ math mode"))}MDXContent.isMDXComponent=!0;\n',
  scope: {}
}
```
</details>

Of course the rendered output doesn't have any math at all. Everything else works as expected ("world" is in italic for example). So the two plugins aren't loaded.

I must be missing some very obvious configuration steps here... but what's wrong?

Version numbers in case they are relevant:

    "next": "12.0.7",
    "next-mdx-remote": "^3.0.8",
    "rehype-katex": "^6.0.2",
    "remark-math": "^5.1.1",

**Comment by bryanhpchiang** [comment]
Same issue, do:
```
import markdown from "remark-parse";
```

and change
```
  remarkPlugins: [markdown, remarkMath],
```

However, this breaks custom components and results in SVG rendering issues (https://github.com/mdx-js/mdx/issues/1148). Will probably switch to mdx-bundler.

**Comment by joulev** [comment]
Indeed, I need to have custom components too (otherwise I wouldn't even use MDX in the first place), so doing this is not very applicable to me.

**Comment by bryanhpchiang** [comment]
I got KaTeX to work by downgrading remark-math to 3.0.0.

**Comment by subwaymatch** [comment]
I also ran into the same issue and took me a while to find out that this was a version issue.

Downgrading `remark-math` to 3.0.0 or 3.0.1 seems to work. This is also briefly mentioned in https://github.com/hashicorp/next-mdx-remote/issues/148.

There is a Codesandbox example created by @timlrx at https://codesandbox.io/s/katex-forked-jegb7?file=/pages/index.js that renders KaTex correctly. The versions used in the example are:

- `remark`: 12.0.1
- `remark-math`: 3.0.0
- `rehype-katex`: 5.0.0
- `rehype-parse`: 9.0.0

I would love to find out if anyone has made KaTeX to work with the latest versions of plugin packages. 🧐

**Comment by joulev** [comment]
Indeed, look like this issue is an exact duplicate of #148, but since it was closed with only a workaround (I would prefer to use the latest version of `remark-math`), I think I will keep this one open.

**Comment by marcospassos** [comment]
Same issue here. As remark-math is at version 5, we need a solution for it.

**Comment by BRKalow** [comment]
This is likely due to the fact that we're relying on an older version of remark along with mdx v1, as others have found.

If you would like, give `next-mdx-remote@next` a try, which uses mdx v2 under the hood and should be compatible with these packages. Otherwise, the alternative is to adjust the versions as @subwaymatch [has outlined](https://github.com/hashicorp/next-mdx-remote/issues/221#issuecomment-1008001630).

**Comment by imteekay** [comment]
I tried following the versioning suggested by @subwaymatch but it doesn't seem to work.

I:

- Added the dependencies with right versions
- Configured the plugins
- Added the katex CSS to the head

These are the versions I'm using

- `rehype-katex`: 5.0.0
- `remark-math`: 3.0.0
- `next-mdx-remote`: 4.2.0

Here's the PR with the changes: https://github.com/imteekay/iamtk.co/pull/251
Any ideas on what I could be doing wrong?
