### ISSUE TITLE
Migrating to v3 - hydrate to serialize

### ISSUE THREAD

**Issue by bubuq3** [hashicorp/next-mdx-remote#222]
Hello, would you please tell me how to convert this old version to newer one?
I followed this release note and it hasn't worked: https://github.com/hashicorp/next-mdx-remote/releases/tag/3.0.0
OLD:
```js
// ...
export const getStaticProps = async ({ params }) => {
  const portfolioItem = await getPortfolioItem(params.slug);
  return {
    props: {
      portfolioItem: portfolioItem.portfolios[0],
      content: await renderToString(he.decode(portfolioItem.portfolios[0].content)),
    },
  };
};
```
output: `{hydrate(content)}`

Tried like this and it hasn't worked:
NEW:
```js
// ...
import { serialize } from "next-mdx-remote/serialize";
import { MDXRemote } from "next-mdx-remote";

export const getStaticProps = async ({ params }) => {
  const portfolioItem = await getPortfolioItem(params.slug);
  return {
    props: {
      portfolioItem: portfolioItem.portfolios[0],
      content: await serialize(portfolioItem.portfolios[0].content),
    },
  };
};`
//output
export default function Home({ portfolioItem, content}) {
  return (
    <>
          <div className="prose prose-xl max-w-none pt-4 text-justify dark:text-gray-100 pb-10 cms-content">
            <MDXRemote {...content} />
          </div>
    </>
  );
}
```

error:
./node_modules/@esbuild-plugins/node-resolve/esm/index.js:37:0
Module not found: Can't resolve 'builtin-modules'
null

**Comment by BRKalow** [comment]
Can you share a minimal reproduction? Happy to take a look if so.

**Comment by bubuq3** [comment]
https://github.com/bubuq3/clone-portfolio2021/blob/7899d9c07770bb462abfba88cfdd3ca05e2ed7a9/pages/portfolio/%5Bslug%5D.js#L20-L36

Hope I haven't leaked anything 🤣
