### ISSUE TITLE
Property 'children' is missing in type 'Node<Data>' but required in type 'Root'

### ISSUE THREAD

**Issue by edwinvelez** [hashicorp/next-mdx-remote#226]
Next.js offers a [with-mdx-remote](https://github.com/vercel/next.js/blob/canary/examples/with-mdx-remote/pages/posts/%5Bslug%5D.js) example JavaScript project which works. However, when adding a plugin, a problem is identified. Although the "problem" exists, I can successfully `npm run dev` and `npm run build` as expected.

![image](https://user-images.githubusercontent.com/2299753/150163089-a1645696-4ee3-4597-a63e-404afb6ac802.png)

If the project  is converted to TypeScript, `npm run dev` works as expected but `npm run build` fails.

![image](https://user-images.githubusercontent.com/2299753/150167208-78cb8ded-80cb-4cf4-b1d5-9211e02321dc.png)

Below is the output to `npm run build`.

```
➜ npm run build

> build
> next build

Failed to compile.

./src/pages/posts/[slug].tsx:30:30
Type error: Type '(options?: void | Options | undefined) => void | Transformer<Root, Root>' is not assignable to type 'Pluggable<[(Settings | undefined)?], Settings>'.
  Type '(options?: void | Options | undefined) => void | Transformer<Root, Root>' is not assignable to type 'Plugin<[(Settings | undefined)?], Settings>'.
    Type 'void | Transformer<Root, Root>' is not assignable to type 'void | Transformer'.
      Type 'Transformer<Root, Root>' is not assignable to type 'void | Transformer'.
        Type 'Transformer<Root, Root>' is not assignable to type 'Transformer'.
          Types of parameters 'node' and 'node' are incompatible.
            Property 'children' is missing in type 'Node<Data>' but required in type 'Root'.

  28 |     const mdxSource                      = await serialize( content, {
  29 |         mdxOptions: {
> 30 |             rehypePlugins: [ rehypeHighlight ],
     |                              ^
  31 |         },
  32 |         scope     : frontMatter,
  33 |     } );
info  - Checking validity of types .% 
```

These are the relevant imports.
```typescript jsx
import { MDXRemote }                      from 'next-mdx-remote';
import { serialize }                      from 'next-mdx-remote/serialize';
import rehypeHighlight                    from 'rehype-highlight';
```

To workaround this problem I add `// @ts-ignore`. Only then will `npm run build` execute successfully.
```typescript jsx
const mdxSource = await serialize( content, {
    mdxOptions: {
        // @ts-ignore
        rehypePlugins: [ rehypeHighlight ],
    },
    scope     : frontMatter,
} );
```

**Comment by BRKalow** [comment]
This might be the result of type mismatches between remark versions. If you want, you could try using `next-mdx-remote@next`, which uses mdx v2 under the hood, to see if that fixes your issue.

**Comment by edwinvelez** [comment]
Thanks @BRKalow.

`next-mdx-remote@next` seems to have corrected the problem but also introduced another. Hopefully when the `@next` is ready for final release all issues will have been resolved. For now the seems to be on the radar and  `// @ts-ignore` a temporary solution.

```shell
(node:4450) [DEP0151] DeprecationWarning: No "main" or "exports" field defined in the package.json
Default "index" lookups for the main are deprecated for ES modules.
```
