### ISSUE TITLE
Use next-mdx-remote with rehype-sanitize makes `inline code block` not working

### ISSUE THREAD

**Issue by resqiar** [hashicorp/next-mdx-remote#229]
Hi!

I tried to migrate from `react-markdown` to `next-mdx-remote` lately, but I encountered a problem where the inline code block does not work when I use `rehype-sanitize` plugin. 

This should be the expected behaviour in the HTML: 

```html
   <p>
     <code>this inline should work nice and steady</code>
   </p>
```

but instead, it completely removes the "code" inside of the "p" tag:

```html
   <p>
    this inline should work nice and steady
   </p>
```

Here is what I use in the `package.json`

```json
"dependencies": {
    "next": "11.1.2",
    "next-mdx-remote": "3.0.8",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-markdown": "8.0.0",
    "rehype-sanitize": "5.0.1",
    "remark-gfm": "3.0.1",
  },
```

and here is my simple `index.tsx`

```ts
import { serialize } from "next-mdx-remote/serialize";
import { MDXRemote } from "next-mdx-remote";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeSanitize from "rehype-sanitize";
import "github-markdown-css";

export default function IndexPage({ source }) {
  return (
      <div className="markdown-body">
        <MDXRemote {...source} />
      </div>
  );
}

export async function getServerSideProps() {
  // example md
  const content = "`this inline should work nice and steady`\n";

  const mdxSource = await serialize(content, {
    mdxOptions: {
      remarkPlugins: [remarkGfm],
      // remove below plugins, and inline code block will works
      rehypePlugins: [rehypeSanitize]
    },
    target: ["esnext"]
  });

  return {
    props: {
      source: mdxSource
    }
  };
}
```

Am I missing any configurations? I also tried other libraries with the same config, but the problem didn't appear. 

I created a simple sandbox to replicate and reproduce the problem. If you don't mind, you can check this [CodeSandbox](https://codesandbox.io/s/next-mdx-remote-sanitization-issue-qg7pp?file=/pages/index.js) 

Thank you so much!

**Comment by alexcarpenter** [comment]
@resqiar Just checked out your CodeSanbox repro and looks to be working. Are you still experiencing the issue?

<img width="1091" alt="CleanShot 2022-03-08 at 08 31 44@2x" src="https://user-images.githubusercontent.com/825855/157247960-1ef75d41-626c-434b-a395-258ed8127dc9.png">

**Comment by nos-nart** [comment]
@alexcarpenter How can I replacing `code` tag? Because It's wrapped by `p` tag so when I try
```js
const COMPONENTS = {
  code: (props) => <code {...props} className="my-default-class" />
}
```
So the `code` tag does not apply styling from class? Do I need to use any other package to make the `code` tag not to be wrapped by `p` tag? or how can I apply my class for `code` tag?

**Comment by alexcarpenter** [comment]
@nos-nart your example would include the class `my-default-class`. New lines in MDX are wrapped in `<p>` tags.

Example shown here:

![CleanShot 2022-03-11 at 08 51 32@2x](https://user-images.githubusercontent.com/825855/157880807-1621573d-4952-4845-8118-8b6446294bb5.png)

**Comment by nos-nart** [comment]
@alexcarpenter On mine `code` tag doesn't includes class I apply for
```js
const COMPONENTS = {
   // these work
   ul: (props) => <List type="unordered" {...props} />,
   h2: (props) => (
     <h2 {...props} className="text-3xl font-bold leading-12" />
   ),
  // Does not work
  code: (props) => <code {...props} className="bg-red-500" />,
}
```
![image](https://user-images.githubusercontent.com/37862200/157893442-6f4de67d-4117-4500-ac2e-e112dd230713.png)
Do you know how to make it work? Thank you for helping me

**Comment by resqiar** [comment]
@alexcarpenter Sorry for the late reply, I don't understand why the reproduction code is working for you but not me, here is the image: 

![next-mdx-remote-rehype-sanitize-issue](https://i.imgur.com/OrnTyxC.png)

However, **upgrading `next-mdx-remote` from `v3` to `v4`** appears to fix the problem, Here is the same repro but upgraded to v4, it should work just fine. https://codesandbox.io/s/next-mdx-remote-sanitization-issue-fixed-after-v4-xqmefh 


Note:
For everyone who struggles because inline code does not behave normally after upgrading to v4, check this closed issue #244.

**Comment by resqiar** [comment]
@nos-nart  Where did you put that component?
I tried with the same setup as yours and it's working

```jsx
<MDXRemote
  {...yourmdxsource}
  // custom components
  components={{
    code: (props) => <code {...props} className="your-custom-class" />
  }}
/>
```
![](https://i.imgur.com/5EcHzp7.png)

**Comment by nos-nart** [comment]
@resqiar I updated `next-mdx-remote` to v.4 and It works
