### ISSUE TITLE
Breaks with concurrent mode

### ISSUE THREAD

**Issue by jaredpalmer** [hashicorp/next-mdx-remote#23]
Getting a conditional / different order of hooks warning with react@experimental

**Comment by jescalan** [comment]
Ah interesting, I hadn't tested with this. Any idea what might be causing it?

**Comment by ljosberinn** [comment]
https://github.com/hashicorp/next-mdx-remote/blob/master/hydrate.js#L21 this line very most likely

**Comment by jescalan** [comment]
This should be resolved as of v2 - marking as closed but by all means feel free to re-open if that's not the case!
