### ISSUE TITLE
Upgrade to mdx 2.x

### ISSUE THREAD

**Issue by joepio** [hashicorp/next-mdx-remote#230]
First off: thanks for maintaining this repo, it's awesome.

Version 2.0 of `mdx` ~~has just been released~~ has a [pre-release](https://mdxjs.com/blog/v2/), and has a couple of benefits:

- Improved syntax makes it easier to use markdown in JSX
- JavaScript expressions turn {2 * Math.PI} into 6.283185307179586
- New esbuild, Rollup, and Node.js integrations
- Any JSX runtime: React, Preact, Vue, Emotion, you name it, they’re all supported
- Improved AST exposes more info in greater detail
- Compiles at least 25% faster
- Generated code runs twice as fast (100% faster)
- Bundle size of @mdx-js/mdx is more than three times as small (250% smaller)

[Here's the migration guide](https://mdxjs.com/migrating/v2/). 

Are there plans for `next-mdx-remote` to upgrade to this new version?

Edit: just noticed there's already a PR, nice! Might be good to keep this issue open as a reference, or maybe just close it. #211

**Comment by jescalan** [comment]
@joepio - it has not yet been released, you can see this in the [release log](https://github.com/mdx-js/mdx/releases), and in the large red warning box in the site that you linked that says it hasn't been released.

That being said, we have some good news! As you have discovered, we have a PR open to support it as soon as it is released, and if you are on a prerelease and want to test it, you can do so using `npm i next-mdx-remote@mdx2`. So nothing should be holding you back 😁

**Comment by joepio** [comment]
Thanks @jescalan!

**Comment by jescalan** [comment]
Closing this issue - anyone interested can refer to [the PR where the upgrade is implemented for further info](https://github.com/hashicorp/next-mdx-remote/pull/211), and anyone eager to try it out immediately before that PR is released can install the v2-compatible version with `npm i next-mdx-remote@mdx2` today 😁
