### ISSUE TITLE
markdown inside jsx tag

### ISSUE THREAD

**Issue by dmitryshelomanov** [hashicorp/next-mdx-remote#232]
I cant use somting like this

```mdx
Hello, world!
Below is an example of markdown in JSX.

<div style={{padding: '1rem', backgroundColor: 'violet'}}>
  ### dlkfjdlkf
  <div style={{padding: '1rem', backgroundColor: 'violet'}}>
 dfkdfjdjfdjfjdlfljk

### dlkfjdjf

- dlkfjdjf
- df
</div>
</div>
```

with error SyntaxError: unknown: Expected corresponding JSX closing tag for

How to fix it ?

**Comment by jescalan** [comment]
This is an mdx issue, mixing jsx and markdown requires special handling in mdx v1. It has improved in v2 which we should have a release for soon.

**Comment by dmitryshelomanov** [comment]
@jescalan 
![image](https://user-images.githubusercontent.com/19505559/154846970-fd49abfc-d490-43ed-8633-d637c26c87d4.png)
with v2 cant compile (any symbol)
how to use with cjs modules ?

**Comment by BRKalow** [comment]
@dmitryshelomanov can you share a minimal reproduction? Happy to take a look if so!

**Comment by dmitryshelomanov** [comment]
[test.zip](https://github.com/hashicorp/next-mdx-remote/files/8104988/test.zip)
@BRKalow demo
razzle

npm install then npm run start

(Cant do it online)

**Comment by dmitryshelomanov** [comment]
import remarkAlign from 'remark-align';
import remarkAttr from 'remark-attr';
import remarkComments from 'remark-comments';

not working with mdx2

**Comment by dmitryshelomanov** [comment]
![image](https://user-images.githubusercontent.com/19505559/154964219-f9dfcec1-5a1c-42a9-997a-106be45a419c.png)
it works
but without remarkComments remarkAttr remarkAlign
has any libs? With similar behavior ?

**Comment by dmitryshelomanov** [comment]
How to write own plugins ?There is any docs ?
