### ISSUE TITLE
Use Data Scope w/o Explicitly Specifying It In Source

### ISSUE THREAD

**Issue by max-pod** [hashicorp/next-mdx-remote#240]
Hi,

This is a niche use-case, and what I'm looking to do is to pass props into components that don't have to specify those props in the mdx source. Trying to do this so that non-technical people can just use MDX components without having to think about the data model.

Ex: MDX `This is a <Test/> component`
Scope: `{test: test}`
And have Test actually function like <Test test={test} />

Right now I have my components curried in wrappers, that provide that data, but I'm looking for suggestions because I would like to be able to determine the names of components being used with Object.keys() -- and having wrappers makes this practically impossible.

**Comment by BRKalow** [comment]
Would a react context work for you? The components could use the context data without explicitly being passed props.

```jsx
const MyContext = React.createContext({})

function Test() {
  const data = useContext(MyContext)

  return <div>{data.foo}</div>
}

function MyPage({ mdxSource }) {
  return (
    <MyContext.Provider value={{ foo: 'bar' }}>
      <MDXRemtoe {...mdxSource} components={{ Test }} />
    </MyContext.Provider>
  )
}
```

**Comment by max-pod** [comment]
Yeah, that or trying to use one of the transformers like https://github.com/jaywcjlove/rehype-rewrite
