### ISSUE TITLE
Markdown table does not render properly on v4

### ISSUE THREAD

**Issue by raulfdm** [hashicorp/next-mdx-remote#242]
# Bug report

## Describe the bug

After migrating to v4, all tables are not being rendered properly.

It's important to mention that if I paste the exact same markup in the [MDX playground,](https://mdxjs.com/playground/), all works fine.

## To Reproduce

I've created this repository so you can test: https://github.com/raulfdm/next-mdx-remote-table-bug

It's clearly a problem with v4 because if you downgrade to v3.0.8 (latest 3) and run the application again, the table will be proper formatted.

## Expected behavior

All tables being rendered correctly.

## Screenshots

Live demo: https://next-mdx-remote-table-bug.vercel.app/

## System information

- OS: `macOs Monterey 12.2.1`
- Browser (if applies) [e.g. chrome, safari]: `any`
- Version of Next.js: [e.g. 10.0.1]: `12.1.0`
- Version of next-mdx-remote [e.g. 10.0.1]: `4.0.0`
- Version of Node.js: [e.g. 12.0.0]: `v14.18.3`

**Comment by Fox32** [comment]
Not sure about your particular problem, but I also had problems with tables when migrating. I missed this detail from the [MDX2 migration guide](https://mdxjs.com/migrating/v2/#gfm):

> We turned off GFM features in MDX by default. GFM extends CommonMark to add autolink literals, footnotes, strikethrough, tables, and task lists. If you do want these features, you can use a plugin. How to do so is described in [our guide on GFM](https://mdxjs.com/guides/gfm/).

**Comment by raulfdm** [comment]
> Not sure about your particular problem, but I also had problems with tables when migrating. I missed this detail from the [MDX2 migration guide](https://mdxjs.com/migrating/v2/#gfm):
> 
> > We turned off GFM features in MDX by default. GFM extends CommonMark to add autolink literals, footnotes, strikethrough, tables, and task lists. If you do want these features, you can use a plugin. How to do so is described in [our guide on GFM](https://mdxjs.com/guides/gfm/).

Thanks for sharing that @Fox32 ... I missed this bit.

Adding gfm indeed added back the tables.
