### ISSUE TITLE
No Difference between Code Block and inline code

### ISSUE THREAD

**Issue by thatanjan** [hashicorp/next-mdx-remote#244]
I am using next-mdx-remote `4.0.0` version. When I try to add syntax highlights to code it doesn't distinguish between a code block and an inline code.
I am using [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer) for syntax highlight with the following code.
```javascript
// CodeBlock.jsx

import React from 'react'
import Highlight, { defaultProps } from 'prism-react-renderer'
import vsDark from 'prism-react-renderer/themes/vsDark'

const CodeBlock = ({ children, className }) => {
	const language = className ? className.replace(/language-/, '') : ''

	return (
		<Highlight
			{...defaultProps}
			theme={vsDark}
			code={children.trim()}
			language={language}
		>
			{({ className, style, tokens, getLineProps, getTokenProps }) => (
				<pre className={className} style={{ ...style, padding: '20px' }}>
					{tokens.map((line, i) => (
						<div key={i} {...getLineProps({ line, key: i })}>
							{line.map((token, key) => (
								<span key={key} {...getTokenProps({ token, key })} />
							))}
						</div>
					))}
				</pre>
			)}
		</Highlight>
	)
}

export default CodeBlock
```

### My mdx code
![image](https://user-images.githubusercontent.com/71136371/157228048-7de5d6d6-2d2c-404c-897a-045a921d3bc2.png)

### MDX component object
```javascript
import CodeBlock from './CodeBlock'

const components = {}

components.code = CodeBlock

export default components
```

### Result
![image](https://user-images.githubusercontent.com/71136371/157226389-56144c3b-627a-4277-8314-ce1941cbf88a.png)

### Expected Result
![image](https://user-images.githubusercontent.com/71136371/157227090-ce197140-a2a4-4c93-828b-185be7f0334d.png)

It works with the version `3.0.8` but not with the `4.0.0` version

Thanks in advance.

**Comment by DecliningLotus** [comment]
Can confirm this is affecting my project too. If you don't use the ternary operator for the variable `language`, it outright breaks because inline code returns `className` as undefined.

**Comment by alexcarpenter** [comment]
@thatanjan Try switching to:

```
import CodeBlock from './CodeBlock'

const components = {}

components.pre = CodeBlock

export default components
```

**Comment by BRKalow** [comment]
Note that MDX was upgraded to v2 as part of this, which was a breaking change and requires changes in how you author content.

See the upgrade guide here: https://mdxjs.com/migrating/v2/#update-mdx-content

Of note:
> The special component name inlineCode was removed, we recommend to use pre for the block version of code, and code for both the block and inline versions

**Comment by thatanjan** [comment]
Finally, it is working. Thank you so much @BRKalow and @alexcarpenter.
I switched the `code` tag to `pre` tag for CodeBlock.
```javascript
import CodeBlock from './CodeBlock'

const components = {}

components.pre = CodeBlock

export default components
```

I also changed the prism code. Now it is getting the code from the nested `code` tag.
```javascript
import React from 'react'
import Highlight, { defaultProps } from 'prism-react-renderer'
import vsDark from 'prism-react-renderer/themes/vsDark'

const CodeBlock = ({ children }) => {
	if (!children || children.type !== 'code') return null

	const {
		props: { className, children: code = '' },
	} = children

	const language = className ? className.replace(/language-/, '') : ''

	return (
		<Highlight
			{...defaultProps}
			theme={vsDark}
			code={code.trim()}
			language={language}
		>
			{({ className, style, tokens, getLineProps, getTokenProps }) => (
				<pre className={className} style={{ ...style, padding: '20px' }}>
					{tokens.map((line, i) => (
						<div key={i} {...getLineProps({ line, key: i })}>
							{line.map((token, key) => (
								<span key={key} {...getTokenProps({ token, key })} />
							))}
						</div>
					))}
				</pre>
			)}
		</Highlight>
	)
}

export default CodeBlock
```

**Comment by Henryyy-Hung** [comment]
> Finally, it is working. Thank you so much @BRKalow and @alexcarpenter. I switched the `code` tag to `pre` tag for CodeBlock.
> 
> ```js
> import CodeBlock from './CodeBlock'
> 
> const components = {}
> 
> components.pre = CodeBlock
> 
> export default components
> ```
> 
> I also changed the prism code. Now it is getting the code from the nested `code` tag.
> 
> ```js
> import React from 'react'
> import Highlight, { defaultProps } from 'prism-react-renderer'
> import vsDark from 'prism-react-renderer/themes/vsDark'
> 
> const CodeBlock = ({ children }) => {
> 	if (!children || children.type !== 'code') return null
> 
> 	const {
> 		props: { className, children: code = '' },
> 	} = children
> 
> 	const language = className ? className.replace(/language-/, '') : ''
> 
> 	return (
> 		<Highlight
> 			{...defaultProps}
> 			theme={vsDark}
> 			code={code.trim()}
> 			language={language}
> 		>
> 			{({ className, style, tokens, getLineProps, getTokenProps }) => (
> 				<pre className={className} style={{ ...style, padding: '20px' }}>
> 					{tokens.map((line, i) => (
> 						<div key={i} {...getLineProps({ line, key: i })}>
> 							{line.map((token, key) => (
> 								<span key={key} {...getTokenProps({ token, key })} />
> 							))}
> 						</div>
> 					))}
> 				</pre>
> 			)}
> 		</Highlight>
> 	)
> }
> 
> export default CodeBlock
> ```

A better way to distinguish between inline and block is to pass a parameter `isBlock` from `<pre>` to `<code>`. 

./mdx-components.js
```javascript
import CodeBlock from "@/components/shared/MDXComponents/CodeBlock/CodeBlock";
import React from "react";

export function useMDXComponents(components) {
    return {
        pre: ({ children }) => (
            <pre>
                {React.Children.map(children, child => {
                    if (React.isValidElement(child)) {
                        return React.cloneElement(child, { isBlock: true });
                    }
                    return child;
                })}
            </pre>
        ),
        code: CodeBlock,
        ...components,
    }
}
```

.../CodeBlock.jsx
```javascript
import styles from './CodeBlock.module.css'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { coldarkDark } from 'react-syntax-highlighter/dist/esm/styles/prism';

const CodeBlock = ({ className, children, isBlock, ...props }) => {

    // check if parent is pre tag

    const match = /language-(\w+)/.exec(className || '');

    if (! isBlock) {
        return (
            <code {...props} className={styles.inlineCodeBlock}>
                {children}
            </code>
        )
    }

    return (
        <pre className={styles.codeBlock} aria-hidden={false}>
            <div className={styles.header}>
                <span className={styles.language}>
                    {match ? match[1] : "code"}
                </span>
                <div className={styles.copyButton}>
                    Copy Code
                </div>
            </div>
            <SyntaxHighlighter
                style={coldarkDark}
                PreTag="div"
                language={match ? match[1] : null}
                {...props}
            >
                {String(children).replace(/\n$/, '')}
            </SyntaxHighlighter>
        </pre>
    )
};

export default CodeBlock;
```
