### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by mxcdh** [hashicorp/next-mdx-remote#246]
Hello

I have error: 'TypeError: Cannot read properties of undefined (reading 'map')'.

I understand what this error means. 
But I still understand, why ingredients.array is not available in my components. 
I transmit array from .mdx files. 

Bellow my project (whole blog):
https://stackblitz.com/edit/nextjs-cbqaq9?file=components%2FIngredients.tsx

btw
Before added question I read all documentation and check demo project :/
https://github.com/vercel/next.js/blob/canary/examples/with-mdx-remote/components/CustomLink.js

**Comment by BRKalow** [comment]
Closing as I don't believe this is an issue with the library. Feel free to reply if you feel differently.

Thanks!
