### ISSUE TITLE
Improve typing of the `frontmatter` prop

### ISSUE THREAD

**Issue by MatthijsMud** [hashicorp/next-mdx-remote#249]
The type of `frontmatter` is specified as `Record<string, string>`. This isn't completely accurate, as the properties could also have types such as `number`, `boolean`, `Array`, `Object`.

> **[types.d.ts](https://github.com/hashicorp/next-mdx-remote/blob/e1078a8218d27b4c362b893302423449949be1ad/src/types.ts#L38)**
> ```ts
> export declare type MDXRemoteSerializeResult<TScope = Record<string, unknown>> = {
>   // ...
>   frontmatter?: Record<string, string>;
> }
> ```

Consider using a type that more accurately describes the potential values such as the following, or use `unknown`. 
**Note:** Recursive types are available starting at [Typescript 3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#more-recursive-type-aliases).
```ts

type Frontmatter = 
| number 
| string 
| boolean
| Array<Frontmatter> 
| { [key: string]: Frontmatter }
;

export declare type MDXRemoteSerializeResult<TScope = Record<string, unknown>> = {
  // ...
  frontmatter?: Record<string, string>;
}
```

**Comment by BRKalow** [comment]
Thanks for opening this! Would you be willing to create a PR to adjust the types as you've suggested here?
