### ISSUE TITLE
For markdown options, `mdPlugins` is now `remarkPlugins` in mdx-js

### ISSUE THREAD

**Issue by brianespinosa** [hashicorp/next-mdx-remote#25]
mdPlugins still works, but there is a warning for that configuration in the mdx-js codebase about the deprecation. We should update the docs to reflect this change.

I can include this in my PR this morning as well.

**Comment by jescalan** [comment]
Thank you! Would be wonderful to have this as its own PR, since this can/should be merged right away 😀
