### ISSUE TITLE
Cannot find module '/node_modules/react/jsx-runtime' imported from '/node_modules/next-mdx-remote/dist/index.js'

### ISSUE THREAD

**Issue by emonhossainraihan** [hashicorp/next-mdx-remote#254]
I am using the NextJS latest version `12.1.1` and facing this issue. 

Inside the `/node_modules/next-mdx-remote/dist/index.js` it import `react/jsx-runtime`

```js
import * as runtime from 'react/jsx-runtime.js';
```

Which create the issue but if I changed it with actual path it works.

```js
import * as runtime from 'react/cjs/react-jsx-runtime.production.min.js';
``` 

But how to solve it in deployment stage? Like vercel also show the same issue when  deploying. 

```shell
> Build error occurred
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/vercel/path0/node_modules/react/jsx-runtime' imported from /vercel/path0/node_modules/next-mdx-remote/dist/index.js
```

Isn't `next-mdx-remote` compatible with `nextJS@12.1.1`?

**Comment by fernpolo** [comment]
Check out #250

**Comment by BRKalow** [comment]
Thanks for the report! We're going to investigate a potential solution that works for both react v17 and v18 this week.

**Comment by raulfdm** [comment]
I hate when I have to hack things around but totally get the burden of open source and work.

I'm currently using v4.02 and as workaround I've create a script (run post install deps) to replace the import and re-write the file:

```js
#!/usr/bin/env node

const path = require('path');
const fs = require('fs');

const mdxRemoteEntryPath = path.resolve(__dirname, '..', 'node_modules/next-mdx-remote/dist/index.js');
const mdxRemoteEntryContent = fs.readFileSync(mdxRemoteEntryPath, 'utf8');
const mdxRemoteEntryContentFixed = mdxRemoteEntryContent.replace(
  `import * as runtime from 'react/jsx-runtime.js';`,
  `import * as runtime from 'react/jsx-runtime';`
);

fs.writeFileSync(mdxRemoteEntryPath, mdxRemoteEntryContentFixed);
```

Far from optimal but may help (now everything is working fine again)
