### ISSUE TITLE
This is what is appearing when trying to install it on the next project. 

### ISSUE THREAD

**Issue by tanvirpiash** [hashicorp/next-mdx-remote#258]
`npm install next-mdx-remote@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving:-nextjs@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=16.x <=17.x" from next-mdx-remote@4.0.2
npm ERR! node_modules/next-mdx-remote
npm ERR!   next-mdx-remote@"4.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/kausarpial/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kausarpial/.npm/_logs/2022-04-06T09_11_27_838Z-debug-0.log`
it seems like this version of the mdx-remote is not compatible with the react v18.

**Comment by nirajmchauhan** [comment]
+1
Getting the same error
