### ISSUE TITLE
import { serialize } from "next-mdx-remote/serialize" cost is 505.1k

### ISSUE THREAD

**Issue by talatkuyuk** [hashicorp/next-mdx-remote#259]
Import cost is an vscode extension, to calculate import cost related with the packages' sizes.

MDXRemote component is just 4.3k
```javascript
import { MDXRemote } from "next-mdx-remote"; // import cost: 4.3k (gzipped: 1.9k)
```

But, When I import the serialize function:
```javascript
import { serialize } from "next-mdx-remote/serialize"; // import cost: 505.1k (gzipped: 159.2k) It is red colored!!!
```

It calculates as 0.5MB. Is it so much? Is it normal?

**Comment by fernpolo** [comment]
Yes, I've had similar numbers. But because you only need to use `serialise` at build time, this doesn't actually affect the client bundle at all. (Next.js doesn't include code in `getStaticProps`, etc)

**Comment by BRKalow** [comment]
Exactly right, since serialize is only used server-side/at build-time the bundle impact is not as big of a concern as it is on the client.
