### ISSUE TITLE
Typescript Error on Components Props

### ISSUE THREAD

**Issue by rizkimcitra** [hashicorp/next-mdx-remote#262]
**Getting typescript error when passing MDXComponent props to component.**

my MDXComponents:

```tsx
import CustomPre from './Pre'

const MDXComponents = {
  pre: CustomPre
}

export default MDXComponents
```

error: 
```tsx
Type '{ pre: (prop: CustomPreProps) => JSX.Element; }' is not assignable to type 'Record<string, Element>'.
  Property 'pre' is incompatible with index signature.
    Type '(prop: CustomPreProps) => JSX.Element' is not assignable to type 'Element'.ts(2322)
```

screenshot:

<img src="https://ik.imagekit.io/mlnzyx/aaa_1__BeUXxMArZ.png?ik-sdk-version=javascript-1.4.3&updatedAt=1650149530326" />

works fine on my [previous project](https://github.com/rizkimcitra/rizkicitra/blob/main/src/pages/article/%5Bslug%5D.tsx#L146), and no error shown, and here's my package.json file.

```json
"dependencies": {
    "@heroicons/react": "^1.0.6",
    "@tailwindcss/typography": "^0.5.2",
    "clsx": "^1.1.1",
    "gray-matter": "^4.0.3",
    "jotai": "^1.6.3",
    "mdx-prism": "^0.3.4",
    "next": "12.1.4",
    "next-mdx-remote": "^3.0.8",
    "next-seo": "^5.4.0",
    "next-themes": "^0.1.1",
    "prism-themes": "^1.9.0",
    "react": "18.0.0",
    "react-dom": "18.0.0"
  },
  "devDependencies": {
    "@trivago/prettier-plugin-sort-imports": "^3.2.0",
    "@types/node": "17.0.23",
    "@types/react": "18.0.1",
    "@types/react-dom": "18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.19.0",
    "@typescript-eslint/parser": "^5.19.0",
    "autoprefixer": "^10.4.4",
    "cz-conventional-changelog": "3.3.0",
    "eslint": "8.13.0",
    "eslint-config-next": "12.1.4",
    "eslint-config-prettier": "^8.5.0",
    "husky": "^7.0.4",
    "lint-staged": "^12.3.7",
    "next-sitemap": "^2.5.20",
    "postcss": "^8.4.12",
    "prettier": "^2.6.2",
    "tailwindcss": "^3.0.23",
    "typescript": "4.6.3"
  }
```

**Comment by BRKalow** [comment]
Hey, is this something you're still running into? We're just passing the types along from the underlying MDX library.

**Comment by rizkimcitra** [comment]
> Hey, is this something you're still running into? We're just passing the types along from the underlying MDX library.

Oops, pardon, I just updated my package and I have no type error anymore, thanks !

![image](https://user-images.githubusercontent.com/62492410/170853858-7436b56d-9bf6-428f-8230-53de5afd0be3.png)

**Comment by ehteshamdev0** [comment]
Hey, I am also facing the same issue although I am using the latest version of the library.
