### ISSUE TITLE
After version 4.0 the wrapper component does not work as it used to due to changes to children. 

### ISSUE THREAD

**Issue by liltechnomancer** [hashicorp/next-mdx-remote#263]
Prior to version 4.0 you could use the `wrapper` component to map over all the children and do arbitrary things like reverse them.

This is a pretty important feature to MDX, please check out this video if you are curious why.  https://www.youtube.com/watch?v=xEu3t-KJVVg

I set up a small reproduction of this. You can downgrade this repo to any 3.0 build and notice the posts will be reversed, but are not on 4.0 https://github.com/liltechnomancer/next-mdx-remote-bug

Thanks!

**Comment by chardskarth** [comment]
@liltechnomancer  @BRKalow Is this possibly caused by upgrading to mdx-js v2?

Is the change in wrapper - children documented anywhere? It doesn't seem to be found in @mdx-js migration pages.

**Comment by dstaley** [comment]
`wrapper` still works as expected in previous versions of MDX, but the layout of its children has changed. This is not an issue with `next-mdx-remote` nor something we can control.
