### ISSUE TITLE
Add config example for using a directory with auto generated routes for MDX files similar to the way a `/pages` route works

### ISSUE THREAD

**Issue by brianespinosa** [hashicorp/next-mdx-remote#27]
Would be great if this respected the use of this folder being in the root, of a Nextjs repo, or if it was in a /src folder relative to a /pages directory there the way Nextjs supports both.

**Comment by jescalan** [comment]
Just added a nice example for how this can be done here: https://github.com/hashicorp/next-mdx-remote/tree/master/examples/blog

Hope this helps!
