### ISSUE TITLE
Errors when attempting to transpile (next-transpile-modules) with next-mdx-remote@^4.0.0

### ISSUE THREAD

**Issue by max-pod** [hashicorp/next-mdx-remote#271]
Hello, asking for help using `next-transpile-modules` with `next-mdx-remote`

Created a sample project with breakdown: https://github.com/max-pod/next-mdx-attempted-transpile-4

See config file: https://github.com/max-pod/next-mdx-attempted-transpile-4/blob/b89156fc2cc386915b02ee883ddc14c20991fa15/next.config.js#L1

```
Failed to compile.

./node_modules/next-mdx-remote/dist/serialize.js
Module not found: ESM packages (@mdx-js/mdx) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

Import trace for requested module:
./node_modules/next-mdx-remote/serialize.js
./pages/posts/[slug].js

./node_modules/next-mdx-remote/dist/serialize.js
Module not found: ESM packages (vfile) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

Import trace for requested module:
./node_modules/next-mdx-remote/serialize.js
./pages/posts/[slug].js

./node_modules/next-mdx-remote/dist/serialize.js
Module not found: ESM packages (vfile-matter) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

Import trace for requested module:
./node_modules/next-mdx-remote/serialize.js
./pages/posts/[slug].js
```

Attempted to use `esmExternals: loose` to get:

```
Error occurred prerendering page "/posts/example-post". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: _vfile.VFile is not a constructor
```

**Comment by BRKalow** [comment]
Is there an error you're seeing using `next-mdx-remote` without `next-transpile-modules`?

**Comment by max-pod** [comment]
@BRKalow I haven't -- are there any sample projects that have used the two together?

**Comment by BRKalow** [comment]
@max-pod Ultimately I'm questioning why you need to run `next-mdx-remote` through `next-transpile-modules` if we're able to run `next-mdx-remote` successfully on its own.

**Comment by BRKalow** [comment]
I'm going to close this, as `next-mdx-remote` should work on its own with any additional transpilation.
