### ISSUE TITLE
Ability to get all rendered components and their props

### ISSUE THREAD

**Issue by DreamplaySE** [hashicorp/next-mdx-remote#276]
**Background**: I would like to create a component inside mdx that refers to a glossary I've got externally. Ideally, I'd be able to do something like `<Gloss glossId="teddy-bear">Teddy Bear</Gloss>` and then it'd automatically create a tooltip with an explanation of the word. As such, I'd like to pass in data on all the glossaries that have been mentioned inside MDX, but I can't since there's no way to get all the properties.

**Feature Request**: I'd ike to suggest adding an option of getting all the components that are being rendered and their properties. This would allow for me to go through each component I need server-side data for and pass it through to the renderer.

**Comment by BRKalow** [comment]
This sounds similar to what some folks do to extract headings to render a table of contents somewhere. One approach would be to create a custom remark plugin which accepts an array and mutates the array.

```ts
const termsUsed = []

serialize('<Gloss glossId="teddy-bear">Teddy Bear</Gloss>', { remarkPlugins: [
  remarkPluginExtractTermUsage({ termsUsed })
]})

console.log(termsUsed) // [{ glossId: 'teddy-bear', text: 'Teddy Bear' }]
```

The hypothetical remark plugin would visit nodes in the tree and push to `termsUsed`. Looking at the `mdast` in the MDX playground might be a good starting point here: https://mdxjs.com/playground/

Hope this helps!
