### ISSUE TITLE
Cannot parse markdown comments

### ISSUE THREAD

**Issue by vitonsky** [hashicorp/next-mdx-remote#277]
# Steps to reproduce

Try to compile this text

```md
Some text
<!-- md comment -->
```

# Expected behavior

Text compiled successfully

# Actual behavior

Error
```md
Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
```

# Notes

This is easy to fix, we have to apply https://www.npmjs.com/package/remark-comment plugin.
Author say "This plugin must be added after MDX, otherwise you will see this error" but we can't apply it before MDX at this time on user side

**Comment by BRKalow** [comment]
So effectively you're looking for a way to apply a remark plugin before mdx attempts to parse the source, right? I'm not sure if `@mdx-js/mdx` supports this out of the box 🤔

**Comment by vitonsky** [comment]
@leebyron what you think about it? Is it possible to enable md comments for mdx?

**Comment by BRKalow** [comment]
I'm going to close this out as I don't think this issue is specific to `next-mdx-remote`, as MDX v2 does not support HTML comment syntax.
