### ISSUE TITLE
Checkboxs are not rendered in the new version

### ISSUE THREAD

**Issue by ChasexCodex** [hashicorp/next-mdx-remote#278]
The markdown checkboxes (using [ ] and [x]) are not parsed and rendered for some reason.

### Expected:
- [ ] (some info)
- [x] (a checked one)

### Actual:
- [ ]
- [x]
(the content next to the checkboxes still exists)

### How to reproduce:

- Use the example from next.js
```bash
yarn create next-app --example with-mdx-remote with-mdx-remote-app
cd with-mdx-remote
yarn
yarn dev
```

- Add a checkbox to `posts/example-post.mdx`
- open `localhost:3000/posts/example-post`
- Notice the checkboxes exist
- Now update the `next-mdx-remote`
```bash
yarn remove next-mdx-remote
yarn add next-mdx-remote
```
- Notice the checkboxes are gone now

#### Also:
The dots of the list items are appearing in both cases though they shouldn't.

**Comment by BRKalow** [comment]
This is part of GitHub Flavored Markdown (GFM), not commonmark. You can get this to work by using this plugin: https://mdxjs.com/guides/gfm/

**Comment by ChasexCodex** [comment]
Thanks. But why was it working on version 3?

**Comment by BRKalow** [comment]
GFM was included by default in MDX v1, which v3 used. v4 upgraded to MDX v2, which does not include it by default (ref: https://mdxjs.com/migrating/v2/#gfm).
