### ISSUE TITLE
Fallback plain markdown mode (missing docs?)

### ISSUE THREAD

**Issue by kachkaev** [hashicorp/next-mdx-remote#279]
👋 folks!

We are using `next-mdx-remote` in https://github.com/blockprotocol/blockprotocol and it works great! Thanks a lot for this pretty smart lib!

I was working on a new feature today and got confused with `next-mdx-remote` a little, so decided to ping you here.

In addition to the standard mdx docs, we need to render some markdown files, importantly, without `mdx` syntax being on. These markdown files come from third-party developers, so we don’t control them and therefore don’t want any JSX features. Imagine this as rendering package READMEs on npmjs.com in addition to the own platform docs.

I understand that I can use [react-markdown](https://www.npmjs.com/package/react-markdown) or [react-markdown](https://www.npmjs.com/package/react-markdown) or [markdown-to-jsx](https://www.npmjs.com/package/markdown-to-jsx) for plain markdown rendering, but it feels somewhat odd to leverage two separate approaches for very similar tasks. Alternative libraries will move markdown parsing to the client, which will increase bundle size. Besides, it won't be possible to re-use custom components (or at least write some of them twice).

Regardless of whether plain markdown mode is possible, it’d be greate to see it mentioned in `next-mdx-remote` docs. It’d be also nice to know if it is possible to toggle html parsing too (`<img>`, `<sup>`, etc.).

Thanks again for your lib! 🙌

**Comment by kachkaev** [comment]
I can confirm that `{ mdxOptions: { format: 'md' } }` does the job! It was not available to me at first because I was on `next-mdx-remote@3` instead of `@4`. Feel free to close this issue if you want – I’ll keep it open in case you want to tweak README first.

Cheers 🙌

**Comment by BRKalow** [comment]
Yay, I'm glad it worked! Updated the docs here: https://github.com/hashicorp/next-mdx-remote/pull/280
