### ISSUE TITLE
Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by vitalyliber** [hashicorp/next-mdx-remote#281]
Hi all! I have this issue using this lib with React 18.

My libs:
```js
{
    "next": "12.1.6",
    "next-mdx-remote": "^4.0.3",
    "react": "18.1.0",
    "react-dom": "18.1.0",
}
```

Any solution?

<img width="953" alt="Снимок экрана 2022-06-15 в 10 13 49" src="https://user-images.githubusercontent.com/8033090/173765745-f6f22830-b72e-4b15-809e-5569cdc235dd.png">

**Comment by BRKalow** [comment]
Can you provide a minimal reproduction?

**Comment by vitalyliber** [comment]
I'm sorry it happens only when I wrap next-mdx-remote content to the <p> tag.
I renamed the <p> tag to <div> and this error disappear.

**Comment by Gelio** [comment]
Weirdly enough, I also faced the same problem when I also wrapped `MDXRemote` inside of a `p` by mistake:

```tsx
<p>
  <MDXRemote {...content} />
</p>
```

The error message makes this error quite cryptic. Changing the container to a `div` fixed the issue

**Comment by BRKalow** [comment]
This is likely due to the HTML spec, in that `p` cannot contain block-level elements: https://www.w3.org/TR/html401/struct/text.html#edef-P

**Comment by Gelio** [comment]
Yes, you are right about the spec, that's definitely invalid. The error message is slightly perplexing though and the console errors do not help diagnose the problem.

Here is the DOM hierarchy I got when the page was server-side rendered and I had JavaScript enabled:
![image](https://user-images.githubusercontent.com/889383/174256432-a93827c9-d5d9-4134-9104-e32c507aa1d1.png)

Most errors in the console look like this:

![image](https://user-images.githubusercontent.com/889383/174256559-d807fe74-c4df-4e48-b7f8-0abc7c9e1ecf.png)

In the middle of the console errors there is a buried error message explaining the root of the problem:

![image](https://user-images.githubusercontent.com/889383/174256666-f1a13e8c-e1e2-4506-b1aa-36d88dc3da7d.png)

What would help is making the error message for the actual cause more prominent, or making it appear as one of the first/last errors logged to the console. Right now it appears in the middle of the list of 19 errors, 18 of which are the same.

I'm suggesting what would make issues like these one easier to debug without looking for help online. I don't expect any changes, just offering suggestions

**Comment by BRKalow** [comment]
I agree! Unfortunately these errors are coming directly from React, so there is not a ton we can do in this library.

**Comment by FisherRobison** [comment]
I am running into the same error even when the container is a div. MDXRemote still renders as a <p> is that expected? 

```
export default function TestPage({ source }) {
  return (
    <div >
      <MDXRemote {...source} components={components} />
    </div>
  )
}

export async function getStaticProps() {
  // MDX text - can be from a local file, database, anywhere
  const source = 'Some **mdx** text, with a component <Test />'
  const mdxSource = await serialize(source)
  return { props: { source: mdxSource } }
}
```

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/17657726/177023005-24045125-f49f-419f-b0e0-8a7611c24098.png">

**Comment by oliver-daniel** [comment]
I can confirm that this is still an issue in November of 2022. When I try to use the `components` prop to replace `img` tags with a component similar to this:

``` js
<div className="image-container" {...container}>
        <NextImage 
            className="image-component"
            fill
            placeholder='blur'
            {...image}
        />
    </div>
```

I see that the `image-container` div is wrapped in a `<p>` tag, leading to the `HydrationMismatch` error. Replacing the `p` tag with a block-type component (e.g., `div`) removes the error, but doesn't work well for my workflow.

Is there a better way to configure the package or my code to ensure this wrapping doesn't happen?

**Comment by Vikram0118** [comment]
I recently worked on a project where i take mdx to render stuffs in next js. Faced the same hydration error and the problem was one of my `<h4>` was automatically wrapped by `<p>`. 

After same research found a way to avoid it. I `added few new extra lines in the mdx file after every line of text` and the automatic `<p>` tag wrapping was gone.
