### ISSUE TITLE
Cannot parse HTML <br> tag

### ISSUE THREAD

**Issue by Eliot00** [hashicorp/next-mdx-remote#284]
I use [tui.editor](https://ui.toast.com/tui-editor) to write markdown blog, it will add some soft line break, next-mdx-remote can't serialize it, even `<br>` is a legal HTML tag without slash.

```
Error: [next-mdx-remote] error compiling MDX:
Expected a closing tag for `<br>`
```

```
    "next": "^12.1.0",
    "next-mdx-remote": "^4.0.3",
```

**Comment by patradanai** [comment]
i have same issure wuth tui editor

**Comment by BRKalow** [comment]
This is a limitation of MDX: https://mdxjs.com/docs/

You might consider trying to force the content to be parsed as vanilla markdown, instead of mdx.

```
serialize(content, { mdxOptions: format: 'md' })
```

Note that you won't be able to use MDX components with this approach.

**Comment by talatkuyuk** [comment]
I suffer from the same issue. I think there should be a solution.
