### ISSUE TITLE
Server error rendering MDX on page with dynamic routing

### ISSUE THREAD

**Issue by linda-lai** [hashicorp/next-mdx-remote#285]
👋 Hey folks. Encountering the same issue raised here when rendering a page with dynamic routing: https://github.com/vercel/next.js/issues/36646. I'm setting up a new project based off the [with-mdx-remote blog example](https://github.com/vercel/next.js/tree/canary/examples/with-mdx-remote) in the Next repo.

Working okay on the deployed production version. But visiting a unique slug route locally in dev mode, I'm getting this error:

![Screen Shot 2022-07-07 at 11 24 03 pm](https://user-images.githubusercontent.com/29894441/177785929-83b3205f-db50-465b-a9e2-f1fc8d6d22ea.png)

![Screen Shot 2022-07-07 at 11 25 08 pm](https://user-images.githubusercontent.com/29894441/177785943-1b15699c-32eb-469e-9446-c32d2c9faab9.png)

Reverting from the latest (`v4.0.3`) to `v3.0.8` mentioned in the linked issue is the workaround. Wondering if there's a specific configuration or change I need to make to move from v3 to v4?

```js
import { serialize } from "next-mdx-remote/serialize";
import { MDXRemote } from "next-mdx-remote";

export default function Post({ frontmatter, content }) {
  return (
    <div>
      <h1>{frontmatter.title}</h1>
      <img alt="" width="200" src={frontmatter.img}></img>
      <p>{frontmatter.excerpt}</p>

      <MDXRemote {...content} />
    </div>
  );
}

export const getStaticProps = async ({ params }) => {
  const source = fs.readFileSync(
    path.join(process.cwd(), "posts", `${params.slug}.mdx`)
  );

  const { content, data: frontmatter } = matter(source);

  const mdxSource = await serialize(content);

  return {
    props: { frontmatter, content: mdxSource },
  };
};
```

```json
{
  "dependencies": {
    "gray-matter": "^4.0.3",
    "next": "latest",
    "next-mdx-remote": "^4.0.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "styled-components": "^5.3.5"
  },
}
```

**Comment by raulmihaila** [comment]
I had a similar problem but a different error was displayed (v4.1.0): 
Error: [next-mdx-remote] error compiling MDX: Cannot handle unknown node `raw`

**Comment by BRKalow** [comment]
Hi y'all, are you still encountering this issue?

**Comment by linda-lai** [comment]
@BRKalow It's been awhile so I haven't checked, let me take a look and confirm 👍

**Comment by dstaley** [comment]
Going to go ahead and close this one out for now, but if it's still happening and you're willing to share a minimal reproduction please do and we'd be happy to investigate!
