### ISSUE TITLE
Could not parsing markdown table

### ISSUE THREAD

**Issue by mehedi-sharif** [hashicorp/next-mdx-remote#291]
Hello there,

I have implemented `next-mdx-remote` to my project and everything works perfectly except the table. 

here is the example code of the table:

```
| Tables        |      Are      |  Cool |
| ------------- | :-----------: | ----: |
| col 3 is      | right-aligned | $1600 |
| col 2 is      |   centered    |   $12 |
| zebra stripes |   are neat    |    $1 |
```
and the output looks like this:
![image](https://user-images.githubusercontent.com/5304905/180707978-78fb68a6-222c-4fb1-b763-2376f66b6992.png)

is it a bug or I did do something wrong?

**Comment by BRKalow** [comment]
See the MDX v2 upgrade guide: https://mdxjs.com/migrating/v2/#gfm
