### ISSUE TITLE
Different name of children type for image

### ISSUE THREAD

**Issue by hendraaagil** [hashicorp/next-mdx-remote#293]
I have a markdown like this to display an image:

```md
![Project View](/assets/blog/berkenalan-dengan-react-memahami-useeffect/project-view.png)
```

I want to wrap that image using `figure` element. So, in Paragraph component I add condition like this:
```js
  if (children.type && children.type.name === 'Image') {
    return (
      <Box
        as="figure"
        my={3}
        mx="auto"
        w="fit-content"
        bg={bgColor}
        textAlign="center"
        rounded="md"
        overflow="hidden"
      >
        {children}
      </Box>
    );
  }

  return (
    <Text my={3} fontWeight="400">
      {children}
    </Text>
  );
```

In development server, it rendered correctly
![image](https://user-images.githubusercontent.com/54741166/184544187-081e3d8b-c74c-491e-8985-5a6d27dedfb7.png)

But, after I build and start the (production) server. It rendered `p` instead of `figure` element
![image](https://user-images.githubusercontent.com/54741166/184544290-d1fdb577-1b7e-4a27-997f-82ecb08c2baf.png)

After that, I find that `children.type.name` value can be either `'H'` or `'P'` when I start in production server. So, my solution is adding a condition like this 😅 

```js
  if (
    children.type &&
    (children.type.name === 'Image' ||
      children.type.name === 'P' ||
      children.type.name === 'H')
  ) {
    ...
  }
```

But, anyone know how this can happen? Because it confused me.

```
"next-mdx-remote": "^4.1.0"
```

Thanks.

**Comment by timomeh** [comment]
Instead of unwrapping the image from the paragraph yourself, you can use the https://github.com/remarkjs/remark-unwrap-images plugin. It removes the wrapping paragraph.

```tsx
import remarkUnwrapImages from 'remark-unwrap-images'

<MDXRemote
  options={{
    mdxOptions: {
      remarkPlugins: [
        remarkUnwrapImages,
      ]
    }
  }}
/>
```

**Comment by hendraaagil** [comment]
Thanks @timomeh! That plugin works perfectly for me.
