### ISSUE TITLE
Question: How does one parse frontmatter and use directly as `pageProps`?

### ISSUE THREAD

**Issue by chrisrzhou** [hashicorp/next-mdx-remote#295]
Hi!

I am curious if the library supports the following consumer pattern.

Given an `pages/example.mdx` file with frontmatter

```mdx
---
title: Title
description: description
---

# Heading 1
```

To automatically be able to pass the parsed frontmatter object as data into Next's `pageProps` (e.g. in `_app.js`)

```js
// pages/_app.js
export default function App({ Component, pageProps }) {
  console.log(pageProps);  // pageProps should contain the `example.mdx`'s parsed frontmatter
  return <Component {...pageProps }/>
}
```

**Comment by BRKalow** [comment]
We do support parsing frontmatter, as can be seen here: https://github.com/hashicorp/next-mdx-remote#additional-examples

You could then pass access that through `pageProps` 👍
