### ISSUE TITLE
skip render unknow language code block

### ISSUE THREAD

**Issue by misakamayako** [hashicorp/next-mdx-remote#296]
if a markdown contains unknown language code block, such as

\`\`\`sequence
Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!
\`\`\`

the `serialize` will throw an error, but maybe skipping it is a better option

**Comment by BRKalow** [comment]
Can you provide the error? That will help determine if it's an issue with this library or another dependency.

**Comment by misakamayako** [comment]
Error: [next-mdx-remote] error compiling MDX:
Unknown language: `sequence` is not registered

and mdxOptions only contains `format: 'md'`

**Comment by BRKalow** [comment]
Are you using any remark/rehype plugins for syntax highlighting? I would look there. This library doesn't do any special handling of code blocks before handing it to MDX.
