### ISSUE TITLE
MDXRemote won't replace iframes

### ISSUE THREAD

**Issue by leo-petrucci** [hashicorp/next-mdx-remote#297]
I woke up to some errors popping up in my logs causing my pages to 500.

In my site I regularly embed `iframes` which contain inline styles, before these iframes are rendered I usually override the `style` props so that they're not inlined:

```
const components = {
    iframe: (props: any): React.ReactNode => (
        <iframe
            {...props}
            style={{
                width: '100%',
                height: '500px',
                border: 0,
                borderRadius: '4px',
                overflow: 'hidden',
            }}
        />
}
```

This seemed to work until I upgraded to v4. Now iframes simply aren't replaced at all which causes my pages to 500.

I know the easy fix is to not add those inline styles to my pages, but I have people writing content that aren't great with code so I'd like them to not have to worry about removing attributes from iframes or other embeds.

I created a [reproduction on Codesandbox](https://codesandbox.io/s/fancy-architecture-7wog1l?file=/pages/index.js)

For comparison, [this is how it used to work in 3.0.8](https://codesandbox.io/s/hungry-pascal-im4f1u)

Is this a bug or is there something I'm doing wrong?

**Comment by peduarte** [comment]
same here 😄 does anyone have any idea why this is happening?

**Comment by ryngonzalez** [comment]
Getting the same as well! I'm on `4.4.1` currently.
