### ISSUE TITLE
Usage clarification

### ISSUE THREAD

**Issue by EarthlingDavey** [hashicorp/next-mdx-remote#3]
Hi I've read through the readme, can you help me out with a couple of questions please?

1. Is it correct that the app must be rebuilt if the md source content is updated?

2. Because of `getStaticProps` I need to have the string available at the page level. 
If I'm making a query from inside a component is it possible to use `next-mdx-remote`?

**Comment by kylemac** [comment]
1. i think the answer is "yes, probably". if you're doing your data fetching in GSP when you're in dev mode (`next dev`) then `getStaticProps` will refetch your data each time and you won't have to rebuild. However when you do a `next build` and presumably a `next static` your query won't run again on the client-side, unless you were using `getServerProps`.

> side note:  In dev-mode your local watcher won't know that your source has been updated so you'll have to do a manual refresh on the view, but the new data will be fetched. We have this problem too so we have a little lib we're working on that would solve this local-dev issue: https://github.com/hashicorp/next-remote-watch but it's very experimental atm

2. if you're not doing your data-fetching via `getStaticProps` than you're not really taking advantage of the benefits of having your data only be fetched at build time. Alternatively you could do your data fetching at the `getServerProps` level and you wouldn't need a rebuild. Nextjs urges folks by convention to do all their data fetching at the getStaticProps or getServerProps level whenever possible, to get optimization benefits. You may have a use-case where you can't avoid it though and in that case I believe you'd need the MDX runtime in your client-side bundles.

**Comment by EarthlingDavey** [comment]
Thank you @kylemac ... I've learned a tonne today!

I'm now using the package as intended and it's working amazingly well.

One issue (?) that I'll report separately.

**Comment by kylemac** [comment]
Great to hear! I’ll close this one out and we’ll work through your other issues separately.
