### ISSUE TITLE
The frontmatter typings are incorrect

### ISSUE THREAD

**Issue by judehunter** [hashicorp/next-mdx-remote#302]
The current type for the frontmatter is `Record<string, string>`. Since the frontmatter has parsed values (such as arrays and objects), the values of the Record should be all possible YAML values. Or at least it should be `Record<string, unknown>` or `Record<string, any>` so that no type assertions have to be done :)

**Comment by BRKalow** [comment]
This is configurable via type parameters on [`MdxRemoteSerializeResult`](https://github.com/hashicorp/next-mdx-remote/blob/main/src/types.ts#L23-L26), but there might be opportunity for us to make this clearer in documentation.

PRs welcome!

**Comment by MaximilianGaedig** [comment]
Came here to fix this simple issue, just as @judehunter said updating it to `Record<string, any>` is the way to go

**Comment by BRKalow** [comment]
This was addressed in a recent release. The default type is now `Record<string, unknown>`
