### ISSUE TITLE
Can `remark-mdx-frontmatter` plugin be working in `mdxOptions`?

### ISSUE THREAD

**Issue by kssflow** [hashicorp/next-mdx-remote#303]
(First, thank you for reading and big shoutout to this valuable open source project)

**Objects**
**I want to use frontmatter value in mdx file itself.**

I have heard that `remark-mdx-frontmatter` make it happen.
So I have tried.. following code

```js
export async function getStaticProps({ params }) {
    // ...some code related to reading .mdx file
    
    const mdxSource = await serialize(
        source,
        {
            mdxOptions: {
                remarkPlugins: [remarkGfm, remarkMath, remarkFrontmatter, remarkMdxFrontmatter],
                rehypePlugins: [rehypeKatex, rehypeHighlight],
                format: 'mdx'
            },
            parseFrontmatter: true // doesn't matter including it or not...
        }
     )

    return {
        props: {
            source: mdxSource
        }
    }
```

but that didn't work... (although other plugins worked correctly).
Is there something I missing?
Although I have consulted to reference, I cannot find right solution so create this help..

Thanks for reading. And if this question is silly, sorry for consuming your times..
Thanks in advance!

**Comment by BRKalow** [comment]
Hey there, `parseFrontmatter: true` should make the frontmatter available via `frontmatter` in your MDX: https://github.com/hashicorp/next-mdx-remote/blob/main/__tests__/serialize.test.tsx#L125-L149

Was this not working for you?
