### ISSUE TITLE
v4: Cannot provide filepath to plugins

### ISSUE THREAD

**Issue by nwalters512** [hashicorp/next-mdx-remote#309]
I have a plugin that relies on knowing the path to the file being compiled. In `next-mdx-remote` v3, I was able to provide `filepath` via `mdxOptions`, e.g.:

```ts
serialize('# Hello', { mdxOptions: { filepath: '/path/to/file.mdx' } });
```

As of MDX v2, however, `filepath` isn't an option anymore, and that's been replaced by passing a VFile object (https://mdxjs.com/migrating/v2/):

> `filepath` is replaced by accepting a VFile or compatible object as the first argument [file](https://mdxjs.com/packages/mdx/#file)

I would like to be able to provide a filepath, either by passing a `VFile` object directly to `serialize`, or by adding support for a `filepath` key in the second argument to `serialize`.

**Comment by BRKalow** [comment]
So, we do actually construct a `VFile` instance internally. Maybe we can update `serialize()` to accept a `string` or a `VFile` instance, like MDX's `compile()` does. Happy to take a look at a PR if you're up to take a crack at it!

**Comment by nwalters512** [comment]
@BRKalow great! I opened a PR adding this: #311.

**Comment by NekoChanTaiwan** [comment]
Is `file.path` include in `VFile` object now ?

I'm using `next-mdx-remote@4.2.0`, and I didn't find it.

![image](https://user-images.githubusercontent.com/47508893/210492949-3de158b9-e53f-47df-80d8-f5cd1f4d4f6e.png)

**Comment by NekoChanTaiwan** [comment]
> Is `file.path` include in `VFile` object now ?
> 
> I'm using `next-mdx-remote@4.2.0`, and I didn't find it.
> 
> ![image](https://user-images.githubusercontent.com/47508893/210492949-3de158b9-e53f-47df-80d8-f5cd1f4d4f6e.png)

Never mind, I fixed it 🥲

![image](https://user-images.githubusercontent.com/47508893/210494662-17c1fd9a-ab4a-4316-b088-bedd17943dff.png)
