### ISSUE TITLE
How to handle HTML with inline styles?

### ISSUE THREAD

**Issue by smakman** [hashicorp/next-mdx-remote#314]
I'm trying to parse markdown that contains HTML tags with inline styles (for example `<iframe style="overflow: hidden" />`), which results in:

```
Error: The `style` prop expects a mapping from style properties to values, not a string. 
For example, style={{marginRight: spacing + 'em'}} when using JSX.
```

I tried using `rehype-react`:

```js
const source = await serialize(content, {
  mdxOptions: {
    rehypePlugins: [rehypeReact],
  },
});
``` 

But this results in:

```
Error: [next-mdx-remote] error compiling MDX: createElement is not a function
```

Is there any way to parse HTML with inline styles?

**Comment by BRKalow** [comment]
As far as I know, this isn't supported with MDX as tags are treated as JSX, not HTML. 💭

**Comment by BRKalow** [comment]
I don't think that doc is accurate, based on the [playground](https://mdxjs.com/playground/):
![Screen Shot 2022-11-21 at 12 02 28 PM](https://user-images.githubusercontent.com/1289701/203127762-42f2eefc-6437-4016-a15b-f755cc605e0a.png)

**Comment by talatkuyuk** [comment]
@smakman I suppose the `rehype-plugin` is not the plugin which can be used in the `serialize` function. In the docs, it says that `This package is a unified plugin that compiles HTML (hast) to React nodes (the virtual DOM that React uses).`. Means that it is a kind of compiler that can be used with unified. This transformation is already being done via serialize itself.

**Comment by talatkuyuk** [comment]
@BRKalow As far as I see in the documentation, https://github.com/micromark/micromark#intro, The `micromark` uses [common-markup-state-machine](https://github.com/micromark/common-markup-state-machine). I do not understand the relation between the `micromark` and the `mdx-state-machine` which is in progress, the document says.

**Comment by BRKalow** [comment]
I'm going to close this out as addressing this is out of scope of what `next-mdx-remote` wants to be responsible for. Feel free to continue the discussion!

**Comment by Azeem838** [comment]
Hi

To fix this issue, I used the serializer as follows:
```javascript
  serialize(`<span style="color: red">Hello</span> World`, {
    mdxOptions: {
      rehypePlugins: [rehypeRaw],
      format: "md",
    },
  })
```

**Comment by eric-burel** [comment]
Hi folks, sorry for digging out this issue but I've just hit it and it's a bit nasty. Is there a way to tell mdx to treat the content as "raw" markdown, and not "mdx" with JSX in it? Maybe this could be documented somehow, even if not directly covered by next-mdx-remote.
My use case is rendering my GitHub profile description, in markdown, from within my app. I'd like to reuse most of the code from my next-mdx-remote setup, but I am ok to add a few tweaks to support this.
