### ISSUE TITLE
How to use custom options with `rehype` plugins?

### ISSUE THREAD

**Issue by AgileNix** [hashicorp/next-mdx-remote#315]
How can I add a custom option to a rehype plugin?

For example, the docs at https://github.com/rehypejs/rehype-external-links say that I should use the following syntax
```js
.use(rehypeExternalLinks, {rel: ['nofollow']})
```

In `next-mdx-remote`, however, the plugins are passed differently and I don't see how I can add the `{rel: ['nofollow']}` option.

```js
 rehypePlugins: [rehypeExternalLinks]
```

**Comment by DET171** [comment]
You would do something like the following:
```js
rehypePlugins: [
  [rehypeExternalLinks, {rel: ['nofollow']}]
]
```

**Comment by BRKalow** [comment]
@DET171 is correct! `mdxOptions` has the same format as the options for `compile()` from '@mdx-js/mdx`: https://mdxjs.com/docs/extending-mdx/#using-plugins

**Comment by AgileNix** [comment]
perfect, thank you @DET171 and @BRKalow
