### ISSUE TITLE
markdown diff and language

### ISSUE THREAD

**Issue by i-coder-keller** [hashicorp/next-mdx-remote#316]
How should I go about using markdown diff syntax, currently using diff doesn't explain the language, I've tried 'diff&js' 'diff-js' and can't highlight it
![image](https://user-images.githubusercontent.com/50040262/202680649-476c5372-fea3-429b-87da-c1f509b2ec45.png)
I hope it should look like this:
![image](https://user-images.githubusercontent.com/50040262/202680820-fe09cf3a-c753-4de2-a54b-9e780f9f2932.png)

**Comment by BRKalow** [comment]
What highlighting plugin are you using? This isn't a feature that's part of the core MDX library, it's something should be handled by whatever syntax highlighter you're using.

**Comment by i-coder-keller** [comment]
> 你用的是什么高亮插件？这不是核心 MDX 库的一部分的功能，它应该由您使用的任何语法突出显示来处理。

I'm using the rehype-prism-plus plugin, I checked the documentation for this plugin and it doesn't specify what I should do, it doesn't recognize the language when I diff

**Comment by BRKalow** [comment]
It looks like there's a note in the README here on supporting `diff`: https://github.com/timlrx/rehype-prism-plus/tree/main

There's nothing in particular that `next-mdx-remote` can help with here so I'm going to close this out.
