### ISSUE TITLE
Help setting the Content-Security-Policy to allow unsafe-eval

### ISSUE THREAD

**Issue by manuelonate** [hashicorp/next-mdx-remote#320]
Hi,

I have used next-mdx-remote on several next.js projects with no problem. In my last one, I am getting errors on the pages that use next-mdx-remote functions. After some investigation it looks like this website has more strict CSP settings than the others, for reasons I don't know, because I have done nothing different.

 Anyway, I have tried to solve the issue by inserting the following code to the component that uses next-mdx-remote:

`    <Head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="script-src 'unsafe-eval'"
        />
      </Head>
  `

Doing so, the pages load, but on the browser console I get a bunch of errors and warnings. Two for each js resource loaded by the page, such as:

Error: Content Security Policy: The page’s settings blocked the loading of a resource at https://eurousc.es/_next/static/chunks/webpack-951a1212eff2ebb2.js (“script-src”).

Warning: Loading failed for the <script> with source “https://eurousc.es/_next/static/chunks/webpack-951a1212eff2ebb2.js”.

Furthermore, the pages look alright, but they become unresponsive, with links not working and the UI not reacting.

So, my question is, what is the recommended way to provide the 'unsafe-eval' directive to a website created with next.js?

**Comment by BRKalow** [comment]
Hi there, I think you would also need the `'self'` source specified so that you are able to load scripts from the same origin.

```
<meta httpEquiv="Content-Security-Policy" content="script-src 'self' 'unsafe-eval'" />
```

**Comment by noahlst** [comment]
Another approach would be to add the CSP to `next.config.js` if you can:

```js
// Content security options
const securityHeaders = [
  {
    key: "Content-Security-Policy",
    value:
      "script-src 'self' 'unsafe-eval' 'unsafe-inline' [URL]”,
  },
];

module.exports = {
  // Configuration for Next.js
  // …

  // Import HTTP headers
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: securityHeaders,
      },
    ];
  },
};
```

**Comment by dstaley** [comment]
Gonna go ahead and close this issue since an answer has been provided.
