### ISSUE TITLE
Is there a way to use MDXRemote in a component that is not a page ? 

### ISSUE THREAD

**Issue by nisarhassan12** [hashicorp/next-mdx-remote#321]
Hi 🙌🏿  there. 

I have a situation where I have some markdown contents being passed to a component coming through a CMS where the markdown looks like the following:

```md
 # H1

<Quote text="Some random text..." attribution="John Doe" />
```

The component is supposed to be used anywhere i.e alongside other normal components no matter how deep they are in the components tree.

**Comment by noahlst** [comment]
This is not possible because MDX for MDXRemote has to be processed by `serialize`.`serialize` can only be called at build time in `getStaticProps`, which is only available in Next.js pages.

**Comment by BRKalow** [comment]
This is generally correct ☝️ You could pass the result of `serialize` to a nested component from a page component, but with `getStaticProps` at least the `serialize` call ultimately needs to be done there.

**Comment by anthonyhexium** [comment]
Ok just in case someone needs to do so. I used `html-react-parser` library.
