### ISSUE TITLE
Parse error : Could not parse expression with acorn: Unexpected tok

### ISSUE THREAD

**Issue by amm834** [hashicorp/next-mdx-remote#322]
```

14 \| {
00:25:13.825 | 15 \|
00:25:13.825 | > 16 \| &#x20;   case ADMIN;
00:25:13.825 | \| ^
00:25:13.825 | 17 \|
00:25:13.825 | 18 \| &#x20;   case USER;
00:25:13.826 |  
00:25:13.826 | More information: https://mdxjs.com/docs/troubleshooting-mdx
00:25:14.685 | info  - Generating static pages (9/9)
00:25:14.695

<br class="Apple-interchange-newline">


```

**Comment by BRKalow** [comment]
Did you checkout the linked troubleshooting page? https://mdxjs.com/docs/troubleshooting-mdx/#could-not-parse-expression-with-acorn-error

**Comment by amm834** [comment]
I did. `&#x20;` is just a space char it should work fine, in this case.

**Comment by BRKalow** [comment]
Does the MDX you're trying to render work in the playground? https://mdxjs.com/playground/

**Comment by BRKalow** [comment]
I'm going to close this as it appears to be an issue with the source content. Feel free to provide a reproduction if you're able to render the content in the playground but not with `next-mdx-remote`.

**Comment by amm834** [comment]
Sorry for that, I forgot to close this issue 🤣
