### ISSUE TITLE
Error when testing a component importing MDX Remote with Jest and Next

### ISSUE THREAD

**Issue by aburto22** [hashicorp/next-mdx-remote#337]
Hi all,

I am building a Next.js app and using as a Jest as my test runner. I want to create an integration test for a component importing MDX Remote, but Jest is throwing out errors.

After a bit of researched, I found out that jest don't understand ES Modules, so we need to transform the modules by tweaking our jest config file. This is what I have added to my jest config file:

```
const nextMdxRemotePatterns =
  '/node_modules/(?!(next-mdx-remote|@mdx-js|unist-|unified|bail|is-plain-obj|trough|vfile|remark-|micromark-|micromark|estree-util-|parse-entities|character-entities|mdast-util-|character-reference-invalid|is-|stringify-entities|periscopic|hast-util-|comma-separated-tokens|property-information|space-separated-tokens|zwitch|ccount|decode-named-character-reference|trim-lines))';

const jestConfig = async (...args) => {
  const nextJestConfig = await createJestConfig(customJestConfig)(...args);
  return {
    ...nextJestConfig,
    transformIgnorePatterns: nextJestConfig.transformIgnorePatterns.map(
      pattern => {
        if (pattern === '/node_modules/') {
          return nextMdxRemotePatterns;
        }
        return pattern;
      }
    ),
  };
};
```

This actually does it job well enough, but at some point I am hitting an error about a module that cannot be found:

```
Cannot find module 'estree-walker' from 'node_modules/estree-util-build-jsx/lib/index.js'

Require stack:
  node_modules/estree-util-build-jsx/lib/index.js
  node_modules/estree-util-build-jsx/index.js
  node_modules/@mdx-js/mdx/lib/plugin/recma-jsx-build.js
  node_modules/@mdx-js/mdx/lib/core.js
  node_modules/@mdx-js/mdx/index.js
  node_modules/next-mdx-remote/dist/serialize.js
  node_modules/next-mdx-remote/serialize.js
  tests/unit/components/leasing-calculator/intro.spec.tsx
```

I tried installing this module as a dependency, but that doesn't seem to fix the issue.

I am using next-mdx-remote version 4.3.0.

Any ideas if I am doing something wrong or what can I do to fix this issue?

Thanks!

**Comment by BRKalow** [comment]
Hiya, `next-mdx-remote` is published as a native ES modules package. This jest documentation might be helpful: https://jestjs.io/docs/ecmascript-modules

**Comment by dsinghvi** [comment]
What was the solution here? Can't get my jest config to work

**Comment by pacoorozco** [comment]
I don't fully understand how to fix the problem. I've read the link added by @BRKalow but I don't get what to do... :sorry:

**Comment by aburto22** [comment]
At least personally, the response from BRKalow was not helpful (I had already read that page before posting this issue, and my actual problem was tweaking jest to compile ES module libraries. Next-mdx-remote seems to succeed in implementing this in their own tests though, but for some reason it wasn’t working for me).

anyways, I ended up mocking the whole dependency with Jest manual mocks.

This might be useful:  https://jestjs.io/docs/manual-mocks

**Comment by weilin-ong** [comment]
> Hiya, `next-mdx-remote` is published as a native ES modules package. This jest documentation might be helpful: https://jestjs.io/docs/ecmascript-modules

Hi, could you explain how this helps?

**Comment by weilin-ong** [comment]
> At least personally, the response from BRKalow was not helpful (I had already read that page before posting this issue, and my actual problem was tweaking jest to compile ES module libraries. Next-mdx-remote seems to succeed in implementing this in their own tests though, but for some reason it wasn’t working for me).
> 
> anyways, I ended up mocking the whole dependency with Jest manual mocks.
> 
> This might be useful: https://jestjs.io/docs/manual-mocks

Hi, could you show how you mock it please?
