### ISSUE TITLE
Remark/Rehype Plugins in Next.js 13?

### ISSUE THREAD

**Issue by bathrobe** [hashicorp/next-mdx-remote#341]
Hey there, thanks for supporting v 13. Wondering how to insert remark and rehype plugins now, as the example in the readme was for the Serializer component which is no longer necessary.

**Comment by BRKalow** [comment]
Hiya, the RSC component accepts an `options` prop:

```ts
import { MDXRemote } from 'next-mdx-remote/rsc'

const options = {
	mdxOptions: {
		remarkPlugins: [],
		rehypePlugins: []
	}
}

export default function Page({ source }) {
	return <MDXRemote source={source} options={options} /> 
}
```

We'll update the docs here!

**Comment by bathrobe** [comment]
Thank you!

**Comment by nvitaterna** [comment]
Is there any way this could take the options provided to MDX via withMDX in next.config.js?
