### ISSUE TITLE
Table inside JSX element

### ISSUE THREAD

**Issue by hahnbeelee** [hashicorp/next-mdx-remote#343]
I have code that looks like this:
```jsx
  <Accordion title="Auth0">
    Required parameters for integration:

    | Parameter     | Description                                   |
    | ------------- | --------------------------------------------- |
    | Domain        | ManagementClient server domain                |
    | Client Id     | Management API Non Interactive Client Id.     |
    | Client Secret | Management API Non Interactive Client Secret. |
  </Accordion>
```
And this is what the configuration of my serialize function:
```typescript
const getMdxSource = async (
  pageContents: string,
  data: Record<string, unknown>,
  snippetTreeMap: Record<string, Root> = {}
) => {
  return serialize(pageContents, {
    scope: data,
    mdxOptions: {
      remarkPlugins: [
        [remarkMdxInjectSnippets, snippetTreeMap],
        remarkGfm,
        withRemoveJavascript,
        withFrames,
        withTableOfContents,
        withSmartypants,
        withRemoveImports,
      ],
      rehypePlugins: [
        withRemoveUnknownJsx,
        withCodeBlocks,
        [
          withSyntaxHighlighting,
          {
            ignoreMissing: true, // Ignore errors when no language is found
          },
        ],
        withListRoles,
        withApiComponents,
        withRawComponents,
        withLayouts,
      ],
      format: 'mdx',
      useDynamicImport: true,
    },
    parseFrontmatter: true,
  });
};
```
([Source Code](https://github.com/mintlify/mint/blob/main/client/src/mdx/getMdxSource.ts))
Basically, my end goal is a GFM table inside a JSX element, but for some reason the table is not being rendered properly. See below.
![CleanShot 2023-02-22 at 17 18 24](https://user-images.githubusercontent.com/55263191/220800787-0223429e-7832-4441-9fd4-69e79da8eb47.png)

## What I've tried
- Un-indenting the children makes it render properly and I can probably figure out some sort of work-around that un-indents cases like this but that seems sub-optimal.
(Notice how the table is flush with the left.)
```jsx
<Accordion title="Auth0">

Required parameters for integration:

| Parameter     | Description                                   |
| ------------- | --------------------------------------------- |
| Domain        | ManagementClient server domain                |
| Client Id     | Management API Non Interactive Client Id.     |
| Client Secret | Management API Non Interactive Client Secret. |

</Accordion>
```
![CleanShot 2023-02-22 at 17 21 29](https://user-images.githubusercontent.com/55263191/220801111-db264366-dcc6-4587-aff1-e37b5664aaff.png)
- Setting `parseFrontmatter: false`
- Used the next.js debugger to walk through the tree. If I put the debugger in a remark plugin right after the remarkGfm plugin, the tree looks exactly like you'd expect it to look if the table was broken. Aka only the header is an actual node and the rest of the table is in a string.
![CleanShot 2023-02-22 at 17 28 50](https://user-images.githubusercontent.com/55263191/220801912-f3a2e270-2586-4277-856d-c6801c72bd78.png)

Any idea what could be causing this? I already posted in [mdx](https://github.com/mdx-js/mdx/discussions/2245) and messed around with my configuration but no avail. :/

**Comment by dstaley** [comment]
Going to close this as I believe this was using MDX v1, which I don't believe supported JSX wrapped Markdown.
