### ISSUE TITLE
Parse markdown inside a non-children component prop

### ISSUE THREAD

**Issue by klaasman** [hashicorp/next-mdx-remote#344]
Hi there,

I've been searching for the answer the last hour, but unable to find anything related.

I have the following mdx:

```markdown
<Graphic src="./image.png" caption="Image caption with *markdown* such as a [link](#)" />
```

In this case the caption obviously get's passed with type `string`, but ideally I want it to be parsed and have it passed as a ReactNode into my custom Graphic component. So I tried this:

```markdown
<Graphic src="./image.png" caption={<>Image caption with *markdown* such as a [link](#)</>} />
```

And that didn't seem to help. It became a ReactNode type, but the markdown did not get parsed.

Then I tried the following:
```markdown
<Graphic src="./image.png">
  Image caption with *markdown* such as a [link](#)
</Graphic>
```
So I basically removed the `caption` prop and moved the content to the children. This works, so there's definitely a possibilty in parsing markdown which is part of a prop (in this case `children`). But how can I have this working with the `caption` prop?

**Comment by BRKalow** [comment]
Hiya, as far as I know this is a limitation of the MDX language and isn't supported without potentially extracting the value of the prop and parsing it independently as a separate MDX string.

**Comment by klaasman** [comment]
Allright! Thanks for taking the time to answer.
