### ISSUE TITLE
Client Side Rendering

### ISSUE THREAD

**Issue by BlackPhoenix134** [hashicorp/next-mdx-remote#360]
Hi,

What would be necessary to allow the MDX to be rendered client side to see a preview for editing articles in an admin UI?
I could use some hacky way to save the current edited article preview in memory of the server and use server props to render the preview from memory, but there must be a better way.

Thanks

**Comment by magicmatatjahu** [comment]
@BlackPhoenix134 As I understand, you have some editor to change the content of markdown/mdx files and you wanna see some preview for that changes, am I right? If yes, I suggest you to create the special API route for it like `/api/mdx/preview` and on the changes in editor, send the content the the new api and render the rendered (using the `next-mdx-remote` lib) content from result in given place in your app/page. Using the `getServerSideProps()` is not a good choice for your case.
