### ISSUE TITLE
'MDXRemote' cannot be used as a JSX component

### ISSUE THREAD

**Issue by tfsomrat** [hashicorp/next-mdx-remote#366]
Hi, when I am using MDXRemote in my `app/page.tsx` file. it gives this warning, but it works perfectly. I am a beginner of TypsScript. how to fix this?

![image](https://github.com/hashicorp/next-mdx-remote/assets/58769763/133d049b-90d0-40e9-ae2c-f9c1ecece51e)

**Comment by BRKalow** [comment]
Hi there! This should help: https://nextjs.org/docs/app/building-your-application/configuring/typescript#async-server-component-typescript-error

The fix:
```tsx
{/* @ts-expect-error Async Server Component */}
<MDXRemote ... />
```

**Comment by tfsomrat** [comment]
Hey @BRKalow,  it is really helpful. now it's working properly.

But I need one more thing. how to add `rehypePlugins` and `remarkPlugins` with it?

**Comment by tfsomrat** [comment]
I have config `next.config.mjs` like this

```
import createMDX from "@next/mdx";
import remarkGfm from "remark-gfm";
import config from "./src/config/config.json" assert { type: "json" };

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  basePath: config.base_path !== "/" ? config.base_path : "",
  trailingSlash: config.site.trailing_slash,
};

const withMDX = createMDX({
  options: {
    remarkPlugins: [remarkGfm],
    rehypePlugins: [],
    providerImportSource: "@mdx-js/react",
  },
});

export default withMDX(nextConfig);
```

but it's not working. I am not getting table element from markdown.

**Comment by BRKalow** [comment]
You would pass those as props to `<MDXRemote />`:

```tsx
import remarkGfm from 'remark-gfm'

const mdxOptions = {
	remarkPlugins: [remarkGfm]
}

...

<MDXRemote ... options={{ mdxOptions }} />
```

I'll add an example in the README for passing plugins with the `next-mdx-remote/rsc` API 👍
