### ISSUE TITLE
Importing 'next-mdx-remote/render-to-string' causes "Can't resolve 'fs'" Error

### ISSUE THREAD

**Issue by agstover** [hashicorp/next-mdx-remote#37]
Including `import renderToString from 'next-mdx-remote/render-to-string'` in my file causes my Next app to crash with this error. The error kind of sprang up randomly. I deleted package.lock.json, node_modules, and .next and reinstalled everything, and am still receiving the error.

```
error - ./node_modules/@babel/core/lib/transformation/normalize-file.js:9:0
Module not found: Can't resolve 'fs'
null
```

The repo is located at https://github.com/agstover/kinetica and the page where the library is imported is here: https://github.com/agstover/kinetica/blob/master/pages/learn/%5B...trade%5D.js

**Comment by jescalan** [comment]
You need to actually use it in `getStaticProps` or `getServerProps` in order for it to work. If you just import it without using it, next estimates that it's being used as a side effect and doesn't drop it from the client side bundle. As soon as you use the method, this error will go away 😀

**Comment by MattSPalmer** [comment]
Hi, just to clarify since I'm encountering this too - what are the particulars of how `renderToString` must be used in `getS_____Props` to avoid being flagged as a side effect?

My usage looks something like:

```javascript
import hydrate from 'next-mdx-remote/hydrate';
import renderToString from 'next-mdx-remote/render-to-string';

import TechnicalPost from 'components/essays/technical-post';
import { getBySlug, allSlugs } from 'utils/essays/fetch-post';
import { hydrateFragment, prerenderFragment } from 'utils/essays/render';

const components = {};

const HydratedPost = ({ title, rawFragments }) => {
  return (
    <TechnicalPost
      title={title}
      fragments={rawFragments.map((fragment) =>
        hydrateFragment(fragment, components, hydrate)
      )}
    />
  );
};

export const getStaticPaths = async () => {
  const { slugs } = await allSlugs();
  return {
    paths: slugs.map((slug) => ({ params: { slug } })),
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const { post } = await getBySlug(params.slug);
  const rawFragments = await Promise.all(
    post.fragments.map((fragment) =>
      prerenderFragment(fragment, components, renderToString)
    )
  );
  return {
    props: { title: post.title, rawFragments },
  };
};

export default HydratedEssay;
```

My ultimate hope is that there is a way to share/organize pre-rendering code outside of page files by just passing the next-mdx-remote exports as callbacks, but perhaps the way the code is analyzed is working against me here.

**Comment by jescalan** [comment]
Hey @MattSPalmer - it just had to be used, at all. In your code example, it is imported but not used, hence the error.

**Comment by MattSPalmer** [comment]
Thanks for the link - I did try importing it into `prerenderFragment` first and got the same result - but now I'm wondering if it's because I'm exporting a hydrating function from the same file!
