### ISSUE TITLE
 nextjs 13.4.3 not work

### ISSUE THREAD

**Issue by liompei** [hashicorp/next-mdx-remote#371]
in nextjs 13.4.3

code 
`import {getFileBySlug, getFiles} from "@/lib/mdx";
import {MDXRemote} from "next-mdx-remote";

const components = {}

export default async function Page({params}) {
  const source = await getBlog(params.slug)
  return (
    <div>
      <article className='prose prose-stone'>
        <MDXRemote {...source} components={components}/>
      </article>
    </div>
  )
}

async function getBlog(slug) {
  const slugMdx = await getFileBySlug(slug)
  return slugMdx
}

export async function generateStaticParams() {

  const blogs = await getFiles('blog')
  const blogList = blogs.map((post) => ({
    slug: post.replace(/\.mdx/, '')
  }))
  console.log(blogList)
  return blogList
}`

response:

Unhandled Runtime Error
Error: Cannot read properties of null (reading 'useState')

**Comment by GP21895242** [comment]
I have the same issue when I switch to next app router mode. It seems working fine in page router mode

**Comment by BRKalow** [comment]
There is a separate API for server components, documented here: https://github.com/hashicorp/next-mdx-remote#react-server-components-rsc--nextjs-app-directory-support
