### ISSUE TITLE
Question: Will this support the Rust-based compiler?

### ISSUE THREAD

**Issue by ovflowd** [hashicorp/next-mdx-remote#378]
Just wondering if this project intents to have a version that uses the Rust-based MDX compiler maintained by Vercel. Thanks!

**Comment by BRKalow** [comment]
It's something [we've explored](https://github.com/hashicorp/next-mdx-remote/blob/brk.feat/mdx-rs/src/serialize-experimental.ts)! In practice, the lack of plugin support has felt relatively limiting, and the Rust-based compiler packaged with Next is not necessarily meant for runtime use. It increases the size of your deployed serverless functions by quite a bit.

**Comment by ovflowd** [comment]
That makes sense, their Rust Compiler is also still on beta so it might receive iterations in the future.

I appreciate the answer! Would there be any chance of integration if in the future it supports plugins and becomes less verbose (bundled with different things?)

**Comment by BRKalow** [comment]
We'll definitely keep an eye on it and integrate it in the future if it makes sense. 👍
