### ISSUE TITLE
Loading an ESM recma plugin during serialize

### ISSUE THREAD

**Issue by timmyg** [hashicorp/next-mdx-remote#380]
I am trying to loading a custom plugin `recma.mjs` but am getting `SyntaxError: Unexpected token 'export'`. I am successfully using the same plugin when configuring `@next/mdx` in my `next.config.mjs`. Any ideas?

```mjs
import { mdxAnnotations } from 'mdx-annotations';
import recmaNextjsStaticProps from 'recma-nextjs-static-props'; // this one is esm

function recmaRemoveNamedExports() {
  return (tree) => {
    tree.body = tree.body.map((node) => {
      if (node.type === 'ExportNamedDeclaration') {
        return node.declaration;
      }
      return node;
    });
  };
}

export const recmaPlugins = [
  mdxAnnotations.recma,
  recmaRemoveNamedExports,
  recmaNextjsStaticProps,
];
```

I am including it this like...
```ts
  const mdxSource = await serialize(template, {
    mdxOptions: {
      remarkPlugins,
    },
  });
```

**Comment by BRKalow** [comment]
Can you provide a minimal reproduction in a standalone repo or a codesandbox so we can take a look? Thanks!

**Comment by timmyg** [comment]
@BRKalow appreciate the quick reply - love this package so far.

I reproduced [here](https://codesandbox.io/s/next-mdx-remote-props-forked-7ysdpz?file=/pages/index.tsx). This recma.mjs is able to be imported into my next.config nextMdx config successfully but not into next-remote-mdx

**Comment by timmyg** [comment]
basically, I am trying to get the same processing on markdown (through plugins) that is done via`@mdx/next` to a raw `mdx` file

**Comment by dstaley** [comment]
Thank you for reporting this! `next-mdx-remote` (and the underlying MDX library) executes code by essentially running the generated JavaScript via a constructed function, like the following:

```js
const fn = Reflect.construct(Function, ['return 1'])
fn() // returns 1
```

If your MDX contains `export` statements, they will not be parsed correctly by `Reflect.construct`:

```js
const fn = Reflect.construct(Function, ['export const a = 1']) // Uncaught SyntaxError: Unexpected token 'export'
```

So this is something we're not able to fix in this library. Thank you for reporting this though!
