### ISSUE TITLE
Suggestion : Add mdxOption for React Server Components

### ISSUE THREAD

**Issue by BeginArjun** [hashicorp/next-mdx-remote#385]
## Suggestion : 
- Fixing the `serialize()` in `next-mdx-remote` OR
- Adding a new method for users to add `mdxOption`

**Comment by laem** [comment]
Also thought I could add options to my MDXRemote import from next-mdx-remote/rsc but it doesn't seem to work.

**Comment by gaearon** [comment]
This works for me, does it not work for you?

```js
          <MDXRemote
            source={content}
            options={{
              mdxOptions: {
                remarkPlugins: [remarkSmartpants],
                rehypePlugins: [
                  [
                    rehypePrettyCode,
                    {
                      theme: overnight,
                    },
                  ],
                ],
              },
            }}
          />
```

**Comment by dstaley** [comment]
This appears to be working as intended, but if not please provide a reproduction and we'd be happy to take a closer look!
