### ISSUE TITLE
Docs Suggestion Regarding Issue : #384

### ISSUE THREAD

**Issue by BeginArjun** [hashicorp/next-mdx-remote#386]
A few days ago I came up with an issue while using the `serialize()` function. After a lot of investigation and debugging I realised that I have used the wrong imports and that the new NextJS version using `app` directory doesn't support this function and doesn't need 
the `serialize()` function at all.

## Suggestion : 
- Include a little Note for the users using latest version of NextJS `app` directory to point [here](https://github.com/hashicorp/next-mdx-remote#react-server-components-rsc--nextjs-app-directory-support)

**Comment by dstaley** [comment]
The docs are pretty explicit about how to use `next-mdx-remote` via React Server Components, but I'll see if we can make error messages more clear to indicate where something isn't going correctly!
