### ISSUE TITLE
Feat(TOC): proposal

### ISSUE THREAD

**Issue by AugustinMauroy** [hashicorp/next-mdx-remote#395]
_TOC mean "table of content"_
I propose to introduce an TOC data generation.

We can use the `compileMDX` API

Like that: 
```js
const { content, TocData } = await compileMDX({
    source: `
      # Hello World
      This is from Server Components!
      
      ## Second Hello world.
    `,
    options: { parseFrontmatter: false, parseToc: true },
  })
 ```
 
 Type of `TocData` can be :
 ```ts
 type TocData = {
    heading: string
    level: number
    // not sure but it's can useful to create anchor heading
    id?: string 
}[]
```

> I would be delighted to accomplish this proposal

**Comment by minonl** [comment]
It should prevent duplicating ids for headings having same content.
eg. https://docs.pmnd.rs/zustand/getting-started/comparison#npm-downloads-trend
```
## Redux
### State Model
...
## Jotai
### State Model
...
## Recoil
### State Model
```
Fow the moment, there are several `id="state-model"` generated which all lead to the first appearing one.

Here in Github, the ids will be append with suffix number say `state-model-1` `state-model-2`

**Comment by AugustinMauroy** [comment]
@minonl 

i will get eyes on that. Thanks for reporting.

**Comment by B2o5T** [comment]
I think it's out of the scope of this library

**Comment by stern-shawn** [comment]
> I think it's out of the scope of this library

Agreed, there are already remark plugins for this, such as [remark-toc](https://github.com/remarkjs/remark-toc), or you can roll your own. For example, a custom remark plugin that finds all the headers in a page, compiles them into a list including the data you want (`heading`, `level`, `id`), and append that to your page's frontmatter for consumption by UI components.

**Comment by talatkuyuk** [comment]
I agree with @stern-shawn.

As an example, I want to share a custom `remark plugin` that I created.
```typescript
import { type Plugin } from "unified";
import { type Root } from "mdast";
import { visit } from "unist-util-visit";
import { slug } from "github-slugger";
import { toString } from "mdast-util-to-string";

type HeadingTocItem = {
  value: string;
  url: string;
  depth: number;
  parent?: string;
  level?: number[];
};

const plugin: Plugin<[{ exportRef: HeadingTocItem[] }], Root> = (options) => {
  return (tree) =>
    visit(tree, "heading", (node, index, parent) => {
      const textContent = toString(node);
      const parentType = parent?.type;

      options.exportRef.push({
        value: textContent,
        url: `#${slug(textContent)}`,
        depth: node.depth,
        parent: parentType,
      });
    });
};

export default plugin;
```
Then you can use it in the remark plugin lists, and use the `exportRef` in the `scope` *within the options:*
```js
import remarkTocHeadings from "./lib/remark-toc-headings.js";

{
  scope: { toc },
  remarkPlugins: [
    [ remarkTocHeadings, { exportRef: toc } ],
  ]
}
```
This mechanism works very well.

**Comment by dstaley** [comment]
Going to close this out as an alternative has been provided.

**Comment by shiny** [comment]
Thanks to talatkuyuk, now I've work it out.
Some notes for anyone who still doesn't understand. Here are more details if you  feel confused.

It is a server componet, render in RSC
```typescript

// install packages before use 
import rehypeSlug from 'rehype-slug'
import rehypeAutolinkHeadings from 'rehype-autolink-headings'
// codes above
import remarkTocHeadings, type { HeadingTocItem } from "./lib/remark-toc-headings.js";

const source = `
## title
content herer
`

// toc is an array contains HeadingTocItem
// typings from ./lib/remark-toc-headings.js
// you should export type HeadingTocItem in that file

const toc: HeadingTocItem[] = []
const { content } = await compileMDX({
    source,
    options: {
      scope: { toc },
      mdxOptions: {
        remarkPlugins: [ [plugin, { exportRef: toc }] ],
        // if you need to wrapping headings in a link, you should add rehypePlugins
        // or it is no need
        rehypePlugins: [ rehypeSlug, [rehypeAutolinkHeadings, { behavior: 'wrap' }] ]
      }
    }
  })
```

now you can use `{content}` in tsc
```
TOC
<ul>
  {toc.map((item, index) => (<li key={index}><Link href={item.url}>{item.value}</Link></li>))}
</ul>

Content
{content}
```
