### ISSUE TITLE
Replacing standard markdown elements doesn't work

### ISSUE THREAD

**Issue by EarthlingDavey** [hashicorp/next-mdx-remote#4]
If I set the components to target standard markdown html elements, like h1, img etc. 

e.g.
```
const components = {
  h1: (props) => <h1 style={{ color: 'tomato' }} {...props} />,
}
```

Then the static files are correct.

But, on page load in the browser. I think the component assignment is ignored.

With my example I'll see a red h1 for a second then black.

Html source has this in it `<h1 style="color:tomato">Games</h1>` ... `mdx(\"h1\", null, \"Games\"),`

Expected behaviour - consistent components across static and in browser.

Thanks - Davey

**Comment by jescalan** [comment]
Thanks for filing this one, I'll get it on the list to address!

**Comment by iamturns** [comment]
Hey @jescalan - any ETA on this one? Is it a tricky bug?

**Comment by revskill10** [comment]
Maybe related, but i couldn't make syntax highlighting work per `mdxjs` docs. Could you provide example with syntax highlighting too ?
