### ISSUE TITLE
Issues with using v3 Next Optimised images

### ISSUE THREAD

**Issue by henryhobhouse** [hashicorp/next-mdx-remote#40]
### Compatibility with Next Optimised images
The new version 3 (canary) of [Next Optimised images](https://github.com/cyrilwanner/next-optimized-images/tree/canary) using [React Optimised Image](https://github.com/cyrilwanner/react-optimized-image#readme) from the same team. 

The latter requires a babel plugin to work. Everything is great until you try to pass in options parameters in the url and then the babel throws an error on either server side (renderToString) or client side (hydrate) in which ever try to parse the `img` links. 

<img width="707" alt="Screenshot 2020-09-29 at 00 31 22" src="https://user-images.githubusercontent.com/25727106/94497078-01dc6f80-01ee-11eb-9ace-ef83c24a363d.png">

### environment
version of node: 12.18.4
version of next-mdx-remote: 1.0.0
version of next-optimize-images: 3.0.0-canary.10
version of react-optimized-image: 0.4.1
version of next: 9.5.4-canary.22

Steps to reproduce

I am struggling to get it working on codesandbox as the same setup I have locally that is working doesn't work there 🤷 Let me know if you need anything in particular though.

Expected behaviour
adding `?lqip` to the end of the url in the `require` for the images should result in low quality blurred image being served.

Actual behaviour
Babel throws an error trying to parse the mdx.

**Comment by henryhobhouse** [comment]
Managed to fix this. Apologies for false alarm!

**Comment by MichielDeMey** [comment]
@henryhobhouse Could you give us some information on how you fixed your issue? 🙂

**Comment by henryhobhouse** [comment]
@MichielDeMey  I have to be honest I've completely forgotten but from memory it was a configuration adjustment rather something more sinister/behind the scenes. Since then I've pivoted the solution completely as it worked well when there were only a few hundred images however the project I am working on has over 5000 and this setup was requiring so much memory it was creating HEAP out of memory issues. 

Still using next-mdx-remote, which is ace, however doing a custom image processing pipeline in which we are creating thumbnails ourselves and then combining those with Next Image component to get the affect we are looking for.

**Comment by MichielDeMey** [comment]
Thanks @henryhobhouse, I'll have a peek at our Webpack configuration. 👍

**Comment by sethreidnz** [comment]
> @MichielDeMey I have to be honest I've completely forgotten but from memory it was a configuration adjustment rather something more sinister/behind the scenes. Since then I've pivoted the solution completely as it worked well when there were only a few hundred images however the project I am working on has over 5000 and this setup was requiring so much memory it was creating HEAP out of memory issues.
> 
> Still using next-mdx-remote, which is ace, however doing a custom image processing pipeline in which we are creating thumbnails ourselves and then combining those with Next Image component to get the affect we are looking for.

I know this issue is dead but I would love to hear more about this... I'm just rebuilding my blog site in next.js and probably won't have that kind of scale issue for a while. But curious what the solution you've gone for looks like and if it's worth going for at this point myself.
