### ISSUE TITLE
Allowing for only hydrating some components

### ISSUE THREAD

**Issue by samrobbins85** [hashicorp/next-mdx-remote#41]
It would be nice to only hydrate some components, and have the others be the ones generated during the build step. My use case for this is that I have some components that don't use the client side features of React, but do import libraries for doing things. These libraries then get included in my bundle when they aren't needed on the client side and more rendering happens on the client side.

I expect this might be something that needs changes to MDX, but I'm not sure what so I thought I'd raise the issue here

**Comment by jescalan** [comment]
Hey @samrobbins85 - I definitely agree, but this is not only a change that would need to be made to mdx, it would need to be made to react itself. React does not support partial hydration in general. It's certainly possible that this library could find some way to twist the rules and make it happen, but it's not a priority for me. If you are interested in trying to contribute a feature like this, I'd very much welcome it though!

**Comment by samrobbins85** [comment]
Thanks! Yeah I wasn't sure the level to which it would require changes, but good to know it's not just me with this kind of use case
