### ISSUE TITLE
Can't import serialize

### ISSUE THREAD

**Issue by pawitpr** [hashicorp/next-mdx-remote#413]
Code: ``import { serialize } from "next-mdx-remote/serialize";``
Error: [{
	"resource": "/home/pawitsahare/Desktop/pathshala/app/svg-paths/page.tsx",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module 'next-mdx-remote/serialize' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 27,
	"endLineNumber": 2,
	"endColumn": 54
}]

Tried reinstall and compiling, but still serialize not found

**Comment by paramaggarwal** [comment]
https://github.com/hashicorp/next-mdx-remote/issues/307

**Comment by dstaley** [comment]
Closing as there's not enough information in this report to be actionable.
