### ISSUE TITLE
<figure> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by piscopancer** [hashicorp/next-mdx-remote#414]
This happens because an figure (image + below text) are rendered inside a `p` tag. But how do I explain `MDXRemote` that this component rather not be contained in a `p` tag but be a standalone block element? 

Look at that
![image](https://github.com/hashicorp/next-mdx-remote/assets/109352196/3ce42f93-fa93-4f9f-bdb2-768ff057f674)
 
That's the code btw
```tsx
<MDXRemote
  source={article.text} // markdown text, all good
  components={{
    // ...
    img: ({ src, alt }) => {
      return (
        <figure>
          <img src={src} alt={alt} />
          <figcaption>{alt}</figcaption>
        </figure>
      )
    }
  }}
/>
```
Please help 😉💋

**Comment by stern-shawn** [comment]
Take a look at a remark plugin such as [remark-unwrap-images](https://github.com/remarkjs/remark-unwrap-images) which will automatically remove the unwanted, wrapping `p` tag. This has also been a bane of my existence in a project 😅 

Be sure to pass the plugin as part of your `serialize` [config](https://github.com/hashicorp/next-mdx-remote#apis), for example:

```ts
serialize(
  yourMdxString, // Raw MDX input here
  {
    mdxOptions: {
      remarkPlugins: [
        remarkUnwrapImages,  // where the magic happens ✨
        ... // other plugins you're using
      ],
      rehypePlugins: [],
      format: 'mdx',
    },
    ...
  }
)
```

**Comment by piscopancer** [comment]
@stern-shawn thank you, I did not know such helpful package existed. However, I struggle a little with the usage guide, should be enough just to throw it into the extensions array and that's it, isn't it? Anyway, it's now working.
```js
import remarkGfm from 'remark-gfm'
import createMDX from '@next/mdx'
import remarkUnwrapImages from 'remark-unwrap-images'

/** @type {import('next').NextConfig} */
const nextConfig = {
  // ...
}

const withMDX = createMDX({
	options: {
		remarkPlugins: [remarkGfm, remarkUnwrapImages],
		rehypePlugins: [],
	},
})

export default withMDX(nextConfig)
```

**Comment by piscopancer** [comment]
@stern-shawn ✅ It's working. I use `next-mdx-remote` to process strings as MDX and that's the only thing I did
```tsx
import { MDXRemote } from 'next-mdx-remote/rsc'

// ...

<MDXRemote
  source={article.text}
  options={{
    mdxOptions: {
      remarkPlugins: [remarkUnwrapImages],
    },
  }}
/>
```

And there is actually no more `p` strangling an image 🤯

![image](https://github.com/hashicorp/next-mdx-remote/assets/109352196/0176cde4-7031-483c-906a-593262f587f0)
