### ISSUE TITLE
support MDX v3

### ISSUE THREAD

**Issue by minpeter** [hashicorp/next-mdx-remote#419]
https://mdxjs.com/blog/v3

Do you have any plans regarding this?
Or is there already an issue tracking this?
When I looked for it, it didn't seem to exist, so I created a new one. I'm sorry if there was any.

**Comment by Yusufzai** [comment]
It has major compatibility issue when you include react componenet

**Comment by minpeter** [comment]
Oh.. But i will (a)wait. 🤓

**Comment by IanMitchell** [comment]
I poked around a little bit on this, and I _think_ this might require first updating `@hashicorp/remark-plugins`. It also looks like it might be a breaking change because of the `useDynamicImports` option change on the MDX side. Updating should simplify the code in this package a tiny bit, on the bright side!

**Comment by talatkuyuk** [comment]
Is there any repo that has been forked from `next-mdx-remote` and works with MDX v3 ?

**Comment by hipstersmoothie** [comment]
There's really not much code in this repo. Upgrading should be relatively simple

**Comment by hipstersmoothie** [comment]
I think it's working now `@alisowski/next-mdx-remote`

I may have dropped support for react < 18 though

**Comment by talatkuyuk** [comment]
Hi @hipstersmoothie and the developers who following the issue about supporting mdx v3.

I have tried `MDXRemote` server component with using the package **"@alisowski/next-mdx-remote/rsc"** which is a adapted version of `next-mdx-remote`.

My nextjs version is **14**.

The problem may not be related the package but related with the `nextjs@14` default behaviour.

When I pass the `components` prop to `MDXRemote` as ususal, it gives error about **strong**: `Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".`

```jsx
return (
    <MDXRemote
      source={source}
      components={{
        strong: (props: React.HTMLAttributes<HTMLElement>) => (
          <strong className="custom-strong" {...props} />
        )
      }}
    />
  );
```

What do you think about that should the **strong** function be a `server action` or `client component`? **This is my main question.**

If it will be a **server action** I have to define the `strong` as a `async function`:
```js
async function strong(props: React.HTMLAttributes<HTMLElement>) {
    "use server";

    return <strong className="custom-strong" {...props} />;
  }
```
then use it in the component props:
```jsx
return (
    <MDXRemote
      source={source}
      components={{strong}}
    />
  );
```
Then the error goes away, no problem. But this use case bothers me, I couldn't understand why I need to create a server action just for that ? This doesn't make sense to me.

On the other way, if the `strong` should be a **client component**, in this case, I have to define it in another jsx/tsx file, putting "use client" on top of the file. This also bothers me as leading to create unnecessary files for simple html tag mapping.

I suppose this is a `nextjs@14` awkward default behavior. 

**I need your and other developers' opinion about that the components should be client components or server actions, or is another way that I don't know?**

**Comment by dstaley** [comment]
Just wanted to drop a note here to let everyone know that MDX v3 is now supported in the canary releases being published from [this PR](https://github.com/hashicorp/next-mdx-remote/pull/448). Please give them a shot and report any issues!
