### ISSUE TITLE
MDX not compiling when using React Component in mdx file

### ISSUE THREAD

**Issue by Yusufzai** [hashicorp/next-mdx-remote#420]
### Summary

I am using NextJS and MDX with next-mdx-remote to get my data and it successfully work but the only problem is whenever I try to import react components I get the following error

> Error: Expected component CodeBlock to be defined: you likely forgot to import, pass, or provide it. It’s referenced in your code at 317:1-317:24

In short :

This Works -

```
---
title: 'First Blog Post'
author: 'Me'
publishDate: 'Nov 4th, 2023'
---

# This is our first post

Here is a regular paragraph

here is a list:

- Item one
- Item two
- Item three

## This is an h2 element

```

This Does Not -

```
---
title: 'First Blog Post'
author: 'Me'
publishDate: 'Nov 4th, 2023'
---

# This is our first post

Here is a regular paragraph

here is a list:

- Item one
- Item two
- Item three

<CodeBlock></CodeBlock>

## This is an h2 element
```

Below are the following files

1. index.js for MDX
https://pastebin.com/5ZmCDtkf

2. articles/[slug]/page.js
https://pastebin.com/X0tGqsip

3. package.json
https://pastebin.com/iNCywNfK

4. mdx-components.js
https://pastebin.com/U8Bn739q

### Additional information

I am using NEXT JS 14.X

**Comment by severinlandolt** [comment]
Having a similar issue, any help would be greatly appreciated!

**Comment by severinlandolt** [comment]
@Yusufzai Does multiline code work for you?

```diff
---
title: 'First Blog Post'
author: 'Me'
publishDate: 'Nov 4th, 2023'
---

# This is our first post

Here is a regular paragraph

+ ```
+  var add2 = function(number) {
+  return number + 2;
+ }
+ ```

```

**Comment by oyal** [comment]
Same issue. `next 14.0.4`、`next-mdx-remote 4.4.1`

This is my content:

```mdx
import Button from '@/components/Button'

---
title: title
description: description
---

## mdx-remote

- 1
- 2
- 3

<Button>button</Button>
```

I got an error:

```
Unhandled Runtime Error
Error: Expected component `Button` to be defined: you likely forgot to import, pass, or provide it.
It’s referenced in your code at `16:1-16:24`
```

**Comment by patrick-xin** [comment]
@Yusufzai with your setup in` index.js`, when you pass components to `compileMDX`, it should be like this:   `components: components`, instead of `components: { components }` as component is already an object.

**Comment by dstaley** [comment]
Looks like an answer has been provided, so I'm going to go ahead and close this one out.
