### ISSUE TITLE
`img` is wrapped with `p` when using `compileMDX`

### ISSUE THREAD

**Issue by devjiwonchoi** [hashicorp/next-mdx-remote#422]
## Reproduction

https://github.com/devjiwonchoi/next-mdx-remote-img-wrapped-with-p-repro

## Description

The `img` is wrapped with a `p` tag.

![Screenshot 2023-12-03 at 3 18 39 AM](https://github.com/hashicorp/next-mdx-remote/assets/120007119/dedf23ee-4fc5-42f4-9cdc-cabf248be36f)

P.S. If I pass the custom `p` component, the wrapped `p` is also modified as the custom.

**Comment by stern-shawn** [comment]
Try out the configuration changes suggested in #414 , that should fix the issue 😄

**Comment by dstaley** [comment]
This is due to how MDX parses Markdown and isn't something we can modify within the context of this library.

```mdx
![devjiwonchoi logo](/devjiwonchoi.png)
```

```json
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "image",
          "title": null,
          "url": "/devjiwonchoi.png",
          "alt": "devjiwonchoi logo"
        }
      ]
    }
  ]
}
```

<img width="938" alt="image" src="https://github.com/hashicorp/next-mdx-remote/assets/88163/c091060d-1d73-49f3-abe9-c82bb8232bd0">
