### ISSUE TITLE
Question: remark and rehype plugins seem not working

### ISSUE THREAD

**Issue by tuan-m-ng** [hashicorp/next-mdx-remote#43]
I'm trying to add the ability to type math in my mdx files, and I'm using the remark and rehype plugins like below: 

```
 const mdxSource = await renderToString(content, {
      components,
      mdxOptions: {
        remarkPlugins: [remarkMath],
        rehypePlugins: [rehypeKatex]
      },
      scope: data
    });
```

but the parsed output does not contain parsed math equations, rather math equations are stilled wrapped around the p tags (`<p> $$ ... $$ </p>`).

What could be the problem? 

Thank you.

**Comment by tuan-m-ng** [comment]
Never mind, I just found out that `remark-math` has recently been updated and that's why the plugins were not working. 

Actually, is there a plan to update `next-mdx-remote` to make use of that latest `remark-math`? 

Thanks!

**Comment by jescalan** [comment]
This repo uses mdx directly, and is on the latest version, which means that mdx itself has not been updates to use this version of remark, which is outside my control. The fix here is to use an older version of remark-math that work correctly. I'd go for the most recent one below `4.0.0`.

**Comment by tuan-m-ng** [comment]
> This repo uses mdx directly, and is on the latest version, which means that mdx itself has not been updates to use this version of remark, which is outside my control. The fix here is to use an older version of remark-math that work correctly. I'd go for the most recent one below `4.0.0`.

👍  The most recent one below `4.0.0` is `3.0.1` and it's working!

**Comment by jescalan** [comment]
Great to hear! Glad you got this working

**Comment by tuan-m-ng** [comment]
👍  Thanks for this very useful library, it's really nice using it with `next-remote-watch`.
