### ISSUE TITLE
Upgrade to latest @mdx-js/mdx version?

### ISSUE THREAD

**Issue by DavieReid** [hashicorp/next-mdx-remote#432]
Hello,

I noticed that `next-mdx-remote` uses  version 2.2.1 of `@mdx-js/mdx` which in turn [uses version 10.0.0 of `unified`](https://github.com/mdx-js/mdx/blob/2.2.1/package.json#L105).

I would like to use the latest version of the `rehype-pretty-code` plugin which requires [version 11 of `unified`](https://rehype-pretty-code.netlify.app/#usage). 

[This issue](https://github.com/hashicorp/next-mdx-remote/issues/431) is also caused by the unified versions.

Would you be open to a contribution that updates `@mdx-js/mdx` and `@mdx-js/react` to their latest versions?

**Comment by DavieReid** [comment]
closing as Dupe of https://github.com/hashicorp/next-mdx-remote/issues/419

**Comment by karlhorky** [comment]
I can confirm that `next-mdx-remote@0.0.0-canary-20240321205249` (canary version from [the v5 PR](https://github.com/hashicorp/next-mdx-remote/pull/448#issuecomment-1995658726)) is compatible with `remark-gfm@4.0.0` 🎉

(in my analysis, this most likely extends to any other plugins such as `rehype-pretty-code` which depend on MDX v3 or newer versions of the Unified dependencies)
