### ISSUE TITLE
Unmaintained? New maintainers?

### ISSUE THREAD

**Issue by karlhorky** [hashicorp/next-mdx-remote#434]
Hi @dstaley and @BRKalow (since you seem like last active maintainers here)

First of all, thanks for `next-mdx-remote` - it is a great project and idea, and would be amazing to have this become a maintained library again!

There are a few areas where the maintenance of the library is currently lacking:

1. Broken types for modern TS module resolution: https://github.com/hashicorp/next-mdx-remote/pull/377
2. MDX v3 (this causes [confusing](https://github.com/hashicorp/next-mdx-remote/issues/431) [incompatibilities](https://github.com/hashicorp/next-mdx-remote/issues/403) with using this library along with other modern plugin packages): https://github.com/hashicorp/next-mdx-remote/pull/433 by @DavieReid and https://github.com/hashicorp/next-mdx-remote/pull/425 by @hipstersmoothie
3. (other updates of dependencies would also be great)
4. CI is currently failing in main branch
5. (other issues and PRs)

There has not been much activity here lately. This leads me to a few questions, in terms of a path forward:

A) Will the last active maintainers @dstaley and @BRKalow return to this project?
B) Is there anyone (outside of the last active maintainers) from HashiCorp which will actively maintain this project?
C) Should maintenance access be given to someone in the community?
D) Should the project be transferred to another organization or singular person?
E) Should the project be marked as "Unmaintained" with a large message in the readme and the repo archived?

CCs:

- From the Next.js / Vercel side: @jescalan 
- From the HashiCorp JavaScript maintainer side: @DhariniJeeva @ZedLi @cameronperera @lisbet-alvarez @dvonanderson
- From the MDX / Unified side: @wooorm

**Comment by talatkuyuk** [comment]
I am on the way to release forked `next-mdx-remote` (actually It stopped being forked and became a brand new package after changes I made), fully re-written as inline with `@mdx-js/mdx` supporting **imports** and **exports** and solving all issues, **I fixed all of them**, but requires breaking changes. I've almost finished, writing tests, and documentation and migration guide.

**Comment by dstaley** [comment]
@karlhorky Thank you so much for asking these questions and summarizing the big opportunities for this library. I've started [a discussion](https://github.com/hashicorp/next-mdx-remote/discussions/437) that outlines HashiCorp's plans for the near future for `next-mdx-remote`, and we can continue the conversation there. Thanks again!

**Comment by karlhorky** [comment]
@dstaley thanks for the reply and the detailed plan forward 🙌 I'm optimistic about the future of the library
