### ISSUE TITLE
Question: Is it possible to use dynamic variables in the componet

### ISSUE THREAD

**Issue by rodbs** [hashicorp/next-mdx-remote#44]
I'm using a component that I'm rendering like in mdx 
` <CompA data={data}/>` 

Right now I need to write this line every time I want to render it.

Instead I'd like to do something like:
` <CompA /> ` 
and it automatically will grab the data. For that in the component definition I've tried several approaches to pass default values
`const CompA = ({data = '{data}') => { ...}` 

but  this is not working  and I'm not sure either if next-mdx-remote allows to parse this kind of components with dynamic variables.
Thanks

**Comment by brianespinosa** [comment]
@rodbs unless I am misunderstanding your question... this is not a limitation of MDX or this library. This is how React works. Unless you set your components up to render inside of a component as children and clone them whereby you would also pass the props of the parent when cloning, this will not work.

It kind of seems like you want to use React Context where you can drop any CompA inside of a Provider and automatically grab that data.

Are either of those scenarios what you are looking for? Have you been able to get your components to do what you want in React by itself without using MDX?

**Comment by rodbs** [comment]
ok, I think I understand what you mean about using the Context.
No, I haven't tried the Component in out of MDX. I thought it  might be possible to defer prop data assignment until next-mdx-remote injected the data. I mean, the data itself is in the mdxScope, my idea was to declare the prop as a default dynamic variable in the component and later the data being injected in the mdx hydration phase. But I see it might not be possible

**Comment by rodbs** [comment]
I've created a React Context to try to get the data from the context into the mdx but I don't get it to work.

I'm not sure if this is related to custom provider you mentioned in this issue:
https://github.com/hashicorp/next-mdx-remote/issues/32

Is it possible now to render a component using next-mdx-remote and have the component get data from a React context? Does the context have to be passed to mdx? how? are there any examples available? Thx

**Comment by jescalan** [comment]
@rodbs There's a PR in progress here to support providers/context - https://github.com/hashicorp/next-mdx-remote/pull/35

**Comment by jescalan** [comment]
Closing as there's already an issue and PR addressing provider support.
