### ISSUE TITLE
Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by chetanpan** [hashicorp/next-mdx-remote#456]
### Describe the bug

If I try to render simple mdx string on page with `compileMDX` from `next-mdx-remote/rsc`, it renders correctly, and also issues "Error: Hydration failed because the initial UI does not match what was rendered on the server."

![image](https://github.com/hashicorp/next-mdx-remote/assets/211534/b445c1a1-6f11-4302-9112-ad4780cb4bd0)

### Reproduction

https://codesandbox.io/p/devbox/testing-mdx-with-math-2dv2y3

### next-mdx-remote version

v4.4.1

**Comment by chetanpan** [comment]
@dstaley Here is new issue. 

Just to reiterate, I have tried with Incognito and Firefox private tab as well. I got same error. I switched back to stable version of next-mdx-remote, but I got same error with canary as well. I also get same error in your forked reproduction. Same error for me, though you mentioned you did not get it.

From the error, it have to do something with `<MDXContent>`. 

Can you please try with `<>{result.content}</>` instead of `<div>{result.content}</div>`? for me, using `<></>` removes hydration error, but produces errro in console about extra attribute in html.

**Comment by dstaley** [comment]
Thank you for the reproduction. I've been able to reproduce this issue (albeit intermittently; it only happens after refreshing several times). Since this isn't something that I can reliably reproduce it will likely take some time to figure out what the issue is.

**Comment by dstaley** [comment]
@chetanpan Actually, can you confirm whether you experience this issue when running the code _outside_ of CodeSandbox? Running it locally, I'm unable to reproduce even after dozens of refreshes.

**Comment by chetanpan** [comment]
@dstaley Yeah, you are right. Local works fine. That means, this error was doing of sandbox. I tried with stackblitz, and it worked fine. 

Meanwhile, canary solve my problem with remark-gfm as well, thanks for suggesting that. Request you to release this canary asap as anybody using mdx, good chance, they will be using remark-gfm, too.

Thanks!👍
