### ISSUE TITLE
Question: How to pass mdxcomponents to render the custom coponents.

### ISSUE THREAD

**Issue by imumesh18** [hashicorp/next-mdx-remote#46]
Hey,

I started moving my blog from nextjs-mdx-enchanced to this library. I followed the steps, but for some reasons the page is not getting render properly. Aparently the componets theme is not getting applied. So on mdx-enhanced, I used to pass my MDXCompontents to MDXProvider and it used to wrap my blog's body. Now I am passing the mdxcoponent to the renderToString() and hydrate. Any help would be appreciated, I might be doing something wrong here if any one can help.

**Comment by gr-qft** [comment]
Check out this example: https://github.com/vercel/next.js/tree/canary/examples/with-mdx-remote
