### ISSUE TITLE
Not a bug, but help needed

### ISSUE THREAD

**Issue by G0rav** [hashicorp/next-mdx-remote#466]
### Describe the bug

![image](https://github.com/hashicorp/next-mdx-remote/assets/130744046/c93b4d62-abae-49af-afba-8c61a2e64d24)

Even though the package is working fine and converting mdx to html tags, why doesn't it render the default css associated with them?

I am using it in next js app with tailwind configured.

I know it is not associated with this package but am stuck here.

### Reproduction

NA

### next-mdx-remote version

v5.0.0

**Comment by talatkuyuk** [comment]
It is not related with `next-mdx-remote` as you say. **`next-mdx-remote` does not touch any styling or plugin behaviours.** You can ask your question at **stackoverflow** with more explanation, and showing source files (tailwind, mdx options, mdx document etc.).

**Comment by lenguyen1807** [comment]
Maybe you can use [tailwindcss-typography](https://github.com/tailwindlabs/tailwindcss-typography). After you install it, just wrap the `article` to `MDXRemote` and add `className="prose"`. It should look like this:

```ts
<article className="prose">
  <MDXRemote ... />
</article>
```

**Comment by G0rav** [comment]
I've fixed it, Thanks
