### ISSUE TITLE
Question: Page flashing

### ISSUE THREAD

**Issue by gr-qft** [hashicorp/next-mdx-remote#47]
This package together with `next-remote-watch` are great for writing mdx documents. However, recently I'm seeing the documents take a noticeable time interval to refresh, and there's a white flashing in between. A couple of weeks ago I didn't notice these problems. 

Could anything be done? 

P.S. Also, after a page refreshes it always starts from the top and it's a bit tedious for me to have to scroll to the place where I was before. Is there a way to solve this as well? 

Thanks!

**Comment by jescalan** [comment]
I don't think so. It's not a "fast refresh" on these pages, it a full manual refresh. `next-remote-watch` is essentially a hack that proxies through next's dev watcher with a fs watcher to watch paths you specify and hit the next dev server with a manual reload command. It's not super reliable, sometimes two saves are needed, but it's about as much as I can do without changing the way nextjs works.

You're very welcome to see if there's anywhere you can contribute or improve it though!

**Comment by gr-qft** [comment]
@jescalan Thanks for the info! It's not perfect, but the writing experience has improved significantly compared to having to click refresh manually. 

I'm still at the level of a user but as I become more familiar with this package I'll try to dig in deeper.
