### ISSUE TITLE
Question: how do I render index.mdx as / instead of /index?

### ISSUE THREAD

**Issue by edmundojr** [hashicorp/next-mdx-remote#49]
First thanks for this awesome library, it checks all the boxes for creating documentation using Next.js and MDX.

I was wondering if there's anyway to render my `/content/index.mdx` as `/` instead of `/index`?

My setup is pretty much the same as the [example/blog](https://github.com/hashicorp/next-mdx-remote/tree/master/examples/blog), but my `[slug].js` file lives inside `pages/`:

- `content/`
  - `index.mdx`
  - all others `.mdx` files
- `pages/`
  - `index.jsx`
  - `[slug].js`

I don't have the slight idea of where to look to change this.

Any help much appreciated, thanks!

**Comment by jescalan** [comment]
I might shift to using an [optional catchall route](https://nextjs.org/docs/routing/dynamic-routes#optional-catch-all-routes) for this one.

**Comment by edmundojr** [comment]
Thanks for sharing this @jescalan, for some reason that didn't work for me, but some of the examples inspired me to fix it in this way:

My structure:
```
content/
├── index.mdx
├── another-page.mdx
pages/
├── index.jsx
├── [slug].jsx
```

My `index.jsx` now is only:
```jsx
export { default, getStaticProps } from './[slug]';
```

And I introduced a change in the `getStaticProps` in `[slug].jsx`, so if the params are undefined (they are on root), I load `index` as the post slug instead:
```jsx
export async function getStaticProps({ params }) {
  const getSlug = params ? params.slug : 'index';
  const postContent = await getPostdata(getSlug);
  // … the rest of the function is pretty much the same as below:
  // https://github.com/hashicorp/next-mdx-remote/blob/master/examples/blog/pages/blog/%5Bslug%5D.jsx#L28-L36
}
```

Now the `/` loads correctly with `index.mdx` content. Hope this helps anyone searching for it.
