### ISSUE TITLE
Question: Possible to return the contents as an array of elements?

### ISSUE THREAD

**Issue by SimeonGriggs** [hashicorp/next-mdx-remote#53]
I was originally using the [MDX library with Next,](https://mdxjs.com/getting-started/next) until I wanted to use `getStaticProps`, which this package lets me do.

However, before I was able to map over the content nodes before to generate my own custom Table of Contents, something I'm not able to do here.

Is there a way to transform the content into an array of nodes, instead of _just_ the compiled string of HTML? Ideally I want to pull out and create an array of all H2 + H3 elements ... without regex-ing them myself

**Comment by jescalan** [comment]
You'd want to use a remark plugin to do this, which can be passed in through the `mdxOptions` argument, I think!

**Comment by SimeonGriggs** [comment]
Yeah I have tried that and had no luck getting it to work :/

```
const source = await renderToString(content, {
    components,
    mdxOptions: {
      remarkPlugins: [require('remark-toc')],
    },
    scope: {},
  })
```

...though I may be doing something wrong here?

**Comment by brianespinosa** [comment]
@SimeonGriggs it is hard to say. We don't know what your MDX file looks like that you are trying to process with [remark-toc](https://github.com/remarkjs/remark-toc). It does appear that you are declaring the plugin correctly in your `remarkPlugins` array. In my project I actually do an import and then add the imported member to the array.

**Comment by SimeonGriggs** [comment]
Got it. I think this plugin will insert the TOC at the top of the document, where I actually want to render it in a sidebar.

Looks like I might be regex-ing the content myself...

**Comment by brianespinosa** [comment]
Possibly... but I would take a deeper look at [other Remark plugins out there](https://unifiedjs.com/explore/topic/remark-plugin/). You may find one that gets you what you need. There may be others that you can control the AST output and wrap the TOC in your own markup and classes which you could then position where you want.

**Comment by jescalan** [comment]
Yep - you also could write your own remark plugin - their plugin API is quite accessible! It's worth considering that you could also run remark separately outside of mdx remote within getStaticProps - its two remark passes which is not ideal, but if it's running at build time you don't incur client-side performance cost.

Closing this issue since the question has been addressed but please feel free to continue discussion here!

**Comment by SimeonGriggs** [comment]
Solved it using the `remark/slug` plugin to add links to the headers in the processed HTML, and yes running a regex over the `content` retrieved from `matter()` to extract the headings and modify that into an array of links.

And yeah I'm doing this in `getStaticProps` so it should only impact build, not page load.

...if anyone is interested:

```
const slugify = require('slugify')

export function getTableOfContents(content) {
  const regexp = new RegExp(/^(### |## )(.*)\n/, 'gm')
  const headings = [...content.matchAll(regexp)]

  let tableOfContents = []

  if (headings.length) {
    tableOfContents = headings.map((heading) => {
      const headingText = heading[2].trim()
      const headingType = heading[1].trim() === '##' ? 'h2' : 'h3'
      const headingLink = slugify(headingText, { lower: true, strict: true })

      return {
        title: headingType === 'h2' ? headingText : `- ${headingText}`,
        link: `#${headingLink}`,
      }
    })
  }

  return tableOfContents
}
```

**Comment by JHSeo-git** [comment]
@SimeonGriggs Try this.

```js
  const mdxSource = await renderToString(content, {
    mdxOptions: {
      rehypePlugins: [
        require('rehype-slug'),
        require('rehype-autolink-headings'),
        require('rehype-toc'),
      ],
    },
  });
```

![rehype1](https://user-images.githubusercontent.com/61136724/104119495-07139380-5373-11eb-9d81-33e87bf3028f.png)

![rehype2](https://user-images.githubusercontent.com/61136724/104119504-15fa4600-5373-11eb-85dc-75970dc30e6a.png)


 I hope it helps you.

**Comment by rizkimcitra** [comment]
> @SimeonGriggs Try this.
> 
> ```js
>   const mdxSource = await renderToString(content, {
>     mdxOptions: {
>       rehypePlugins: [
>         require('rehype-slug'),
>         require('rehype-autolink-headings'),
>         require('rehype-toc'),
>       ],
>     },
>   });
> ```
> 
> ![rehype1](https://user-images.githubusercontent.com/61136724/104119495-07139380-5373-11eb-9d81-33e87bf3028f.png)
> 
> ![rehype2](https://user-images.githubusercontent.com/61136724/104119504-15fa4600-5373-11eb-85dc-75970dc30e6a.png)
> 
> I hope it helps you.

Sorry but where does the `renderToString` come from?

**Comment by JHSeo-git** [comment]
> > @SimeonGriggs Try this.
> > ```js
> >   const mdxSource = await renderToString(content, {
> >     mdxOptions: {
> >       rehypePlugins: [
> >         require('rehype-slug'),
> >         require('rehype-autolink-headings'),
> >         require('rehype-toc'),
> >       ],
> >     },
> >   });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![rehype1](https://user-images.githubusercontent.com/61136724/104119495-07139380-5373-11eb-9d81-33e87bf3028f.png)
> > ![rehype2](https://user-images.githubusercontent.com/61136724/104119504-15fa4600-5373-11eb-85dc-75970dc30e6a.png)
> > I hope it helps you.
> 
> Sorry but where does the `renderToString` come from?

In v2, serialize is renderToString.

Please check migrate v2 to v3 docs.
https://github.com/hashicorp/next-mdx-remote/releases/tag/3.0.0
