### ISSUE TITLE
ReferenceError: MDXContent is not defined

### ISSUE THREAD

**Issue by geniuscd** [hashicorp/next-mdx-remote#55]
Hello, Thank you for you hard work :) great plugin !
I'm getting the following

```
Unhandled Runtime Error
ReferenceError: MDXContent is not defined

Call Stack
   eval
node_modules\next-mdx-remote\hydrate.js (46:11)

<unknown>
   /_next/static/chunks/pages/next.js (116720:8)
```

below is my code, the one in the example file
### slide.jsx
```
import renderToString from 'next-mdx-remote/render-to-string'
import hydrate from 'next-mdx-remote/hydrate'

export default function Slide({ source }) {
    const content = hydrate(source)
    return <div className="wrapper">{content}</div>
}

export async function getStaticProps() {
    // MDX text - can be from a local file, database, anywhere
    const source = 'Some **mdx** text, with a component'
    const mdxSource = await renderToString(source)
    return { props: { source: mdxSource } }
}
```
### Page.jsx
```
...
const Next = () => {
     const classes = useStyles({});
     return (
      <React.Fragment>
       <Head>
        <title>Home - Nextron (with-javascript-material-ui)</title>
      </Head>
      <div className={classes.root}>
        <Slide source={"## testing"} />
      </div>
    </React.Fragment>
  );
};

export default Next;
```

Am i missing something?
I'm trying to load a local mdx file using `fs` and display it

**Comment by jescalan** [comment]
Yeah you need to be running `getStaticProps` in your page file, not sure what's going on with `slide.jsx`?

**Comment by geniuscd** [comment]
Thank you for your reply :D
I made some tests and added `slide.jsx` inside the `pages` folder instead of an imported component. It worked, but i don't want that behavior. (slide.jsx is the [example file](https://github.com/hashicorp/next-mdx-remote#example-usage), nothing fancy)
I'm working with the electron framework for now and i'm trying to build a kind of software where you have a list of mdx files and once you press on one row, a new window will open and displays the MDX.
With your plugin its looking very neat! nice work :D

But sometime i have to read another file and refresh the view instead of reloading it.
That why i though of making it as a component, but its not working.

**Comment by geniuscd** [comment]
never found a solution

**Comment by jescalan** [comment]
If you make a minimal reproduction of your specific issue, I'd be happy to take a look

**Comment by PatrickHeneise** [comment]
`getStaticProps` only works on pages, not components: https://nextjs.org/docs/basic-features/data-fetching#only-allowed-in-a-page-1

you can export a regular function and load it on the page:

```
import {pageProps} from 'components/Docs'

export async function getStaticProps(ctx) {
  return {
    props: {
      ...(await pageProps(ctx))
    }
  }
}
```

**Comment by nevir** [comment]
For anyone else stumbling across this issue, you'll get this error any time `MDXRemote` is called without `compiledSource` (aka the `source` property that's being `...`'d is most likely undefined)
