### ISSUE TITLE
Question: using export in mdx

### ISSUE THREAD

**Issue by LydiaF** [hashicorp/next-mdx-remote#58]
Hi there,

Thank you so much to all the maintainers for such a great library. I have a question about defining components within the mdx. I have read the caveat about not importing components within the mdx but that seems like a different issue (I apologise if it isn't!)

I am wondering if this is just something that probably won't work ever given the constraints of the package, or if there is something I can do.

Thank you so much,

Lydia

```js
import renderToString from 'next-mdx-remote/render-to-string'
import hydrate from 'next-mdx-remote/hydrate'

const source = `
# Test

export const FancyButton = ({ text = "Press" }) => {
  return (
    <button onClick={() => console.log}>{text}</button>
  )
}

<FancyButton text="Press me" />
`

export default function TestPage({ source }) {
  const content = hydrate(source)

  return <div>{content}</div>
}

export async function getStaticProps() {
  const mdxSource = await renderToString(source)

  return { props: { source: mdxSource } }
}
```

![image](https://user-images.githubusercontent.com/10000865/99190703-148c1300-2760-11eb-82ad-7ca0b954a69f.png)

**Comment by jescalan** [comment]
This is some crazy mdx! I think this utilizes the layout features in a way that this library wasn't designed to handle. There is a PR being worked on that I think may remove that limitation, but for now I don't exactly have the bandwidth to look into this further or support this manner of usage. I'm sure you know this already and have a reason for not doing it, but you could just pass that component in under the `components` argument and it should work fine.

**Comment by LydiaF** [comment]
☺️☺️🙃 Yes... you're right! I am wondering how far I can push it.. Wondering if I can make interactive content on the fly from within a cms. It's no problem, I can work around it as you suggested.

Thank you for replying so quickly and for all your work with this package :)

**Comment by Ehesp** [comment]
@jescalan just tried that PR with a custom in-page exported component & it throws the following error:

```
SyntaxError: Unexpected token export
    at Function (<anonymous>)
    at MdxRemote (.../node_modules/next-mdx-remote/mdx-remote.js:12:31)
```

**Comment by jescalan** [comment]
@Ehesp could you mention that on the PR rather than this issue?
