### ISSUE TITLE
There's no rehydration after client page transition

### ISSUE THREAD

**Issue by fillipvt** [hashicorp/next-mdx-remote#6]
Hello!

I'm loving the library's concept, I really really like it! 

For context I'm trying to create a small presentation. This is my `[slide].jsx` component:

```
// pages/[slide].jsx

import { join } from 'path';
import fs from 'fs';
import renderToString from 'next-mdx-remote/render-to-string';
import hydrate from 'next-mdx-remote/hydrate';
import matter from 'gray-matter';

import Intro from '../components/Intro';

const postsDirectory = join(process.cwd(), '/components/slides/');

function getFileNames() {
  return fs.readdirSync(postsDirectory);
}

function getSlug(slug) {
  const initialSlug = slug.replace(/\.mdx$/, '');
  const cleanSlug = initialSlug.replace(/slide-/, '');

  return cleanSlug;
}

function getSlidesSlugs() {
  const fileNames = getFileNames();
  const slugs = fileNames.map((fileName) => getSlug(fileName));
  const filteredSlugs = slugs.slice(1);
  // sort posts by date in descending order
  return filteredSlugs;
}

const components = { Intro };

const Slide = ({ mdxSource, frontMatter }) => {
  const content = hydrate(mdxSource, components);
  console.log({ mdxSource, content });

  return (
    <div>
      <h1 className="text-white">{frontMatter.title}</h1>
      {content}
    </div>
  );
};

export async function getStaticProps({ params }) {
  const fullPath = join(postsDirectory, `slide-${params.slide}.mdx`);
  const fileContents = fs.readFileSync(fullPath, 'utf8');
  const { content, data } = matter(fileContents);
  const mdxSource = await renderToString(content, components);
  return { props: { mdxSource, frontMatter: data } };
}

export async function getStaticPaths() {
  const slugs = getSlidesSlugs();
  return {
    paths: slugs.map((slug) => {
      return {
        params: {
          slide: slug.toString(),
        },
      };
    }),
    fallback: false,
  };
}

export default Slide;

```

As you can see in the `Slide` function component definition, I'm console logging both `mdxSource` and `content`.

This is the result from the console.

- There are 3 renders:

<img width="1655" alt="Screen Shot 2020-05-25 at 12 42 10 AM" src="https://user-images.githubusercontent.com/16828078/82782069-10221580-9e21-11ea-829e-71ecd7991552.png">

- The first and second  render show both values correctly:

<img width="1655" alt="Screen Shot 2020-05-25 at 12 42 16 AM" src="https://user-images.githubusercontent.com/16828078/82782100-24fea900-9e21-11ea-8eb5-20251523ea60.png">

- But the third doesn't have the props for `content` as initially:

<img width="1655" alt="Screen Shot 2020-05-25 at 12 44 09 AM" src="https://user-images.githubusercontent.com/16828078/82782119-3051d480-9e21-11ea-8170-9a8ba6062092.png">

Then finally when I click on a `<Link/>` to go to the next slide this happens (this is a gif, give it a couple of seconds, forgot to remove the initial idle time 😄):

![Screen Recording 2020-05-25 at 12 47 26 AM](https://user-images.githubusercontent.com/16828078/82782531-2a102800-9e22-11ea-97d5-cef1ad95f2fa.gif)

The gif shows:

- On the device top left corner you can see a slide counter which increases from 3 to 4 when the <Link/> click is pressed, this signals the page transition (this is from the `frontMatter` prop)
- But the actual content does not change
- `mdxSource` did update correctly as it's showing a different piece of content on console, this also comes as a prop from `getStaticProps` -- so I think there's no problem there
- But `content`, calculated with `hydrate`, lost its props (as seen in the `console.log`), and so my guess is this is why the content did not update correctly on client page transition.

Am I using the library correctly? Not sure if this is outside of the current scope or if I should be using it differently.

As a note I'd like to point out the problem disappears if instead of using a `<Link/>` component I simply use an `<a/>` tag for the slide transitions. But with the `<Link/>` component there's quite a few good things that happen, so it would be really great if `next-mdx-remote` would work the `<Link/>` component.

I'll share the full repo as soon as I can, but this is the best I can do for now.

Any guidance would be highly appreciated! Thanks in advance

**Comment by dave-stevens-net** [comment]
I'm having the exact same issue. I can't seem to get the client to refresh the MDX content after a page transition. It seems that the memoized value returned by hydrate keeps returning the same page content even though the mdxSource being passed in is different.

**Comment by grncdr** [comment]
I've also had the same issue. I ended up copying and rewriting the `hydrate` function in my own code to work around it.

When I realized that `hydrate` is using hooks under the hook, I decided to treat it as a component. So my code looks like `<HydratedMDX serialized={data.serialized_mdx} components={MyMDXComponents}/>`

```ts
import React from 'react'
import { mdx } from '@mdx-js/react'
import { MDXComponents } from '../components/mdx'

interface SerializedMDX {
  source: string
  renderedOutput: string
}

interface Props {
  serialized: SerializedMDX
  components: object
}
  
function HydratedMDX({serialized: { source, renderedOutput }, components}: Props) {
  // our default result is the server-rendered output
  // we get this in front of users as quickly as possible
  const [result, setResult] = React.useState(
    React.createElement('span', {
      dangerouslySetInnerHTML: {
        __html: renderedOutput,
      },
    }),
  )

  React.useEffect(() => {
    setResult(
      React.createElement('span', {
        dangerouslySetInnerHTML: {
          __html: renderedOutput,
        },
      }),
    )
  }, [renderedOutput])

  React.useEffect(() => {
    // if we're on the client side and have not yet hydrated, we hydrate
    // the mdx content inside requestIdleCallback, since we can be fairly
    // confident that markdown-embedded components are not a high priority
    // to get to interactive compared to... anything else on the page.
    //
    // once the hydration is complete, we update the state/memo value and
    // react re-renders for us.
    window.requestIdleCallback(() => {
      // first we set up the scope which has to include the mdx custom
      // create element function as well as any components we're using
      const scope = { mdx, ...components }
      const keys = Object.keys(scope)
      const values = Object.values(scope)

      // now we eval the source code using a function constructor
      // in order for this to work we need to have React, the mdx createElement,
      // and all our components in scope for the function, which is the case here
      // we pass the names (via keys) in as the function's args, and execute the
      // function with the actual values.
      const hydratedFn = new Function(
        'React',
        ...keys,
        `${source}
        return React.createElement(MDXContent, {});`,
      )(React, ...values)

      // set the output as the new result
      setResult(hydratedFn)
    })
  }, [source])

  return result
}
```

**Comment by fillipvt** [comment]
That works perfectly @grncdr ! 👍 

Would it be okay if I make a PR with this one? The added `useEffect` was indeed the missing piece!

**Comment by grncdr** [comment]
I didn't make a PR because my code changes the API a and would require updates to the documentation as well, but It's fine with me if you want to do it. :+1:

**Comment by dave-stevens-net** [comment]
Great work Stephen (@grncdr). Thanks for sharing. Your component worked flawlessly for me.

**Comment by jescalan** [comment]
Hi everyone I'm sorry I am just seeing this, I was out for parental leave for a bit. Thanks for all the investigation and thorough explanation. Would love to get a PR with these changes if some of you have already made them! Thanks so much 💖

**Comment by jescalan** [comment]
Just a heads up we are tackling this directly now and should have this issue closed out shortly!

**Comment by jescalan** [comment]
Addressed by #15 which should ship today

**Comment by dave-stevens-net** [comment]
I upgraded to vs. 0.6.0 and switched back to using the `hydrate` function. Works great @jescalan. Thanks for fixing this and thank you for your work on `next-mdx-remote`. Much appreciated.

**Comment by jescalan** [comment]
@dave-stevens-net you're welcome, thanks so much for the nice note! 💖

**Comment by fillipvt** [comment]
Thank you very much for this @jescalan !
