### ISSUE TITLE
Additional Markdown in Components?

### ISSUE THREAD

**Issue by PatrickHeneise** [hashicorp/next-mdx-remote#60]
I'm trying to render additional Markdown/MDX within a Component:

_markdown.mdx_:

    # Hello World
    
    <Block>
    ```js
    const x = 'hello world';
    ```
    </Block>

_index.jsx_:

```js
import renderToString from 'next-mdx-remote/render-to-string'
import hydrate from 'next-mdx-remote/hydrate'
import Block from 'components/Block'

export default function Home({mdxSource}) {
   const content = hydrate(mdxSource, {
    components: {Block: Block}
   }

  return <div className="prose">{content}</div>
}

export async function getStaticProps({ params }) {
  const mdxSource = await renderToString(content, { components: { Block:Block }}
...
})
```

_Block.jsx_:
```
export default function Block({children}) {
  return <>{children}</>
}
```

**Comment by jescalan** [comment]
You would need your component to process its children as markdown. MDX does not process component children as markdown by default.

**Comment by Rigel772** [comment]
When using this pattern I am getting in the console:
`Component Block was not imported, exported, or provided by MDXProvider as global scope`

Is it ok? Expected?

**Comment by Rigel772** [comment]
...also when I insert such <Block> into a block of text:
```md
Cras vehicula, nisl vel ultricies gravida, augue nibh laoreet arcu, et tincidunt augue dui non elit. Vestibulum 
semper posuere magna, quis molestie mauris faucibus ut.Cras vehicula, nisl vel ultricies gravida, augue 
nibh laoreet arcu, et tincidunt augue dui non elit. Vestibulum semper posuere magna,
<Block> Text in Block</Block>
 quis molestie mauris faucibus ut.Cras vehicula, nisl vel ultricies gravida, augue nibh laoreet arcu, et 
tincidunt augue dui non elit. Vestibulum semper posuere magna, quis molestie mauris faucibus ut.
```
The part of text before `<Block>`  is rendered with `<p>`  tag and the lower part with no html tag at all...

Is there better way to split text into sections with different formatting?

**Comment by Rigel772** [comment]
`Component Block was not imported, exported, or provided by MDXProvider as global scope`

Please ignore this, my mistake.
