### ISSUE TITLE
Elaborate on renderToString without hydration in readme

### ISSUE THREAD

**Issue by lostfictions** [hashicorp/next-mdx-remote#61]
Hey there, thanks so much for writing this library! I've long been frustrated with the limitations of using MDX with Next, so I'm really glad to discover that someone else also thought there must be a better way (and had the capacity to act on it :) !)

Currently the readme ends on a somewhat ambiguous note:

> It's also worth noting that you do not have to use hydrate on the client side, but without it, you will get a server-rendered result, meaning no ability to react to user input, etc.

To clarify, does this mean the output of `renderToString` can be passed directly to `dangerouslySetInnerHTML`? For my part there are plenty of use-cases where I'd like the componentization provided by MDX for components that are non-interactive (eg. simple layout elements), and I can't imagine I'm alone in this...

**Comment by lostfictions** [comment]
Answering my own question: currently `renderToString` returns an object with shape `{ compiledSource, renderedOutput, scope }`, of which `renderedOutput` can be directly passed to `dangerouslySetInnerHTML`.

I'd be happy to make a PR clarifying this in the readme, but from glancing at open PRs it looks like the API might be changing soon -- should I hold off?

**Comment by jescalan** [comment]
Good digging, that's correct! Would be happy to accept a PR with a note about this in the readme, thank you!
