### ISSUE TITLE
Spread syntax on hydrate function breaks on Safari 11

### ISSUE THREAD

**Issue by valse** [hashicorp/next-mdx-remote#63]
Hi, I'm switched from a custom made mdx parser to your solution and it's very useful thanks!

However I notice that my site breaks on safari 11 because in the `hydrate` function you're using the spread syntax and I have this console error: `Unexpected token '...'. Expected a property name`.

I can't understand why this isn't transpiled by babel :\

**Comment by jescalan** [comment]
You'd have to use `next-transpile-modules` to have babel transpile it. I'd welcome a PR to remove the synax though!

**Comment by valse** [comment]
Hi @jescalan thanks for your help and it works now... I hope to return the favor with a new PR soon!
