### ISSUE TITLE
Is there a way to not use components which is not being used by a certain page?

### ISSUE THREAD

**Issue by melvin2016** [hashicorp/next-mdx-remote#68]
I have a blog page where I read MDX files and some components and if I add components to `hydrate()` function. 

Will this be added with every page even if I'm not using that specific component?

**Comment by PolMrt** [comment]
Take a look at https://github.com/vercel/next.js/tree/canary/examples/with-mdx-remote#notes, they explain how to import components only when needed :)

**Comment by melvin2016** [comment]
Thanks @PolMrt
