### ISSUE TITLE
requestIdleCallback crashes safari

### ISSUE THREAD

**Issue by bogdansoare** [hashicorp/next-mdx-remote#7]
`requestIdleCallback` is [not available in Safari ](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback#Browser_compatibility) so when trying to use [`hydrate`](https://github.com/hashicorp/next-mdx-remote/blob/master/hydrate.js#L26) it crashes the app.

We can add a [simple shim](https://developers.google.com/web/updates/2015/08/using-requestidlecallback#checking_for_requestidlecallback) if `requestIdleCallback` is not available. 

Should I submit a PR with the fix?

**Comment by jescalan** [comment]
Good call - this was on my radar and the shim you mentioned I think is the right direction. If you'd like to contribute this, I would be thrilled!

**Comment by bogdansoare** [comment]
Happy to hear that, just raised a PR.
