### ISSUE TITLE
Using renderToString in client side code

### ISSUE THREAD

**Issue by pbteja1998** [hashicorp/next-mdx-remote#73]
Hi
I wanted to know if there is a way to use `renderToString` in the client. 

I have the following use-case.
1. User starts writing a new blog post
1. The MDX content of the blog post is stored in local storage
1. Now, I want to show a preview of how this content will look like when rendered.

Since the only way to access local storage is in the client, is there a way to convert MDX to JSX in the client?

Thanks in advance.

**Comment by jescalan** [comment]
There is no way to use `renderToString` on the client. It is a server-only method. For what you're trying to do, I'd reach for this package: https://mdxjs.com/advanced/runtime

**Comment by pbteja1998** [comment]
Thanks for the response. I completely forgot about API routes that are present in Next.js. I created an API route and passed the markdown content as a param to it. Then I rendered the fetched output without using hydrate. 

Code snippets for anyone who also want to do the same thing.
```ts
// api/mdx.ts
const mdxHandler: NextApiHandler = async (
  req: NextApiRequest,
  res: NextApiResponse
) => {
  const content = req.body.content
  const mdxSource = await renderToString(content, {
    components: MDXComponents,
    mdxOptions: {
      remarkPlugins: [],
      rehypePlugins: [],
    },
    scope: {},
  })
  res.json({ mdxSource })
}

export default mdxHandler
```


```tsx
// pages/preview.tsx

async function fetchMDX(value: string) {
  const res = await fetch('/api/mdx', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ content: value }),
  })
  return res.json()
}

export default function PreviewNewPage({markdownValue}) {
    const { isLoading, error, data } = useQuery(['/api/mdx', 'new'], () =>fetchMDX(markdownValue))
    if (error) {
        console.log('something went wrong!!!')
    }
    return (
        <>
            {isLoading ? (
              <p>loading...</p>
            ) : (
              <div dangerouslySetInnerHTML={{ __html: data.mdxSource.renderedOutput }} />
            )}
        </>
    )
}
```

**Comment by pbteja1998** [comment]
@jescalan `hydrate` is throwing error when I used the above way. It might be because `data` is undefined until the query is complete. Is there a way to pass dummy value to `hydrate` until the query is complete? I tried passing `{ compiledSource: "", renderedOutput: "", scope {} }`, but it did not work. Do you have any inputs related to this?

I am asking this because, when rendered using `dangerouslySetInnerHTML`, custom components are not getting rendered for some reason. I don't know if it is becuase of `dangerouslySetInnerHTML` or if it is because of passing components in /api/ route.

**Comment by jescalan** [comment]
Just don't run hydrate until it's complete 😀

**Comment by pbteja1998** [comment]
> Just don't run hydrate until it's complete 😀

@jescalan I tried to run hydrate conditionally, but seems like it is a hook. I am getting "fewer hooks than expected" error.

**Comment by jescalan** [comment]
if you're doing your data fetch inside a useEffect, put the hydrate in there too in the promise where the data is returned

**Comment by pbteja1998** [comment]
> if you're doing your data fetch inside a useEffect, put the hydrate in there too in the promise where the data is returned

I am using react-query and I did something similar.

```
const { isLoading, error, data } = useQuery(['/api/mdx', 'new'], () =>
    fetchMDX(value, meta.summary)
  )
  const [content, setContent] = useState('')

  useEffect(() => {
    if (!error && !isLoading && data) {
      const content = hydrate(data.mdxSource, { components: {} })
      setContent(content)
    }
  }, [error, isLoading, data])
```

And i get this error.
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```
<img width="722" alt="Screenshot 2020-12-17 at 3 22 51 AM" src="https://user-images.githubusercontent.com/17903466/102410906-36a2da80-4017-11eb-9bca-35429005d345.png">

**Comment by jescalan** [comment]
```js
const { isLoading, error, data } = useQuery(['/api/mdx', 'new'], () =>
    fetchMDX(value, meta.summary)
  )
  const [content, setContent] = useState('')

  useEffect(() => {
    setContent((!error && !isLoading && data) ? hydrate(data.mdxSource, { components: {} }) : '')
  }, [error, isLoading, data])
```

**Comment by pbteja1998** [comment]
> ```js
> const { isLoading, error, data } = useQuery(['/api/mdx', 'new'], () =>
>     fetchMDX(value, meta.summary)
>   )
>   const [content, setContent] = useState('')
> 
>   useEffect(() => {
>     setContent((!error && !isLoading && data) ? hydrate(data.mdxSource, { components: {} }) : '')
>   }, [error, isLoading, data])
> ```

@jescalan I tried this. Still getting the same error. It might be because we are calling the custom hook(hydrate) conditionally?

**Comment by jescalan** [comment]
Yeah, it also might be because hydrate uses `useEffect` internally...

**Comment by pbteja1998** [comment]
> Yeah, it also might be because hydrate uses `useEffect` internally...

Oh... If `hydrate` is using `useEffect` internally, that makes `hydrate` a custom hook. So I don't think we can call it conditionally then.

**Comment by jescalan** [comment]
So yeah, I think passing dummy content as you originally thought is probably the way to go. You can maybe pass "loading" to `renderToString`, copy that output, set it as the dummy input?

**Comment by pbteja1998** [comment]
> So yeah, I think passing dummy content as you originally thought is probably the way to go. You can maybe pass "loading" to `renderToString`, copy that output, set it as the dummy input?

Good idea. Trying this now.

**Comment by pbteja1998** [comment]
Can't believe this actually worked. Thanks a lot 🙏 @jescalan for taking the time to help me and resolve this. Really appreciate a lot.

---

For anyone who come across this, this is what I passed as a dummy content until I got the actual content.
```js
export const DUMMY_CONTENT = {
  compiledSource:
    '"use strict";\n\nfunction _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }\n\nfunction _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = _objectWithoutPropertiesLoose(source, excluded); var key, i; if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; }\n\nfunction _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }\n\n/* @jsxRuntime classic */\n\n/* @jsx mdx */\nvar layoutProps = {};\nvar MDXLayout = "wrapper";\n\nfunction MDXContent(_ref) {\n  var components = _ref.components,\n      props = _objectWithoutProperties(_ref, ["components"]);\n\n  return mdx(MDXLayout, _extends({}, layoutProps, props, {\n    components: components,\n    mdxType: "MDXLayout"\n  }), mdx("p", null, "loading..."));\n}\n\n;\nMDXContent.isMDXComponent = true;',
  renderedOutput: '<p>loading...</p>',
  scope: {},
}
```

Any I called the hydrate in the following way.
```js
const content = hydrate(data?.mdxSource ?? DUMMY_CONTENT, {
    components: MDXComponents,
  })
```

This will show `loading...` until the actual content is fetched.

---

Thanks @jescalan again for your help.

**Comment by jescalan** [comment]
🎉 so glad you got it working!

**Comment by pbteja1998** [comment]
@jescalan Maybe this should be added as an example in README for showing how this package can be used client-side. If you are up for it, I will open a PR with the details soon. What do you think?

**Comment by jescalan** [comment]
I don't really recommend this package be used client side, to be quite honest, so I'm not sure I'd want to encourage this. What is your use case?

**Comment by pbteja1998** [comment]
> I don't really recommend this package be used client side, to be quite honest, so I'm not sure I'd want to encourage this. What is your use case?

Yeah, makes sense. There aren't any usecases that I can think of too.

**Comment by jescalan** [comment]
You had some use case you are working on here though, right? What were you using it for in this instance - previewing written content for authors?

**Comment by pbteja1998** [comment]
> You had some use case you are working on here though, right? What were you using it for in this instance - previewing written content for authors?

Yes. See the first comment in this issue for the use case. 

I have a editor where user writes mdx content. That content will be synced to local storage as and when the user types it. Then I wanted to show the preview of the mdx that they write. Since the editor content is in local storage, the only way for me to show preview is by doing it client side.

**Comment by jescalan** [comment]
Definitely makes sense - I feel like this is a great case for like, an article or blog post honestly!

**Comment by pbteja1998** [comment]
> Definitely makes sense - I feel like this is a great case for like, an article or blog post honestly!

I am already in the process of making a blog post with the things I learnt and the problems I faced while setting up MDX and also using `next-mdx-remote`.

**Comment by jescalan** [comment]
Amazing - I'd be happy to help, review, etc if that would be useful to you at all. Let me know!

**Comment by pbteja1998** [comment]
It would be amazing to get a review of the article. Is there any way to send you the draft of the article once I finish writing it?

**Comment by jescalan** [comment]
Looks like you found me on twitter already - just hit me with a DM there and we can make it happen 😀

**Comment by pbteja1998** [comment]
> Looks like you found me on twitter already - just hit me with a DM there and we can make it happen 😀

Yeah, I did 😅. Will DM you there.

**Comment by agnosticoder** [comment]
Hey guys, have you got that blog ready yet or not 😀
