### ISSUE TITLE
Can babel dependencies be moved to devDependencies?

### ISSUE THREAD

**Issue by faceshape** [hashicorp/next-mdx-remote#76]
Hey,

Just a quick question, are these dependencies
`
   "@babel/core": "^7.11.1",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-react": "^7.10.4",
`
needed at runtime? Would it be possible to move them to devDependencies instead?

Context is, it's increasing our bundle sizes by a few megabytes by pulling these babel deps, I believe these are typically not needed outside of devDeps. Just want to confirm.

Thank you!

**Comment by jescalan** [comment]
They are needed at runtime for the `renderToString` function, but they should not be bundled on the client side unless you are using the library incorrectly - `renderToString` should only appear inside `getStaticProps` and the dependency will be tree-shaken out of your client bundle if this is the case.

**Comment by faceshape** [comment]
Yes, they are tree-shaken out of client build, but still present in server. It just seemed strange to see babel there, but now I see, makes sense, thank you so much for the very quick reply!

**Comment by jescalan** [comment]
True! Unfortunately we do need it, it's used to parse the mdx output and prepare it for the client side.
