### ISSUE TITLE
Does not work in IE11 as hydrate.js is not transpiled

### ISSUE THREAD

**Issue by cknitt** [hashicorp/next-mdx-remote#77]
In IE11, an exception occurs in every page that uses `next-mdx-remote/hydrate`. This is because `hydrate.js` is not transpiled.

As a workaround, we can use https://github.com/martpie/next-transpile-modules with the following `next.config.js`:

```js
const withTM = require('next-transpile-modules')(['next-mdx-remote/hydrate']);

module.exports = withTM();
```

But ideally, the source should be transpiled before publishing to npm.

**Comment by jescalan** [comment]
Happy to accept a PR to adjust hydrate to work with IE11, would prefer not to add an additional build process 😀

Sorry I didn't catch this, we do not support IE11 so it wasn't tested for. Should be fine in any other browser!
