### ISSUE TITLE
Exclude some components from hydration

### ISSUE THREAD

**Issue by valse** [hashicorp/next-mdx-remote#78]
Is it possible to exclude some components from re-render by the hydrate function?
In my example I have a custom Banner component that I need to SSR only without rehydrate it because this execution conflicts with the ad-server execution too.

I tried to not execute the hydrate completely and it works like expected but I need to "isolate" only one component type...

Thanks

**Comment by jescalan** [comment]
You can try this approach! https://github.com/vercel/next.js/tree/canary/examples/with-mdx-remote#conditional-custom-components

**Comment by jescalan** [comment]
Aside from this, the library will not pick up native functionality to partially hydrate. React itself and nextjs do not support partial hydration either.
