### ISSUE TITLE
Typescript definition: the hydrate definition is wrong

### ISSUE THREAD

**Issue by arsnl** [hashicorp/next-mdx-remote#82]
![error-1](https://user-images.githubusercontent.com/763489/103160549-a1d17700-47a4-11eb-91c1-4d2df4f7c98d.png)
![error-2](https://user-images.githubusercontent.com/763489/103160550-a26a0d80-47a4-11eb-97c8-5ec8c8995b72.png)

PR here: https://github.com/hashicorp/next-mdx-remote/pull/81
Details here: https://github.com/hashicorp/next-mdx-remote/pull/81#issuecomment-751404656

**Comment by jescalan** [comment]
Sorry about the mistaken close @arsnl, and thank you for the contribution. I'll have a release out with this fix shortly!
