### ISSUE TITLE
Issues rendering codeblocks

### ISSUE THREAD

**Issue by marcofranssen** [hashicorp/next-mdx-remote#83]
I'm having some trouble getting the code highlighting working properly.

I'm getting all of these kind of warnings when running nextjs in dev mode.

```
Warning: Received `true` for a non-boolean attribute `nginx/conf.d/default.conf`.

If you want to write it to the DOM, pass a string instead: nginx/conf.d/default.conf="true" or nginx/conf.d/default.conf={value.toString()}.
    in code
    in MDXCreateElement
    in pre
    in MDXCreateElement
    in Fragment
    in wrapper
    in MDXCreateElement
    in MDXContent
    in Context.Provider
    in MDXProvider
```

They are caused by codeblocks like these in my md files.

~~~md
```nginx nginx/conf.d/default.conf
server {

}
```
~~~

In my current blog they are rendered as seen here with a code-block title.

https://marcofranssen.nl/react-router-and-nginx-over-http2/

Over here you can see my attempt to migrate my current blog to nextjs using this library.

https://nextjs-blog-git-feature-mdx.marcofranssen.vercel.app/posts/202003-react-router-and-nginx-over-http2

Another first attempt was without using mdx, this renders the codeblocks properly with syntax highlighting, but I can't use some reusable codeblocks in my code.

https://nextjs-blog-git-feature-blog-posts.marcofranssen.vercel.app/posts/202003-react-router-and-nginx-over-http2

One thing I noticed is that the html using this library looks as following for codeblocks.

```html
<pre><code class="language-bash"># using yarn
yarn start
# using npm
npm run start
</code></pre>
```

While using the remark library it looks like this.

```html
<div class="remark-highlight"><pre class="language-bash"><code class="language-bash"><span class="token comment"># using yarn</span>
<span class="token function">yarn</span> <span class="token function">add</span> react-router-dom
<span class="token comment"># using npm</span>
<span class="token function">npm</span> <span class="token function">install</span> --save react-router-dom
</code></pre></div>
```

I'm not sure if this is caused by the warnings I'm seeing or if this is caused by another bug.

**Comment by jescalan** [comment]
I think the way you're doing the codeblock syntax is nonstandard. Normally the three backticks are followed only by a language, like so

````
```nginx
server {

}
```
````

Have you tried updating code blocks to work like this? I think you'd need a separate plugin to handle file names as part of the code block syntax.

**Comment by marcofranssen** [comment]
@jescalan updated one of my pages to have them removed, however I'm not getting any syntax highlighting. It seems the tokenization is not happening as done with this component for example. https://mdxjs.com/guides/syntax-highlighting#build-a-codeblock-component

**Comment by jescalan** [comment]
You do need to pass in a remark plugin for syntax highlighting to the options in `renderToString`, are you doing this?

**Comment by marcofranssen** [comment]
nope, do you have an example at hand? Seems I must have been overreading this.

**Comment by marcofranssen** [comment]
Got it. Thanks for the help.

```js
import prism from "remark-prism";

  return await renderToString(markdown, {
    components,
    mdxOptions: {
      remarkPlugins: [prism],
    },
  });
