### ISSUE TITLE
multiple source

### ISSUE THREAD

**Issue by ericsonluciano** [hashicorp/next-mdx-remote#85]
I'm trying to implement most of the markdown here the example of what I do with graphql-request
and I got this error with nextjs
```
Unhandled Runtime Error
ReferenceError: MDXContent is not defined

Call Stack
Function.eval
eval at <anonymous> (webpack-internal:///./node_modules/next-mdx-remote/hydrate.js), <anonymous> (4:28)
eval
node_modules/next-mdx-remote/hydrate.js (55:0)
```

here how I use it with MDXProvider Component as Component Provider

and I use types alias for these two as object type.
```
<ComponentProvider>{hydrate(blog.content)}</ComponentProvider>
<ComponentProvider>{hydrate(blog.other)}</ComponentProvider>
```
```
return {
  props: {
    blog: {
      content: await renderToString(
        he.decode(blog.content.markdown),
      ),
      other: await renderToString(
        he.decode(blog.other.markdown),
      ),
      ...blog,
   },
  },
};
```
Any idea how I can solve this? Thanks

**Comment by jescalan** [comment]
I don't _think_ this would actually work with the provider, because of the way next-mdx-remote works internally.  There's a PR I have been working on, but have been slow in taking across the finish line here https://github.com/hashicorp/next-mdx-remote/pull/35 to add support for providers though!

**Comment by ericsonluciano** [comment]
Already solve the issue with some research with types of next-mdx-remote. And forgot to say that I was using Typescript
instead of with `<ComponentProvider>{hydrate(blog.content)}</ComponentProvider>` i redirect to `{hydrate(blog.mdxContent, { components})}`
and from `const components = MDXComponent;` MDXComponent are like `const MDXComponent: MdxRemote.Components = {...}` for styling of each tag
and added `import { MdxRemote } from 'next-mdx-remote/types'`
and add types for whole Blog like this I'm still not sure if why I still need to make to other name instead of content and other
```
export type Blog = {
  blog: {
    id: string,
    mdxContent: MdxRemote.Source,
    mdxOther: MdxRemote.Source,
    content: {
      markdown: string,
    }
    other: {
      markdown: string,
    }
  }
}
```
and rename the props of content and other with mdxName
