### ISSUE TITLE
Composite components in MDX files

### ISSUE THREAD

**Issue by gazzza** [hashicorp/next-mdx-remote#87]
I have managed to get next-mdx-remote working with simple components and their children e.g.:

```
<Hints>
Here is your Hint
</Hints>
```

but if I want to make composite components e.g. 
```
<Hints>
  <Hint>
    <HintQuestion>
      Here is your hint
    </HintQuestion>
    <HintAnswer>
      Here is the answer to your hint
    </HintAnswer>
  </Hint>
</Hints>
```

I have to provide the JSX for the individual components when actually what I am doing is using the React.Children API to do some stuff with the individual components inside each <Hint> element provided to the <Hints> component myself.

Is there a way of achieving this?

**Comment by jescalan** [comment]
I'm not sure I fully understand the question - could you expand on this a bit?

**Comment by gazzza** [comment]
Apologies for the vague question - hopefully this makes it a little clearer. 

What I want is for my <Hint> component to do something like the following (this may not work because I'm still figuring out the code): 

```
import React from 'react';
import { Collapse } from 'antd';

const { Panel } = Collapse;

const Hint = ({ children }) => {
    const [HintQuestion, HintAnswer] = children.props.children;

    return (

        <Panel header={HintQuestion} key={HintQuestion}>
            {HintAnswer}
        </Panel>
    );
}

export default Hint;` 
```

This `<Hint>` component will be hydrated in my [id].js page which renders the .mdx content:

```
export default function Post({ postData }) {
    const content = hydrate(postData.mdxSource, { components });
```

the issue is that I need to provide `<HintQuestion>` and `<HintAnswer>` components to the hydrate function (which I guess makes sense) but what I actually want to do is some custom logic with those components (as per the `<Hint>` component above). 

Hopefully that makes some sense - happy to provide further clarification if needed. Thanks for your help.

**Comment by jescalan** [comment]
I think you may want to leverage this pattern to get what you're after: https://reactjs.org/docs/render-props.html

**Comment by gazzza** [comment]
My understanding is that utilising children in this way is basically a render props pattern. 

I guess the issue is that anything marked with <> tags requires being put into the components dict in the hydrate function. 

Obviously I can change my component to simply accept props to achieve the necessary behaviour but I felt the subcomponent API was a little more natural. 

I'll work around and look into render props a bit more to see if I can make it work - thanks for your help.

**Comment by jescalan** [comment]
You can use children as a render prop - its not really any different. But you'd have to make the children a function like this:

```jsx
<MyComponent>{(Foo) => {
  <Foo />
}}</MyComponent>
```

With the implementation being like:

```jsx
function MyComponent({ children }) {
  return <p>{children(Foo)}</p>
}

function Foo() {
  return <p>test content</p>
}
```

**Comment by jescalan** [comment]
Closing this but feel free to continue discussing!
