### ISSUE TITLE
Any way to know if hydrate() returns static or hydrated content ?

### ISSUE THREAD

**Issue by dipunj** [hashicorp/next-mdx-remote#88]
Hello,

Firstly, thank you for the awesome tool. I have been using this to build my personal blog and really happy with the results.

However there is a very very small issue.
As per the README, at [line 108 commit: 797f471, branch: master](https://github.com/hashicorp/next-mdx-remote/master/README.md#L108), static content would be rendered until hydration has finished.

Is there a way to know this state change?
Can we return a `isLoading` property for the `hydrate()` hook, which becomes `false` when the content has been hydrated.
Is it possible?

Consider the case when the typography is unconventional and FOIT would be preferred over FOUT.
In my case I am using tailwindcss which removes the default h1..h6 styles and the static content looks like a <p> tag. After hydration the css styles apply and make the h1...h6 tags look big and bold. This change isn't pleasant at all.

Thank you for reading through!

**Comment by jescalan** [comment]
Yes, this is possible. Would welcome a pull request for it, this should be a nice easy contribution 😀

**Comment by dipunj** [comment]
Awesome. I will submit one.

**Comment by igeligel** [comment]
Hey, here is a reproduction: https://github.com/igeligel/next-mdx-remote-72

So what I figured out. It breaks once you put in the [responsive styles](https://chakra-ui.com/docs/features/responsive-styles). The affected component is here:  https://github.com/igeligel/next-mdx-remote-72/blob/main/components/ChakraParagraph.tsx#L5

Feel free to check it out. I have the feeling it has something to do with babel's compilation, but I will check later.

**Comment by BRKalow** [comment]
Closing, per my comment on #89. As I mentioned, feel free to re-open if you still feel that this is needed.

Thanks for your contribution :heart:
