### ISSUE TITLE
Feature request: Support custom context Provider

### ISSUE THREAD

**Issue by devrsi0n** [hashicorp/next-mdx-remote#9]
👏 This project is awesome, but I face a context `undefined` error since I use [emotion theme](https://emotion.sh/docs/theming). Can we support custom context Provider for components?

**Comment by devrsi0n** [comment]
I can make a pull request if you don't mind.😀

**Comment by devrsi0n** [comment]
You can check the code here #10

**Comment by jescalan** [comment]
Ah ok this helps with the context behind that change - I saw the PR first and was like "why?" We can definitely get this merged, just want to make sure the feature is properly documented first!

**Comment by devrsi0n** [comment]
@jescalan Thanks, I'll polish the PR for document today

**Comment by JunichiSugiura** [comment]
This is exactly what I was searching for in order to integrate with [@theme-ui/prism](https://theme-ui.com/packages/prism#usage). Thank you!

**Comment by MatthewCaseres** [comment]
This can be closed now right? 
https://github.com/hashicorp/next-mdx-remote/pull/35
Thanks for the new features in 2.1!

**Comment by jescalan** [comment]
Correct, thanks for pointing this out!
